### ISSUE TITLE
bwrap: execvp readlink: Input/output error on Ubuntu 20.10

### ISSUE THREAD

**Issue by canadajones** [ValveSoftware/steam-runtime#354] opened 2021-01-21 23:59 UTC
Hello, I've been having an issue where none of the games I've previously had success with running on Proton will work on the newest (stable) version. The games I tried when troubleshooting were Raft and Human: Fall Flat, but no other game would work either. Raft and Human: Fall Flat work just fine when running on 5.0-10, but when trying any of the newer versions of Proton, they just open and close immediately. All of my games are on the sole local ext4 partition, and Vulkan is confirmed working on the system. Due to the introduction of containerisation in the latest version, as well as the recommendation of the logs to enable the flag, I've attached a log file with the STEAM_LINUX_RUNTIME_VERBOSE environment variable set to 1. 

Proton Version:
5.13-5

OS:
Ubuntu 20.10

GPU
Radeon RX 5700 XT, with the included 20.10 drivers.

Anything else missing, drop me a comment and I'll fill it in.
[protonlogs.txt](https://github.com/ValveSoftware/Proton/files/5852760/protonlogs.txt)

**Comment by kisak-valve** [comment] 2021-01-22 00:05
Hello @canadajones, your log reads like there's a Pressure Vessel issue happening. Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share your findings.

**Comment by canadajones** [comment] 2021-01-22 01:05
Here, running Raft, still with verbose logging on. I don't know if there's anything else you want me to do, so please tell me if so.

[slr-app648800-s2c50eacafedbf758.log](https://github.com/ValveSoftware/steam-runtime/files/5852952/slr-app648800-s2c50eacafedbf758.log)

**Comment by smcv** [comment] 2021-01-22 10:52
> bwrap: execvp readlink: Input/output error

I think @kisak-valve is right to think that this is the root cause.

This is really weird. "Input/output error" (internally `EIO`) is normally only seen when there's a problem with getting data to/from the disk - filesystem corruption or a failing disk or something like that.

Does this disk mostly work reliably?

Do you get warnings in the system log (systemd journal)? They'd most likely be attributed to `kernel`, I think.

Is *Steam Linux Runtime - soldier* installed on the same ext4 filesystem as the games?

Is the ext4 filesystem using any new/odd features, like the recently-added case-insensitive support?

**Comment by smcv** [comment] 2021-01-22 10:55
If there are any FUSE, overlay or encrypted filesystems in the I/O path for the Steam library, that's also relevant information. Whole-disk encryption (LUKS, cryptsetup) shouldn't matter, but encryption for individual directories (ecryptfs) might have an effect.

**Comment by canadajones** [comment] 2021-01-22 12:37
Everything is on the same ext4 partition (Screenshot of gparted): That is the sole disk present in the system right now.
![image](https://user-images.githubusercontent.com/48071533/105490933-d4906180-5cb5-11eb-976f-ab9c892fecbe.png)

it's a new NVMe M.2 SSD that has been removed from and reinserted into the system a couple of times now (~6) as a part of a botched motherboard swap. The SSD shows no signs of damage in any capacity, and it was always handled on a hard floor with an ESD bracelet on. However, I have had Proton have similar issues in like December of last year, but then it fixed itself (dunno if it's the same root cause). I don't really have any problems elsewhere with the filesystem, this is about the only issue I've found.

**Comment by canadajones** [comment] 2021-01-22 12:38
Also, no, there is no special setup on the filesystem, it's all just bog standard default ubuntu.

**Comment by canadajones** [comment] 2021-01-24 01:28
Could rwx permissions cause this error? I might have accidentally chown'd or chmod'd something I shouldn't have.

**Comment by smcv** [comment] 2021-01-25 12:21
> Could rwx permissions cause this error?

I wouldn't expect so. Even if you take away permissions that we need, I'd expect to see `EACCES` "Permission denied", not `EIO` "Input/output error".

**Comment by smcv** [comment] 2021-01-25 12:33
If you care about the data on this disk, I would suggest making sure you have backups, and looking into the possibility of physical device damage ([SMART test](https://help.ubuntu.com/stable/ubuntu-help/disk-check.html.en), block read test) or filesystem corruption (check with `fsck`, or "Check filesystem" in the Disks utility).

The `EIO` error *might* be just a software bug, in pressure-vessel or something else that we're using - but equally it might be a problem with the underlying system, and I wouldn't want you to lose data as a result.

**Comment by smcv** [comment] 2021-01-25 12:39
After making sure you have backups of any important data on this system, you could try renaming the directory `SteamLinuxRuntime_soldier/soldier_0.20210105.2` to `issue354`, and launching the game again. This will re-unpack the runtime, and might launch successfully. Please keep the old `issue354` directory, instead of deleting it: that will let us check whether it has been damaged somehow.

(If you are using a newer version of soldier by the time you read this, then the directory might have a different version number, or might be in the `var` subdirectory, like `SteamLinuxRuntime_soldier/var/soldier_0.20210114.2`.)

**Comment by canadajones** [comment] 2021-01-29 19:20
Hey, I finally got around to trying that, and it seemed to make everything work again. I've attached the old `issue354` folder.

[issue354](https://drive.google.com/file/d/164kT5SK9HXk1_H1F0QfHG2UnkbLfR5xW/view?usp=sharing)

**Comment by smcv** [comment] 2021-02-02 13:15
> I've attached the old issue354 folder

A lot of the files in that zip archive have been truncated to 0 bytes long. `files/bin` seems to be OK, but `files/lib/os-release` and all the files in `files/lib/x86_64-linux-gnu` are empty, which they should not be.

I suspect this might be a side-effect of whatever was causing bwrap to fail with `EIO` (specifically, the kernel is failing to run the executable because it can't read it successfully). It looks as though whatever program you used to create the zip archive has ignored the I/O error, and treated it as though the file was empty (0 bytes).

Sorry, I don't think this is something that pressure-vessel can fix. If ordinary file accesses get truncated, then there is a deeper problem than anything we're doing.

Please make sure you have backups of anything important that is stored on this system, then look into disk diagnostics (SMART test, filesystem check for corruption, etc.) to avoid further data loss.

**Comment by canadajones** [comment] 2021-02-17 12:04
I ran fsck and badblocks (read-only, since this is an SSD and I don't really want to wear it down. I didn't expect this to yield much) and they both came up fine regarding the SSD. The filesystem was trashed, probably due to some botched virtual machines. Anyways, I wiped the drive and reinstalled Ubuntu 20.10. I'll get back to you if this reoccurs.

**Comment by smcv** [comment] 2021-02-17 12:50
> The filesystem was trashed

@canadajones, please reopen or open a new issue if this recurs, but I suspect it was the filesystem rather than pressure-vessel that's at fault here.

This is not something that ordinary applications are ever going to cope with, so I think pressure-vessel is doing the right thing (report the error and leave it to the user/sysadmin to deal with). @kisak-valve, let's close this?

**Closed** 2021-02-17 12:53 UTC
Labels: Pressure Vessel
