### ISSUE TITLE
ALSA only regression in SLR v0.20210317.0

### ISSUE THREAD

**Issue by Cat-Lady** [ValveSoftware/steam-runtime#395] opened 2021-04-18 00:52 UTC
* Steam Runtime Version: 
public AND client_beta

* Distribution:
Debian 10+
 
* Link to your full system information
[system-information.log](https://github.com/ValveSoftware/steam-runtime/files/6330301/system-information.log)

 
* Are you using the Steam Linux Runtime compatibility tool?:
Soldier - Yes, Scout - No.

#### Please describe your issue in as much detail as possible:

Hello Steam'ies,
With current version of Soldier:
[VERSIONS.txt](https://github.com/ValveSoftware/steam-runtime/files/6330304/VERSIONS.txt)
...and, if using official version of Proton that is > than 5.0-10 (5.13 and every later one, including Experimental), there is no sound output if using ALSA.

The issue might be related to:
https://github.com/ValveSoftware/steam-runtime/issues/384

Relevant logs:
Soldier:
[slr-app239350-se7b620a6e6329d80.log](https://github.com/ValveSoftware/steam-runtime/files/6330308/slr-app239350-se7b620a6e6329d80.log)

Proton:
[steam-239350.log](https://github.com/ValveSoftware/steam-runtime/files/6330310/steam-239350.log)

Relevant snippet from the last one seems to be:
```
20891.123:0124:0128:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winepulse.drv" at F60A0000: builtin
20891.123:0124:0128:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\winepulse.drv" : builtin
20891.124:0124:0128:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\winealsa.drv" at F6090000: builtin
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
```

Additional informations:
1. Trying to set sound driver to ALSA via registry inside prefix doesn't change anything (as expected - autodetection seems to correctly assume ALSA, yet it still tries to connect to Pulse).

2. If using official Proton 5.0 or earlier, there are no:
```ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused```

...lines, and sound works as expected.

3. Trying to use ``client_beta`` version of Soldier and steam client beta doesn't help with the issue.

4. Using ``previous_release`` version of Soldier allows sounds to work with ALSA for all official versions of Proton, including experimental.
---

Side note:
Thank you for keeping ALSA compatibility. It is important for users like me. I am happy to provide any other logs that might help to resolve the issue.

**Comment by smcv** [comment] 2021-04-19 11:44
This regression was previously reported in #344 and #384, although it is not in the original scope of those issues. Let's use this issue number to represent the regression.

The root cause is that some code added in v0.20210317.0, which we had intended to only run for PulseAudio users (to fix part of #371), was accidentally also run for non-PulseAudio users (where it's useless, and could break previously-working audio). A fix should be in the next beta (`SteamLinuxRuntime_soldier/VERSIONS.txt` will say `pressure-vessel 0.20210415.0+srt1` or later).

Workaround: use the `previous_release` until the next beta becomes available.

Alternative workaround: explicitly configuring `~/.asoundrc` with something like

```
defaults.pcm.!card 0
defaults.ctl.!card 0
```

might be able to avoid the regression.

**Comment by smcv** [comment] 2021-04-19 11:51
@kisak-valve or @Cat-Lady, please could you retitle this to something like "ALSA regression in SLR v0.20210317.0 when not using PulseAudio"?

Let's use this issue report to represent the regression that happened a few days ago. If you are having different problems with ALSA, please open a separate issue.

**Comment by smcv** [comment] 2021-04-21 11:43
> Thank you for keeping ALSA compatibility. It is important for users like me

To be clear, this is not something that we really support: we try not to break it, but we also don't routinely test it. Using PulseAudio or Pipewire as a sound server to multiplex audio streams to a single hardware device is the default/expected setup in most distributions and desktop environments, and is what we would recommend as the most likely thing to be reliable.

The further away from typical configurations you are, the more likely you are to encounter weird bugs.

**Comment by Cat-Lady** [comment] 2021-04-23 02:49
I can confirm that the client_beta, consisting of ``pressure-vessel	0.20210415.0+srt1`` is working fine on my end, again. Thank you!

**Comment by smcv** [comment] 2021-04-23 13:04
Let's leave this open until 0.20210415.0 or later goes from beta to stable, so that users of plain ALSA audio can find out about needing the beta until then.

**Comment by UFeindschiff** [comment] 2021-04-30 17:00
Unfortunately, today's update broke things when using a custom ALSA config (was using the previous_release branch before). I guess the previous beta went live which resulted in previous_release to be the broken release. 

Unfortunately neither on `pressure-vessel 0.20210415.0+srt1`(both stable and client_beta) nor on `pressure-vessel 0.20210317.0+srt1` (previous_release) have I any sound playback despite working perfectly on all previous releases.

My ALSA config (which I copied to /path/to/soldier/var/buildid/files/etc/asound.conf) is the following:
 
`defaults.pcm.card 2
defaults.ctl.card 2
pcm.multi {
    type route;
    slave.pcm {
        type multi;
        slaves.a.pcm "dmixerproper";
        slaves.b.pcm "dmixerloop";
        slaves.a.channels 2;
        slaves.b.channels 2;
        bindings.0.slave a;
        bindings.0.channel 0;
        bindings.1.slave a;
        bindings.1.channel 1;
        bindings.2.slave b;
        bindings.2.channel 0;
        bindings.3.slave b;
        bindings.3.channel 1;
    }

    ttable.0.0 1;
    ttable.1.1 1;
    ttable.0.2 1;
    ttable.1.3 1;
}



pcm.dmixerproper  {
        type dmix
        ipc_key 1024
        slave {
                pcm "output"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}


pcm.dmixerloop  {
        type dmix
        ipc_key 1024
        slave {
                pcm "hw:Loopback,0,0"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

pcm.dsnooper {
    type dsnoop
    ipc_key 2048
    ipc_perm 0666 
    slave.pcm "output"
    slave 
    {
        period_time 0
        period_size 1024
        buffer_size 4096
        channels 2 
    }
    bindings {
        0 0
        1 1
    }
}

pcm.audioout {
        type plug
        slave.pcm "multi"
}

pcm.!default {
        type asym
        playback.pcm "audioout"
        capture.pcm "dsnooper"
} 

pcm.output {
        type hw
        card 2
}

pcm.loopin {
        type plug
        slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
        type plug
        slave.pcm "hw:Loopback,1,0"
}`

**Comment by smcv** [comment] 2021-04-30 17:32
> Unfortunately, today's update broke things when using a custom ALSA config

Please try putting your custom config in `~/.asoundrc` instead.

**Comment by smcv** [comment] 2021-04-30 17:54
If you are not @Cat-Lady, and your symptoms in terms of fixed/working versions are not the same as what @Cat-Lady reported, then please use a separate issue report to discuss those symptoms.

The big picture here is that we can't really support completely arbitrary ALSA configurations: we don't deliberately break plain ALSA, but neither is it something that is always expected to work, and I would recommend using a sound server (PulseAudio or Pipewire). The approach taken by typical sound servers, with a single `AF_UNIX` socket and a relatively stable, forwards- and backwards-compatible IPC protocol across that socket, is ideal for containers - processes in the container can just speak the same protocol across the same socket and it'll work (like network-transparency, but between containers rather than between machines). It's no accident that X11, Wayland, D-Bus, PulseAudio and Pipewire (and mpd, and gpg-agent, and ssh-agent, and Docker, and many more) are all based on relatively long-term-stable socket protocols, and all work fine between containers with dissimilar library versions.

`/etc/asound.conf` and `~/.asoundrc` are configuration for the ALSA client library `libasound.so.2` on your host system, and its various plugins. Some of the plugins talk directly to the kernel's ALSA interfaces (`/dev/snd/*`), but some do arbitrary other things, like talking to a sound server (PulseAudio etc.) or doing their own IPC which doesn't necessarily cross the container boundary well (`dmix`, `dsnoop`).

The whole point of the container runtime is that it uses a predictable library stack for games, but this means that the container has a different version of `libasound.so.2` and a different set of plugins, so configuration that is valid for one is not necessarily valid for the other - particularly when `libasound.so.2` configuration is close to being a programming language. We don't deliberately break this, but we are never going to be able to guarantee that it will work for everyone either.

However, `libasound.so.2` has two roles: it's the low-level client library for `/dev/snd/*`, and it's also an audio abstraction layer that applications use to target multiple audio backends (direct access to `/dev/snd/*`, or `dmix`, or IPC to a sound server like PulseAudio, or anything else you can write a plugin for). For the subset of games that use `libasound.so.2` (as opposed to SDL or OpenAL or PortAudio or similar) as their audio interface, we need to make sure those games can play audio successfully, and for most people that means `libasound_module_pcm_pulse.so`.

**Comment by smcv** [comment] 2021-05-04 11:17
> Let's leave this open until 0.20210415.0 or later goes from beta to stable

This has now happened. @kisak-valve or @Cat-Lady, please could you close this?

**Comment by kisak-valve** [comment] 2021-05-04 11:42
Closing per the last comment.

**Closed by kisak-valve** 2021-05-04 11:42 UTC
Labels: Need Retest, Pressure Vessel
