### ISSUE TITLE
Can't bring up Steam overlay since Jan 19th update

### ISSUE THREAD

**Issue by radical-equanimity** [ValveSoftware/steam-runtime#69] opened 2017-02-01 23:41 UTC
Before the Jan 19th update, I was able to bring up Steam overlay and take screenshots in game. Now I cannot bring up overlay or take screenshots in any game. I'm on Ubuntu 16.04 64-bit with NVidia 378.09 proprietary drivers. I am frustrated that there is no way to rollback Steam client to previous version. It seems testing at Valve is not sufficient to have such an automatic update system with no fallback

**Comment by kisak-valve** [comment] 2017-02-02 00:42
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/4827.

**Closed by kisak-valve** 2017-02-02 00:42 UTC
