### ISSUE TITLE
Steam Linux Runtime cannot start on customized distro using non-standard ld.so.cache location

### ISSUE THREAD

**Issue by yurytch** [ValveSoftware/steam-runtime#666] opened 2024-04-29 12:06 UTC
#### Your system information

* Steam client version (build number or date): 1.0.0.79
* Distribution (e.g. Ubuntu): Slackware
* Opted into Steam client beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] yes
* Steam Logs: [generate by running this command in a terminal `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`] 
[steam-logs.tar.gz](https://github.com/ValveSoftware/steam-for-linux/files/15148789/steam-logs.tar.gz)

* GPU: AMD Ryzen Vega

#### Please describe your issue in as much detail as possible:
I expected `steam` executable to run and enable me to download things from Steam. Instead it retries a couple of times and then gives me this:
`src/steamUI/steamuisharedjscontroller.cpp (546) : Failed creating offscreen shared JS context`
then it produces zenity dialog with options for restarting steam. None works.

#### Steps for reproducing this issue:

1. Install
2. Run

**Comment by yurytch** [comment] 2024-04-29 16:18
Thank you! I've seen that line in logs, but I believe I've never had even read access to ld.so.cache from an ordinary user account on Slackware. So didn't take notice.

**Comment by TTimo** [comment] 2024-04-29 16:26
I'm not sure that error is relevant to your problem. Please test with Steam beta as several fixes have been made to the steamwebhelper startup in beta already. You can opt in from the command line like this: `echo publicbeta > ~/.steam/steam/package/beta`

**Comment by yurytch** [comment] 2024-04-30 04:06
@TTimo Thanks, but no, switching to beta didn't help. 
The line is now 545, and that's that. 
```
src/steamUI/steamuisharedjscontroller.cpp (545) : Failed creating offscreen shared JS context
```
And why can't the process be interrupted by Ctrl+C after being told to restart? It runs the cycle of `Starting steamwebhelper under bootstrap sniper steam runtime...` forever.

By the way, my home dir is sitting under symlinked subdir, I've seen some talk here about that. But I have tried with clean new user account with a 'real' home dir too, the result was the same.

**Comment by smcv** [comment] 2024-04-30 17:36
Please run `/sbin/ldconfig -pv` and `/sbin/ldconfig -XNv`, and attach their output. If `ldconfig(8)` is located somewhere different on a Slackware system, run it by that path instead.

After that, please try running the Steam beta with `STEAM_LINUX_RUNTIME_VERBOSE=1` in the environment, and attach the resulting logs for further investigation.

Steam's output to the terminal is unlikely to be the interesting thing here, it is the logs that will be important (particularly `steamwebhelper.log`).

> I believe I've never had even read access to ld.so.cache from an ordinary user account on Slackware

The normal arrangement on distributions that don't patch or reconfigure this part of glibc (such as the Debian and Red Hat families) is that ordinary, unprivileged users *do* have read access to `/etc/ld.so.cache`. If you don't, then the cache doesn't serve its purpose - the whole point is that ordinary unprivileged programs can use it to speed up shared library loading.

It's OK if you don't have access to `/var/cache/ldconfig/aux-cache`: for example, on Debian-derived systems, we normally don't. An error message involving `/var/cache/ldconfig/ld.so.cache` should only be seen if we can't load the traditional/interoperable path `/etc/ld.so.cache`, and therefore we fall back to trying the less common paths. ClearLinux's `/var/cache/ldconfig/ld.so.cache` happens to be the last one in our list.

If you already know that Slackware uses unusual or non-standard paths for the cache and configuration used by `ld.so(8)` and `ldconfig(8)`, it would be helpful if you can describe them, because the container runtime framework needs to know how this stuff works on each distribution in order to operate as intended. Normally it's `/etc/ld.so.cache`, built by `/sbin/ldconfig` according to configuration that starts at `/etc/ld.so.conf`. A few distributions are known to do this differently (ClearLinux, Exherbo, possibly Solus) but as far as I was previously aware, all of the older distribution families like Debian, Gentoo, Red Hat and Slackware use the interoperable/traditional paths.

> By the way, my home dir is sitting under symlinked subdir, I've seen some talk here about that. But I have tried with clean new user account with a 'real' home dir too, the result was the same.

To reduce the number of variables, please start by investigating this from a user account whose "official" home directory does not have symlinks in its path. When we have got that scenario working, we can look at whether your symlinked home directory is creating any different problems.

Using symbolic links to offload a directory to a different filesystem often causes trouble for container-related things (because the meaning of the symlink changes on entering the container), so I would recommend preferring to use bind-mounts if possible.

**Comment by smcv** [comment] 2024-05-03 18:13
@kisak-valve, I think a better title for this one would be something like:

```
SLR container cannot start on customized distro not using /etc/ld.so.cache
```

**Comment by yurytch** [comment] 2024-05-03 20:13
Thank you.
> Minimizing writes to SSDs was a practical concern for very early generations of SSD hardware

Still, some habits and idiosyncrasies *had* been acquired in that era. ))

In fact, if just `ld.so.cache` moved to a non-standard location goes as 'abnormal', what would you guys say, if you saw a complete description of my system, which I still fancy to be Slackware, at its heart, like. ))

Still, apps I use (and I use quite a few) do not seem to mind.

Does Steam client work from inside a virtual machine? I might be better off just installing some small-sized Ubuntu in a VM. I need Steam only for the downloading of things I've bought to work, anyway.

Symlinking from an unstandard location of ld.so.cache to /etc won't work with unpatched GLIBC, at least in Slackware. And symlinking that way with patched GLIBC (i.e. my system) doesn't satisfy Steam client.

So... it's a VM or a separate installation or nothing for me, right?

P.S. I must congratulate you on an very reasonable tone and proper conduct of a discussion you are keeping. It's always a pleasure to see good work (at communication in that case). Thank you.

**Comment by smcv** [comment] 2024-05-06 11:57
> Still, apps I use (and I use quite a few) do not seem to mind.

Other apps are probably not constructing a container environment on-demand that is a hybrid of your host system's graphics drivers and a more predictable application-level library stack, which has been a necessary thing for Steam to be portable to many Linux distributions, but does require it to make lower-level assumptions about glibc than is conventional!

Thinking of Steam as an app like any other is not really accurate - it's more like an app framework, operating in the same space as things like Flatpak, Snap or AppImage.

> Does Steam client work from inside a virtual machine? I might be better off just installing some small-sized Ubuntu in a VM.

I don't think we would consider that to be a fully-supported situation, but in general yes it does work (I regularly use VMs to make sure that a fresh Steam installation is still runnable in various older Ubuntu releases).

The main issue you will have in a VM is that the purpose of Steam is to download and run games, but most modern games require GPU-accelerated rendering and will not usually have acceptable performance in a VM. Older or less-demanding games are more likely to work acceptably with software rendering (Mesa's llvmpipe for GL/EGL, and lavapipe for Vulkan). You might be able to pass through rendering to the host with technologies like VirGL, or use dedicated GPU passthrough to make a GPU unavailable to the host and dedicate it to the VM, but those are not really mature enough to be supportable or recommended.

Similarly, Steam running in a VM will be unable to access gamepads, joysticks and other game controllers unless you go to significant effort to make it possible.

Using a container technology like Flatpak could be another option. Valve does not officially support the Flathub community's unofficial Flatpak app, but in practice it often does work, and unlike a VM, it does get direct access to the GPU and game controllers. (There is also a Snap app, but that one generally works less well than its Flatpak equivalent and I wouldn't recommend it, especially on a non-Ubuntu host.)

> I need Steam only for the downloading of things I've bought

You probably know this already, but downloading a game via Steam and then running it directly (without going via Steam) is not something that can be guaranteed to work. It will likely work for some games but not others. The only scenario that is expected to be tested and supported by all Steam game developers/publishers is launching their game via Steam, and for anything beyond that, it's up to the developer/publisher whether they aim to support it or not.

This is partly because of Steam's compatibility frameworks (the Steam Runtime) which make games work on a wider range of distributions but are not active if you run the game manually; partly because some game developers/publishers have chosen to make Steam a requirement as a licensing check (DRM); and partly because some game developers/publishers have chosen to rely on other Steam features such as cloud storage and gamepad mapping.

**Comment by yurytch** [comment] 2024-05-07 07:22
> Other apps are probably not constructing a container environment on-demand that is a hybrid of your host system's graphics drivers and a more predictable application-level library stack, which has been a necessary thing for Steam to be portable to many Linux distributions, but does require it to make lower-level assumptions about glibc than is conventional!

Yes, the analogy with AppImages has occured to me.
Is there publicly available documentation describing what Steam does/expects with/on its host system? Maybe I'm hitting something trivial. In 2021 or so Steam had worked for me, on less unconventionally built Slackware system.

**Comment by RyuzakiKK** [comment] 2024-05-07 07:43
The assumptions about the host system are documented in https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/distro-assumptions.md

**Comment by yurytch** [comment] 2024-05-19 10:15
I've finally found some time and looked into this, and as it happened, it was solvable quite trivially, actually.

I've just recompiled my glibc packages with the recognised `/var/cache/ldconfig` location. The `/var/db` was there before for purely aesthetical reasons.

Steam client works now. The game works, too.

I imagine you might want to add that to your documentation. Thank you guys for your help. The issue may be closed now.

**Comment by smcv** [comment] 2024-05-20 10:39
> I imagine you might want to add that to your documentation.

It's already documented: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/distro-assumptions.md?ref_type=heads#shared-libraries

> The issue may be closed now.

@kisak-valve, please close this as "not planned".

**Closed** 2024-05-20 13:03 UTC
Labels: Pressure Vessel

**Comment by yurytch** [comment] 2024-05-20 18:50
> > I imagine you might want to add that to your documentation.
> It's already documented: 
Not quite. That documentation might be interpreted (possibly superficially) as 'having ld.so.cache at one of the standard locations is sufficient' (tried that previously, with no success). 
While what really works is 'having glibc actually use ld.so.cache residing at one of the standard locations'. Maybe it's obvious to Steam developers but not to us 'plebes'. ))
