### ISSUE TITLE
War Thunder (236390) No internet connection

### ISSUE THREAD

**Issue by dennis1248** [ValveSoftware/steam-runtime#227] opened 2020-02-06 12:54 UTC
This game is unable to login, load "news" and update the launcher.

### The launcher
```
GameAction [AppID 236390, ActionID 4] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 236390, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 236390, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 236390, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 236390, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 236390 "", ProcID 12312, IP 0.0.0.0:0
Starting app 236390
>>> Adding process 12312 for game ID 236390
GameAction [AppID 236390, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/dennis/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 236390, ActionID 4] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/dennis/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dennis/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 12313 for game ID 236390
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
pressure-vessel-locale-gen: No locales need to be generated
/usr/share/libdrm/amdgpu.ids: No such file or directory
Failed to create /mnt/sda1/SteamLibrary/steamapps/shadercache/236390 for shader cache (No such file or directory)---disabling.
```
### Launching and force closing the game
```
Game update: AppID 236390 "", ProcID 14573, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 14573): SteamUser017 / User
RecordSteamInterfaceCreation (PID 14573): SteamFriends014 / Friends
RecordSteamInterfaceCreation (PID 14573): SteamUtils006 / Utils
RecordSteamInterfaceCreation (PID 14573): SteamMatchMaking009 / Matchmaking
RecordSteamInterfaceCreation (PID 14573): SteamMatchMakingServers002 / MatchmakingServers
RecordSteamInterfaceCreation (PID 14573): STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
RecordSteamInterfaceCreation (PID 14573): STEAMAPPS_INTERFACE_VERSION006 / Apps
RecordSteamInterfaceCreation (PID 14573): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 14573): STEAMREMOTESTORAGE_INTERFACE_VERSION012 / RemoteStorage
RecordSteamInterfaceCreation (PID 14573): STEAMSCREENSHOTS_INTERFACE_VERSION002 / Screenshots
RecordSteamInterfaceCreation (PID 14573): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 14573): STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001 / UnifiedMessages
RecordSteamInterfaceCreation (PID 14573): STEAMCONTROLLER_INTERFACE_VERSION / Controller
RecordSteamInterfaceCreation (PID 14573): STEAMUGC_INTERFACE_VERSION001 / UGC
Setting breakpad minidump AppID = 236390
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198146216308 [API loaded no]
/usr/share/libdrm/amdgpu.ids: No such file or directory
Failed to create /mnt/sda1/SteamLibrary/steamapps/shadercache/236390 for shader cache (No such file or directory)---disabling.
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
RecordSteamInterfaceCreation (PID 14573): SteamUtils006 / Utils
Game removed: AppID 236390 "", ProcID 14573 
Game 236390 created interface STEAMAPPS_INTERFACE_VERSION006 / Apps
Game 236390 created interface STEAMCONTROLLER_INTERFACE_VERSION / Controller
Game 236390 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 236390 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION012 / RemoteStorage
Game 236390 created interface STEAMSCREENSHOTS_INTERFACE_VERSION002 / Screenshots
Game 236390 created interface STEAMUGC_INTERFACE_VERSION001 / UGC
Game 236390 created interface STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001 / UnifiedMessages
Game 236390 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 236390 created interface SteamFriends014 / Friends
Game 236390 created interface SteamMatchMaking009 / Matchmaking
Game 236390 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 236390 created interface SteamNetworking005 / Networking
Game 236390 created interface SteamUser017 / User
Game 236390 created interface SteamUtils006 / Utils
Game 236390 method call count for IClientUser::CancelAuthTicket : 2
Game 236390 method call count for IClientUser::BLoggedOn : 1
Game 236390 method call count for IClientUser::GetAuthSessionTicket : 2
Game 236390 method call count for IClientUser::GetSteamID : 3
Game 236390 method call count for IClientFriends::GetPersonaName : 1
Game 236390 method call count for IClientUtils::GetAppID : 19
Game 236390 method call count for IClientUtils::RecordSteamInterfaceCreation : 15
Game 236390 method call count for IClientApps::GetDLCCount : 54
Game 236390 method call count for IClientApps::BGetDLCDataByIndex : 52
Game 236390 method call count for IClientAppManager::IsAppDlcInstalled : 41
Game 236390 method call count for IClientUserStats::RequestCurrentStats : 1
Uploaded AppInterfaceStats to Steam
Exiting app 236390
```

The Steam client doesn't appear to be spitting out anything noteworthy.

The errors about gameoverlayrenderer you can ignore, the game has bugs with the Steam overlay so I disabled it.

**Comment by smcv** [comment] 2020-09-08 13:39
This might be related to #226. Please try the steps from <https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-587125941>, <https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-587126621> and <https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-688870881>.

**Comment by smcv** [comment] 2020-09-14 11:27
Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

If that version works, then we can consider this issue to be a duplicate of #226.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

**Comment by dennis1248** [comment] 2020-09-14 15:02
Hey @smcv 

I tested this for a few hours yesterday, the issue is indeed fixed in the latest Steam Linux Runtime client_beta.

**Comment by kisak-valve** [comment] 2020-09-14 15:03
Thanks for retesting @dennis1248, closing as a duplicate of #226.

**Closed by kisak-valve** 2020-09-14 15:03 UTC
Labels: Need Retest, Pressure Vessel
