### ISSUE TITLE
Game supported by Proton does not start if the steamapps/compatdata/648800/pfx directory is not owned by the user

### ISSUE THREAD

**Issue by emanuelegissi** [ValveSoftware/steam-runtime#477] opened 2021-11-14 15:10 UTC
Hi, I am on Linux Fedora 35.

I set up my kids Steam in their own session.
The two kids (<kid1>, <kid2>) are in the same <steam> group.
I share an only <steam-library> folder. The folder is owned by <root.steam>.
Both kids have read and write privileges on the folders and files, thanks to ACLs lists.

No problem with native games. Both kid1 and kid2 can run any shared game installed by the other.

But if kid1 installs a game supported by Proton in the shared folder, kid2 cannot run it. 
The Proton supported game does not start because:
wine: '/mnt/library/steam-library/steamapps/compatdata/648800/pfx' is not owned by you

If I change the pfx directory and files owner to kid2, the game starts normally:
sudo chown kid2.steam -R /mnt/library/steam-library/steamapps/compatdata/648800/pfx

But then it is kid1 that cannot run that game.

So the problem is only the file owner, even if, thanks to ACLs, both kid1 and kid2 can read and write all the files of the shared steam-library.

I am available for further testing. Thank you.

**Comment by kisak-valve** [comment] 2021-11-14 15:32
Hello @emanuelegissi, this is a general characteristic of the upstream wine project and blocks an entire category of hard to troubleshoot file permission issues. This is not in any way a steam runtime issue which is the issue tracker you've reported this to.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/4820.

**Closed by kisak-valve** 2021-11-14 15:32 UTC

**Comment by emanuelegissi** [comment] 2021-11-14 16:47
Sorry, I am going to report it to the wine project then.
Anyway thank you for Steam on Linux and Proton.

**Comment by emanuelegissi** [comment] 2021-11-14 16:54
Well, I read the ValveSoftware/Proton#4820 bug report you mentioned. The other user was much smarter than me and even offered a possibly working pull request. May I ask if it is going to be accepted in the next release? Thank you again
