### ISSUE TITLE
soldier >= 0.20210629.0 not working on NixOS

### ISSUE THREAD

**Issue by baracoder** [ValveSoftware/steam-runtime#431] opened 2021-07-19 22:19 UTC
#### Your system information

* Steam client version (build number or date): 16-07-2021
* Distribution (e.g. Ubuntu): NixOS
* Opted into Steam client beta?: No (Tried both)
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Proton based games won't launch with soldier 0.20210629.0

Gist containing logs from [Soldat](https://store.steampowered.com/app/638490/Soldat/) 
* `default-slr-app638490-t20210721T203154.log` and `default-VERSIONS.txt` (not working)
* `previous_release-slr-app638490-t20210721T202526.log` and `previous_release-VERSIONS.txt` (working)
* `system-information.txt`

https://gist.github.com/baracoder/905249402c68d64bc89192da02f0ccdd 

#### Steps for reproducing this issue:

1. Switch Steam Linux Runtime - Soldier Beta to `None` and launch [Soldat](https://store.steampowered.com/app/638490/Soldat/) -> fails
2. Switch Steam Linux Runtime - Soldier Beta to `previous_release` and relaunch the same game -> works

**Comment by omgthegreenranger** [comment] 2021-07-20 21:09
Discovered this yesterday, too. When launching LEGO games, it would give me an error about my video card being out of date and not supporting Shader Model 3. Star Trek Online launcher was telling me that support for my card was ended.

**Comment by smcv** [comment] 2021-07-21 10:39
@omgthegreenranger: Your symptoms seem different. Please open a separate issue with full details and logs.

If we mix up more than one root cause in the same issue report, it gets confusing very quickly and we have to waste a lot of time disentangling the situation, which is time we can't spend actually fixing bugs - so please help us to help you.

**Comment by smcv** [comment] 2021-07-21 10:43
@kisak-valve (or @baracoder): Please could you change the title of this issue to something like "soldier >= 0.20210629.0 not working on NixOS" so we won't get unrelated regressions reported here?

We don't have all the details yet, but I'm reasonably confident that this is going to be a NixOS-specific issue.

**Comment by smcv** [comment] 2021-07-21 11:11
@baracoder, I think your [logs](https://gist.github.com/baracoder/d825bad7f2a6994e5e08c728855406d8) are probably the wrong way round? The one you've labelled "default" looks like a game launching successfully, and the one you've labelled "previous_release" looks like pressure-vessel failing to launch with:

> `bwrap: execvp /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb: No such file or directory`

but your issue report says that it's `default` that is failing and `previous_release` is OK, so I assume they're just mislabelled?

I think this will apply equally for all games that run under Proton 5.13 or newer, but just in case the specific game makes a difference, it would be useful to test with a small demo or free-to-play game, so that everyone who is experiencing this issue can easily test the same thing. [The Expendabros](https://store.steampowered.com/app/312990/The_Expendabros/) and [Soldat](https://store.steampowered.com/app/638490/Soldat/) are examples of small Windows-only games that we often use as test-cases.

We will need some more details to solve this: please see <https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information>. As a reminder, please capture:

* [ ] the Help -> System Information
* [ ] the Steam Linux Runtime log `SteamLinuxRuntime_soldier/var/slr-app*-*.log` created by running Steam with `STEAM_LINUX_RUNTIME_LOG=1` in the environment, then launching an affected game
* [ ] `SteamLinuxRuntime_soldier/VERSIONS.txt`

As a minimum we'll need to see these for the default branch of `Steam Linux Runtime - soldier`, where the game launch is failing. I think you will find that `VERSIONS.txt` currently says `depot 0.20210630.17`, `pressure-vessel 0.20210630.0` and `soldier 0.20210629.0`.

It would also be useful if you can exit from Steam, re-launch Steam, and collect them again for the `previous_release` branch, so we can compare. I think you will find that `VERSIONS.txt` says `pressure-vessel 0.20210415.0+srt1` and `soldier 0.20210415.0`.

**Comment by baracoder** [comment] 2021-07-21 19:00
@smcv you are right, I have bodged the gist update. Sorry for the bad quality bug report and thank you for the time posting the relevant points from the docs. I have updated the description.

**Comment by smcv** [comment] 2021-07-21 19:15
From a first look, I think the root cause might be to do with this, which only appears in the new log and not in the old log:

```
20:31:55.283933: pressure-vessel-wrap[743753]: W: "/nix/store/wvgyhnd3rn6dhxzbr5r71gx2q9mhgshj-glibc-2.32-48/lib/ld-2.32.so" is unlikely to appear in "/run/host"
```

I think this means we've lost one of the special cases that we had to implement for NixOS: we should not be rewriting paths that start with `/nix/store/...` to be `/run/host/nix/store/...`, but I think we might now be doing that as a side-effect of some other change?

**Comment by smcv** [comment] 2021-07-21 20:03
Please could you try using the `previous_release`, and running Steam with `PRESSURE_VESSEL_COPY_RUNTIME=1` in the environment? You should find that a directory is generated under `SteamLinuxRuntime_soldier/var/` every time you try to run a Proton game.

If my current theory is correct, then this will *fail*, in basically the same way the default branch did. If it does, then that's sort-of-good - it brings us one step closer to a solution.

If you're comfortable with running unreviewed/unreleased software, you could also try this:

* Update your backups (you have backups, right?)
* Switch back to the default branch
* Replace `SteamLinuxRuntime_soldier/pressure-vessel` with the result of unpacking https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/jobs/54054/artifacts/raw/_build/production/pressure-vessel-bin+src.tar.gz

**Comment by baracoder** [comment] 2021-07-21 21:33
Running the game with `previous_release` and in `STEAM_LINUX_RUNTIME_LOG=1 PRESSURE_VESSEL_COPY_RUNTIME=1 steam` did fail as you predicted.
https://gist.github.com/baracoder/0a99b4aa06c24b274fb282f6e0a535ea

Restarted steam with `STEAM_LINUX_RUNTIME_LOG=1 steam`, switched the runtime to default branch and replaced `SteamLinuxRuntime_soldier/pressure-vessel` and it works again :+1: 
https://gist.github.com/baracoder/cd6bcaa1aede3261fde16c9be609c944

I have also experimented with `run-in-soldier`, though this seems not the right way to run it. The logged bwrap command does not add `/run/host` to `/nix/store` paths, but the `/nix/store/*-glib*` path is missing with the default version. It is shorter in general.
https://gist.github.com/baracoder/48ba1fb4dedbacbf2104cf57e12e5ed7

**Comment by smcv** [comment] 2021-07-22 09:52
Thanks, I'll aim to get that change into the next soldier beta.

> I have also experimented with run-in-soldier, though this seems not the right way to run it.

It's a bit complicated. The entry point from Steam is `./_v2-entry-point` ([full details if you want to know](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/master/docs/steam-compat-tool-interface.md), but `./_v2-entry-point` eventually ends up running `./run-in-soldier` (possibly in the background).

`./run-in-soldier` is close enough for manual testing when you're not coming from inside Steam.

> The logged bwrap command does not add /run/host to /nix/store paths, but the /nix/store/*-glib* path is missing with the default version. It is shorter in general.

At some point I should grab the code from newer Flatpak to log these with one argument per line, instead of one very long line that's hard to compare.

For various reasons the way we start the container has changed quite a lot since 20210415 (we always do the equivalent of `PRESSURE_VESSEL_COPY_RUNTIME=1` now, which is why this stopped working on NixOS) so it isn't directly comparable. We now do less of the setup with bwrap arguments, and more of it by editing the copy of the container in `var/tmp-*` in-place.

I'll check that everything looks reasonable in your test results.

**Comment by smcv** [comment] 2021-07-22 11:29
@baracoder, would you mind trying another unofficial build? https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/jobs/54155/artifacts/raw/_build/production/pressure-vessel-bin+src.tar.gz is a revised version that should hopefully be a bit more compatible with non-FHS operating systems other than NixOS.

> I'll check that everything looks reasonable in your test results.

Yes, it looks correct. We don't need to mount `/nix/store/...` paths individually any more, because we mount all of `/nix` from the host onto `/nix` in the container, and we make `/lib/ld-linux.so.2` a symlink to `/nix/store/.../ld-2.x.so`, etc. You can't see the symlinks being created on the `bwrap` command line any more, but if you look in `SteamLinuxRuntime_soldier/var/tmp-*` you'll see the symlink in `tmp-*/lib`.

> At some point I should grab the code from newer Flatpak to log these with one argument per line, instead of one very long line that's hard to compare.

As you've already discovered, when run with either `STEAM_LINUX_RUNTIME_VERBOSE=1` or `G_MESSAGES_DEBUG=all`, pressure-vessel logs a lot of information about what it's thinking - more than just `STEAM_LINUX_RUNTIME_LOG=1` (and you can use both together, to get an extra-verbose log).

If you run with either `STEAM_LINUX_RUNTIME_VERBOSE=1` or `G_MESSAGES_DEBUG=all` and look for `/usr/bin/bwrap options before bundling`, you'll find a version of this that is easier to compare (one line per argument instead of a single very long line).

Also, if you look for `Making provider's ld.so visible in container` in the log, you'll see a bit more about the setup for `ld.so` specifically, which is what was going wrong here. It'll appear twice, once for 32-bit and once for 64-bit.

**Comment by smcv** [comment] 2021-07-22 11:50
I've opened #432 for some more minor compatibility issues from @baracoder's log, which will need more info to solve.

**Comment by smcv** [comment] 2021-07-23 11:47
@baracoder This should be fixed in SteamLinuxRuntime_soldier depot 0.20210723.18, currently available in the `client_beta` branch. Please retry?

Because you tried an unofficial pressure-vessel build, please [verify integrity](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335) to make sure your local modifications have been reverted.

I don't have a NixOS system here, but I modified a Debian test system to imitate the NixOS behaviour by making the 32-bit `ld.so` a symlink to a regular file in `/nix`, and that seems to work fine with the new beta.

The fixed version looks like this:

```
$ cat ~/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt 
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20210723.18			# Overall version number
pressure-vessel	0.20210722.0			
scripts	v0.20210722.0-0-gb142f90			# Entry point scripts, etc.
soldier	0.20210719.0	soldier	0.20210719.0	# soldier_platform_0.20210719.0/
```

**Comment by baracoder** [comment] 2021-07-23 12:00
@smcv thank you, this version works: I changed Steam Runtime - Soldier to client_beta, verified file integrity and run the free to play Soldat game.
The VERSIONS.txt file is same. Here is the log: https://gist.github.com/baracoder/b6c74b4023805fafc286dcbb8570fca5

**Comment by smcv** [comment] 2021-07-23 12:48
Great, thanks for re-testing. Let's leave this issue open for now, but we can close it when 0.20210723.18 or later goes to the default branch.

**Comment by smcv** [comment] 2021-08-09 15:46
soldier depot 0.20210723.18 (Steampipe build ID 7074429) was moved to the default branch today, so we can close this issue now.

**Closed** 2021-08-09 16:51 UTC
Labels: Pressure Vessel
