### ISSUE TITLE
Proton stops working when using certain cursor theme.

### ISSUE THREAD

**Issue by lindely** [ValveSoftware/steam-runtime#547] opened 2022-11-26 14:12 UTC
**Distribution:** Arch Linux
**Kernel:** 6.0.9
**Desktop Environment:** KDE 5.26.3
**Proton Version:** Next (7.0-5)

When launching *any* game via Proton, Steam would get stuck in the "preparing to launch" window or would say the game was running even though nothing popped up. When performing a `ps -a | grep exe`, one or two `explorer.exe <defunct>` processes would show up.

After much trial and error and checking most files in my `.config` directory, it ended up being a cursor theme I had recently installed. Changing back the cursor theme to the KDE default and logging in again fixed the issue. Enabling the cursor set again and relogging would result in the issue re-appearing. The theme causing the zombie processes is [VS Cursor 12 for Linux](https://store.kde.org/p/1829608). I can't say if the issue lies with this set specifically or if it happens with other sets as well. In any case, it results in some wine process entering a zombie state.

My most extensive tests were with Proton Next 7.0-5 but I encountered the issues as well with 6.3 and GE's custom builds.

Whereas the issue did occur with Steam games and Proton, starting a non-Steam game with wine from Lutris f.e. worked fine. Because of this, I'm reporting  the issue here and not with the Wine project.

**Comment by kisak-valve** [comment] 2022-11-26 14:20
Hello @lindely, this reads like #538. If you go into the theme's index.theme and remove `Inherits=VS12` does that workaround the issue?

**Comment by lindely** [comment] 2022-11-26 14:39
Hi @kisak-valve, you are correct. I downloaded the archive again, removed `Inhertis=VS12` from `index.theme`, placed the theme in `~/.icons` and activated it. After relogging (and rebooting for good measure) the cursors are active and games launch again via Proton.

(I was somewhat verbose because I originally installed the theme via KDE's tools and not by using `~/.icons` -- probably moot but I'd rather be too thorough than omit potentially important stuff)

I assume I can close this now, but since I'm unsure I'll let you be the judge, if you don't mind.

**Comment by smcv** [comment] 2022-11-30 12:11
This is a bug in that specific cursor theme. It seems to be a relatively widespread misunderstanding by theme authors - we've seen other cursor themes with the same problem (#538).

The `client_beta` branch of "Steam Linux Runtime - soldier" has a workaround that should avoid this problem, even if you restore the original `index.theme` with `Inherits` pointing back to itself. @lindely, please could you confirm that? It's the same as [opting in to the beta branch of a game](https://help.steampowered.com/en/faqs/view/5A86-0DF4-C59E-8C4A), but instead of going into the Properties of a game, you should find the "Steam Linux Runtime - soldier" compatibility tool in your Steam library and go into the Properties of that.

As of today, the default branch of "Steam Linux Runtime - soldier" does not yet have the workaround. This version is indicated by `depot 0.20220930.72` in `SteamLinuxRuntime_soldier/VERSIONS.txt`. The beta branch (which has the workaround) should say `depot 0.20221018.74`.

Depot 0.20221018.74 has been in beta for a while and will probably be copied to the default branch soon. After that happens, both the default branch and the beta will have the workaround (but the `previous_release` will not).

**Comment by lindely** [comment] 2022-11-30 16:53
@smcv I did as you asked and performed the following actions:

1. Add `Inherts=VS12` back to `index.theme`.
2. Relog.
3. Launch Steam, confirmed that games wouldn't launch with Proton.
4. Switched *Steam Linux Runtime - Soldier* to **client_beta**.
5. After the update I launched the game that failed in step 3 and it launched correctly.

So that confirms it :-).

**Comment by smcv** [comment] 2022-12-01 17:40
> Depot 0.20221018.74 has been in beta for a while and will probably be copied to the default branch soon. After that happens, both the default branch and the beta will have the workaround (but the previous_release will not).

This happened today. @kisak-valve, I think we can close this issue now (it's effectively a duplicate of #538).

A new beta with some unrelated fixes was also released today. @lindely, you can go back to the default branch if you want, but you're also welcome to keep using the beta if you want to get the latest changes sooner. If you see regressions, please report them as a separate issue.

**Comment by kisak-valve** [comment] 2022-12-01 17:54
Closing per the last comment.

**Closed by kisak-valve** 2022-12-01 17:54 UTC
Labels: Pressure Vessel
