### ISSUE TITLE
Games are not starting with Soldier beta 0.20210201.0

### ISSUE THREAD

**Issue by wwmm** [ValveSoftware/steam-runtime#361] opened 2021-02-02 19:07 UTC
## System Information
- GPU: rx 5700 xt sapphire pulse
- Driver/LLVM version: Mesa 21.0.0-rc4
- Kernel version: 5.10.11
- Link to full system information report as Gist: [system info](https://gist.github.com/wwmm/28380aac1076eb49b25319727c2214bc)
- Proton: 1611698283 experimental-5.13-20210126
- SteamLinuxRuntime: v0.20210114.1-0-g5a1cbb7
- pressure-vessel: 0.20210201.0+srt1 scout 0.20210201.1
- soldier: 0.20210201.0 soldier 0.20210201.0
- Desktop: Gnome 3.38.2 on Wayland
* Have you checked for system updates?: [Yes]
* Are you using the Steam Linux Runtime compatibility tool?: [No]

After updating to the latest beta released a few hours ago Atelier Ryza 2 an Cyberpunk do not initialize anymore. This is the Atelier log
[steam-1257290.log](https://github.com/ValveSoftware/steam-runtime/files/5913867/steam-1257290.log)

I did not have to time to get Cyberpunk logs yet but switching to `Soldier [previous_release]` in Steam settings solved the issue for both games.

**Comment by kisak-valve** [comment] 2021-02-02 19:14
Hello @wwmm, please allow Steam to gather the extended diagnostics information in the System Information section and update your gist. Also, please gather a Steam runtime log while reproducing the issue. There are some instructions at https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information on how to do this.

**Comment by wwmm** [comment] 2021-02-02 19:18
>please allow Steam to gather the extended diagnostics information in the System Information section

It is bigger now. I did not notice that it takes some time for it to do everything.

**Comment by wwmm** [comment] 2021-02-02 19:23
Soldier log
[slr-app1257290-s6ceab9e616206f45.log](https://github.com/ValveSoftware/steam-runtime/files/5913981/slr-app1257290-s6ceab9e616206f45.log)

**Comment by NoXPhasma** [comment] 2021-02-02 21:41
Same issue here with `client_beta` of Steam Runtime - Soldier, works fine with default branch.

Sysinfo: https://gist.github.com/NoXPhasma/a83699f5772c2293e0d4fe4ca847106c
Runtime log: [slr-app960090-s226718a6976415c9.log](https://github.com/ValveSoftware/steam-runtime/files/5914609/slr-app960090-s226718a6976415c9.log)

**Comment by TTimo** [comment] 2021-02-02 22:34
thanks for the reports - we've reverted the `client_beta` branch to match the shipping version for now

**Comment by smcv** [comment] 2021-02-03 12:48
We're having some difficulty reproducing this issue: we have a theory (there was a bug that resulted in all the Vulkan drivers and layers being duplicated, which might be triggering this), but on a system where we can see the duplication happen, test games like Life Is Strange are still launching successfully.

If you are having a problem with a particular update or configuration and can avoid it with a workaround (such as rolling back to a previous version), it would be useful if you could share the system info report and logs before *and after* applying the workaround, so we can compare them.

**Comment by smcv** [comment] 2021-02-03 12:49
If you see this message at the end of a system info report:

> The runtime information tool is preparing a report, please wait...

please wait for the rest of the report to appear before copying it.

**Comment by NoXPhasma** [comment] 2021-02-03 13:04
Full Systeminfo: https://gist.github.com/NoXPhasma/282b44d9471294994fe9ac919098ba47

**Comment by smcv** [comment] 2021-02-03 13:16
@NoXPhasma, regarding https://gist.github.com/NoXPhasma/282b44d9471294994fe9ac919098ba47:

You seem to have some serious problems with the setup of the LD_LIBRARY_PATH Steam Runtime (not the one that is used for soldier, but the one that is used for native Linux games when you do not enable the Steam Linux Runtime compatibility tool). Most of the included libraries are not being found. If you are running Steam with Arch's "native runtime" option, please be aware that Valve specifically does not support that option. Similarly, if you are using your own modified startup script to disable or change the Steam Runtime, we cannot support or debug that.

However, the scout and soldier containers seem to be working OK. Does this system info report represent an environment in which Proton games *do* run successfully, or an environment in which games *do not* run successfully?

Which game(s) did you test in this environment, with which version of Proton?

If games do not work in this environment, please can you share a matching set of system info, Steam Runtime log `slr-*.log` and Proton log `steam-*.log`, all of them from the same system configuration?

**Comment by NoXPhasma** [comment] 2021-02-03 13:20
This Systeminfo was generated with Steam-native, that's right. About the runtime container not having issues is to be expected, as the soldier beta branch is now on the state of the stable branch which I didn't had any issues ([See the comment of TTimo](https://github.com/ValveSoftware/steam-runtime/issues/361#issuecomment-772057598)).

At this point I can not test against the broken state.

**Comment by smcv** [comment] 2021-02-03 13:35
If you are confident with using Linux command-line tools, https://github.com/ValveSoftware/steam-runtime/issues/362#issuecomment-772450527 describes how you could test against the broken state (if we have the right theory about the component that had the regression).

**Comment by smcv** [comment] 2021-02-03 13:38
@NoXPhasma, it would also be useful to see a `slr-app960090-*.log` from the working environment that matches https://gist.github.com/NoXPhasma/282b44d9471294994fe9ac919098ba47, so that we can compare it with the non-working environment in https://github.com/ValveSoftware/steam-runtime/issues/361#issuecomment-772010270.

One thing I notice in https://github.com/ValveSoftware/steam-runtime/issues/361#issuecomment-772010270 is this error message:

```
22:36:49.653615: pressure-vessel-wrap[43732]: "/home/noxp/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier/files" is not a directory
```

which suggests that maybe there was nothing particularly wrong with the changes in the beta, but it didn't get unpacked successfully, and *that* is what was breaking your games?

**Comment by smcv** [comment] 2021-02-03 13:41
@wwmm, similarly, if you can get a matching set of system info, Steam Runtime log `slr-*.log` and Proton log `steam-*.log` from a version that works successfully for you (the normal/default/non-beta branch should be OK now), it would be useful for us to compare those with the non-working logs you provided earlier.

**Comment by NoXPhasma** [comment] 2021-02-03 13:54
Bloons TD 6 stable runtime:
[slr-app960090-s7b666fab477c5f72.log](https://github.com/ValveSoftware/steam-runtime/files/5918849/slr-app960090-s7b666fab477c5f72.log)
[steam-960090.log](https://github.com/ValveSoftware/steam-runtime/files/5918853/steam-960090.log)

Bloons TD 6 linked soldier package: 
[slr-app960090-s70820602ff728fdf.log](https://github.com/ValveSoftware/steam-runtime/files/5918875/slr-app960090-s70820602ff728fdf.log)
No Proton log has been created

**Comment by smcv** [comment] 2021-02-03 14:04
@NoXPhasma: Thanks, please could you also grab a new Help -> System Information report with the broken version of `pressure-vessel-bin.tar.gz` installed? The last section of that report will tell us more about exactly what's broken.

**Comment by NoXPhasma** [comment] 2021-02-03 14:06
> One thing I notice in #361 (comment) is this error message:
>
> `22:36:49.653615: pressure-vessel-wrap[43732]: "/home/noxp/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier/files" is not a directory`
>
> which suggests that maybe there was nothing particularly wrong with the changes in the beta, but it didn't get unpacked successfully, and that is what was breaking your games?

That folder didn't exists, but there is a `com.valvesoftware.SteamRuntime.Platform-amd64,i386-soldier-runtime.tar.gz` file which contains a folder called `files`. I extracted it into a new folder `soldier` so that the path exists with data. However that doesn't change anything.

[slr-app960090-s373173012db79184.log](https://github.com/ValveSoftware/steam-runtime/files/5918921/slr-app960090-s373173012db79184.log)

> @NoXPhasma: Thanks, please could you also grab a new Help -> System Information report with the broken version of pressure-vessel-bin.tar.gz installed? The last section of that report will tell us more about exactly what's broken.

https://gist.github.com/NoXPhasma/311e7e4ab204b108fa94f5a88216aaf1

**Comment by smcv** [comment] 2021-02-03 14:11
At some point (I forget exactly which version) we changed how the runtime gets unpacked so it ends up in `SteamLinuxRuntime_soldier/var/soldier/files`, so that directory not existing is now harmless. There might have been a transitional situation where it was breaking things, but it depends on precisely which versions you were using before and after upgrading.

What is meant to happen *now* is that you get something like this:

```
SteamLinuxRuntime_soldier/
SteamLinuxRuntime_soldier/var/
SteamLinuxRuntime_soldier/var/soldier_0.20210203.42/
SteamLinuxRuntime_soldier/var/soldier_0.20210203.42/files/...
SteamLinuxRuntime_soldier/var/soldier_0.20210203.42/metadata
SteamLinuxRuntime_soldier/var/soldier -> soldier_0.20210203.42
```

If you have that (with some version number) then you can safely delete `SteamLinuxRuntime_soldier/soldier`.

**Comment by NoXPhasma** [comment] 2021-02-03 14:12
Yes, those folders exist.

**Comment by smcv** [comment] 2021-02-03 14:29
> Bloons TD 6 linked soldier package:
> slr-app960090-s70820602ff728fdf.log
> No Proton log has been created

Looks like something is crashing out before we get as far as either starting the Proton log, or running the system info diagnostic tool in the container. The system info in https://github.com/ValveSoftware/steam-runtime/issues/361#issuecomment-772535955 just says `CClientJobGatherRuntimeInformation: container read output failed`, which is unhelpfully vague, and slr-app960090-s70820602ff728fdf.log doesn't have any obvious error messages.

So, I'll try this the harder way... Still with the 0.20210201.0 version of pressure-vessel in place, please change to the `SteamLinuxRuntime_soldier/` directory and run this:

```
PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info > srsi.json 2> srsi.log; echo $?
```

I'd like to see what ends up in `srsi.json` and `srsi.log`, and also any output you get. (The successful result is that the output is just `0`, but I think you might get something different.)

**Comment by NoXPhasma** [comment] 2021-02-03 14:35
Exit code was 0
[srsi.json.txt](https://github.com/ValveSoftware/steam-runtime/files/5919121/srsi.json.txt) (json files are not allowed by github)
[srsi.log](https://github.com/ValveSoftware/steam-runtime/files/5919126/srsi.log)

**Comment by smcv** [comment] 2021-02-03 14:49
Hmm. This means when we run the diagnostic tool in the container, it's working fine; but when *Steam* runs the diagnostic tool in the container, it's failing (that's what `CClientJobGatherRuntimeInformation: container read output failed` means).

Please could you try getting `Help -> System Information`, still with the 0.20210201.0 version of pressure-vessel-bin.tar.gz in place, but this time starting Steam using the normal Steam Runtime instead of the "native runtime"? You will need to exit from Steam completely, and reopen it.

**Comment by NoXPhasma** [comment] 2021-02-03 14:53
https://gist.github.com/NoXPhasma/17a79029eb0c02ec2179fd58e500d3e5

I've also tried to run a game with the runtime in use and it still fails in the same way.

**Comment by smcv** [comment] 2021-02-03 15:03
OK, we're making progress! With the normal Steam Runtime, games still fail, but now I have some diagnostic info to look at.

My conclusion so far is that the Arch Linux "native runtime" continues to do damage (but I didn't know it could reach far enough to break the container runtime).

It looks as though, inside the container, you have working 32-bit Vulkan, but 64-bit Vulkan is failing with a timeout. This is interesting, because when you ran the diagnostic tool in the soldier container but completely outside Steam, both worked fine.

`libstrangle_vk.so` is getting onto the search path more than once (once with just its filename and once with each architecture's full filename). I wonder whether that's part of what's breaking things.

The Steam fossilize and overlay Vulkan layers are also getting duplicated, which might be caused by the change in pressure-vessel that we were suspicious about. However, when you ran the diagnostic tool in the soldier container but completely outside Steam, these layers were still duplicated but it apparently didn't break anything.

**Comment by smcv** [comment] 2021-02-03 16:17
> `libstrangle_vk.so` is getting onto the search path more than once

It looks as though this is because you have more than one manifest for it: `/usr/share/vulkan/implicit_layer.d/libstrangle_vk.json` and `/home/noxp/.local/share/vulkan/implicit_layer.d/libstrangle_vk.json`. I would recommend only having one of those.

**Comment by smcv** [comment] 2021-02-03 16:19
The Steam layers getting duplicated does seem to be a bug in the pressure-vessel update, as we suspected.

If you don't mind trying a prerelease version, you could replace `pressure-vessel/` with the result of unpacking this: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/jobs/28008/artifacts/raw/_build/scout/pressure-vessel-0.20210201.0.2-2734-bin.tar.gz (you'll need to rename the unpacked directory from `pressure-vessel-0.20210201.0.2-2734` to just `pressure-vessel`).

**Comment by NoXPhasma** [comment] 2021-02-03 16:24
It looks as though this is because you have more than one manifest for it: /usr/share/vulkan/implicit_layer.d/libstrangle_vk.json and /home/noxp/.local/share/vulkan/implicit_layer.d/libstrangle_vk.json. I would recommend only having one of those.

Ahh, good catch. Removed it from home. It still would cause the issue.

But I downloaded the new package and now it the game started fine. Looks like you've found the issue :)
[slr-app960090-s20d0ef51cf33d320.log](https://github.com/ValveSoftware/steam-runtime/files/5919930/slr-app960090-s20d0ef51cf33d320.log)

**Comment by smcv** [comment] 2021-02-03 16:29
Thanks for confirming! I'll turn the handle for a new release.

**Comment by wwmm** [comment] 2021-02-03 17:42
>@wwmm, similarly, if you can get a matching set of system info, Steam Runtime log slr-*.log and Proton log steam-*.log from a version that works successfully for you (the normal/default/non-beta branch should be OK now), it would be useful for us to compare those with the non-working logs you provided earlier.

These are the the logs and system information with the current Steam Runtime Beta:

system info https://gist.github.com/wwmm/28380aac1076eb49b25319727c2214bc
[steam-1257290.zip](https://github.com/ValveSoftware/steam-runtime/files/5920400/steam-1257290.zip)
[slr-app1257290-s867acfda070532ef.log](https://github.com/ValveSoftware/steam-runtime/files/5920417/slr-app1257290-s867acfda070532ef.log)

Everything is fine ins this configuration.

**Comment by TTimo** [comment] 2021-02-03 21:43
the `client_beta` branch was updated to `0.20210203.0` - we think the bug that caused this issue in the previous beta that we pulled out has been addressed.

**Comment by wwmm** [comment] 2021-02-03 22:27
>the client_beta branch was updated to 0.20210203.0

I did a quick test with Cyberpunk and Atelier Ryza 2 and now they are opening. As far as I can see the problem is fixed.

**Comment by smcv** [comment] 2021-02-04 12:02
OK, thanks!

@kisak-valve, I think we can close this issue already: it was a regression in the beta (which never affected the stable release), and @wwmm confirms that the updated beta has fixed it.

**Comment by NoXPhasma** [comment] 2021-02-04 12:39
I can confirm that the `client_beta` works again after the last patch.

**Comment by kisak-valve** [comment] 2021-02-04 13:36
Thanks, closing.

**Closed by kisak-valve** 2021-02-04 13:36 UTC
Labels: Need Retest, Pressure Vessel
