### ISSUE TITLE
ALSA only - No audio with Touhou Luna Nights (851100)

### ISSUE THREAD

**Issue by MunyuShizumi** [ValveSoftware/steam-runtime#400] opened 2021-04-19 20:04 UTC
# Compatibility Report
- Name of the game with compatibility issues: **Touhou Luna Nights**
- Steam AppID of the game: **851100**

## System Information
- GPU: **GTX 1070 (laptop)**
- Driver/LLVM version: **nvidia 465.24.02-3, llvm-libs 11.1.0-1**
- Kernel version: **linux 5.11.15-arch1-2**
- Link to full system information report as Gist: [steam-sysinfo-yosuzume-20210419](https://gist.github.com/MunyuShizumi/b334fe88bed856e5ab4cf6b8dc257d5d)
- Proton version: **5.13-6, 6.3-2, experimental-6.3-20210407b** (works with 5.0-10)

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

#### working 5.0-10
[steam-851100-proton-5.0-10b.log](https://github.com/ValveSoftware/Proton/files/6338651/steam-851100-proton-5.0-10b.log)
#### borked >=5.13-6
[steam-851100-proton-5.13-6.log](https://github.com/ValveSoftware/Proton/files/6338653/steam-851100-proton-5.13-6.log)
[steam-851100-proton-6.3-2.log](https://github.com/ValveSoftware/Proton/files/6338655/steam-851100-proton-6.3-2.log)
[steam-851100-experimental-6.3-20210407b.log](https://github.com/ValveSoftware/Proton/files/6338659/steam-851100-experimental-6.3-20210407b.log)

## Symptoms

No audio plays.

## Reproduction

Start app, press key to close config menu (not sure if it should have sound?), sound should play during dev/publisher intro video and in main menu (music + letter scrolling). Issue persists during gameplay, but the menu should be enough to reproduce/diagnose.

Tested from Proton Experimental backwards, last working version is 5.0-10 (haven't tested earlier versions). Using ALSA (no PulseAudio), up-to-date Arch Linux. Relatively fresh minimalist (re)install, so possibly missing some packages that would commonly get installed over years of usage.

**Comment by kisak-valve** [comment] 2021-04-19 20:12
Hello @MunyuShizumi, on the Proton issue tracker, we're using one issue report per unofficially supported game with Proton, and usually I'd transfer this issue report to https://github.com/ValveSoftware/Proton/issues/3137, however, it's much more likely that you've encountered a Pressure Vessel issue with the Steam Linux Runtime - Soldier container environment that is used with Proton 5.13 and newer. Let's treat this as an issue with the runtime environment until there's a stronger indication the issue is elsewhere.

Possible duplicate of #395.

**Comment by MunyuShizumi** [comment] 2021-04-19 23:56
> on the Proton issue tracker, we're using one issue report per unofficially supported game with Proton

My mistake, misunderstood the system, will keep it in mind for future reports.

> Can you opt into the Steam's beta client (if not already), then go to Steam Linux Runtime - Soldier in your Steam library and test the `client_beta` beta branch?

Indeed, Steam Runtime's `client_beta` branch resolves the issue. Apparently, I missed the last 6 months of Proton/Steam Runtime development, just now reading about all the changes since Proton 5.0.
Cheers!

**Comment by kisak-valve** [comment] 2021-04-19 23:58
Thanks for testing, closing as a duplicate of #395.

**Closed by kisak-valve** 2021-04-19 23:58 UTC
Labels: Pressure Vessel
