### ISSUE TITLE
Dota 2 fails to launch on Solus due to ld.so.conf path

### ISSUE THREAD

**Issue by Horb** [ValveSoftware/steam-runtime#510] opened 2022-05-04 19:28 UTC
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/Horb/847d6691ad42f0c855d223e48ab32ced
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Dota 2 does not launch from Steam. My current work around is to run dota2.sh manually but this doesn't setup the Steam Overlay which I need for purchases.

See attached [steam_output.txt](https://github.com/ValveSoftware/Dota-2/files/8626557/steam_output.txt) and the segfault on line 86.

#### Steps for reproducing this issue:

1. Select Dota 2 in my Steam Library.
2. Click PLAY
3. See typical Steam dialogs (Synchronizing Steam Cloud etc.), PLAY button turns to STOP.
4. Dota 2 does not launch as expected. STOP button returns to PLAY.

**Comment by Horb** [comment] 2022-06-07 20:43
I restored my run.sh and reproduced the issue.

I then replaced my pressure-vessel directory at `.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier` with the one provided above and the issue was resolved.

**Comment by JacekJagosz** [comment] 2022-06-07 23:50
I even verified Dota 2 now works just fine even with Native runtime enabled, and the Intercept Library enabled in our Linux-Steam-Integration.
Thank you so much for all the investigative work!

**Comment by smcv** [comment] 2022-06-08 08:28
> I then replaced my pressure-vessel directory at .local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier with the one provided above and the issue was resolved.

Great, we should be able to include that change in the next soldier and sniper beta releases. I'll update this issue when that has happened.

> now works just fine even with Native runtime enabled

I'm sure you know this already, but if this is the same as Arch's "native runtime" (disabling the `LD_LIBRARY_PATH` runtime and using host libraries exclusively), then this is unsupportable. Steam will continue to make changes and additions to its `LD_LIBRARY_PATH` runtime as they become necessary, and if OS distributors' "native runtimes" don't keep up with that, then Steam and games will not work.

If it brings you some sort of benefit, I would prefer it if we can find a way to get that benefit without it. The traditional `LD_LIBRARY_PATH` runtime already prefers to use host libraries in almost all cases, unless the library in the runtime is strictly newer (typically meaning libraries that we actively backport, like SDL and Vulkan-Loader) in which case using the newer version is required. The exceptions at the moment are libcurl, because of some historical ABI divergence that we're stuck with now, and a couple of 32-bit D-Bus-related libraries.

Using a "native runtime" will have little or no effect on the container runtime, which works differently anyway.

**Comment by smcv** [comment] 2022-07-21 11:17
> Fixed in today's beta releases (SteamLinuxRuntime_soldier and SteamLinuxRuntime_sniper `client_beta` branch, `VERSIONS.txt` will say `pressure-vessel 0.20220624.0` or later).
> 
> The default branch is not yet fixed; the beta will probably be copied to the default branch in a few weeks.

This change has now been promoted to the default branch.

**Comment by kisak-valve** [comment] 2022-07-21 12:09
Closing per the last comment.

**Comment by smcv** [comment] 2022-07-22 14:21
> > Fixed in today's beta releases (SteamLinuxRuntime_soldier and SteamLinuxRuntime_sniper `client_beta` branch, `VERSIONS.txt` will say `pressure-vessel 0.20220624.0` or later).
> > The default branch is not yet fixed; the beta will probably be copied to the default branch in a few weeks.
> 
> This change has now been promoted to the default branch.

Unfortunately this update had to be rolled back due to some unrelated regressions (#518, etc.) so we are back to only the `client_beta` branch having this fix. Solus users should stay on the `client_beta` branch for now.

**Comment by smcv** [comment] 2023-06-01 13:07
> > This change has now been promoted to the default branch.
> 
> Unfortunately this update had to be rolled back due to some unrelated regressions (#518, etc.) so we are back to only the `client_beta` branch having this fix. Solus users should stay on the `client_beta` branch for now.

We fixed #518, etc., so this fix made it to the default branch a while later (early August 2022, I think). Please re-test the default branch on Solus: this should now be fixed.

**Comment by kisak-valve** [comment] 2023-07-07 23:57
Closing per the last comment.

**Closed by kisak-valve** 2023-07-07 23:57 UTC
Labels: Need Retest, Pressure Vessel
