### ISSUE TITLE
Mangohud not load in Tomb Raider with Proton+Soldier

### ISSUE THREAD

**Issue by cyberconan** [ValveSoftware/steam-runtime#565] opened 2023-02-20 15:58 UTC
* Steam Runtime Version: 0.20230123.89
* Distribution (e.g. Ubuntu 18.04): ArchLinux
* Link to your full system information: https://gist.github.com/cyberconan/e46774fe1f0ed9cba25d499b5a3e54ba
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime + Proton Experimental
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`? https://gist.github.com/cyberconan/0b0d30583d9daff35bc8ded896e7ed58

#### Please describe your issue in as much detail as possible:
Mangohud stop working with Tomb Raider in last Runtime Soldier Version.

#### Steps for reproducing this issue:
1. Set Tomb Raider with Proton Experimental (or other version)
2. Set launch parameters: mangohud %command% -nolauncher
3. Run the game, mangohud not appear.

Log: https://gist.github.com/cyberconan/45b31234c7aede408fc7204426a429b3

Downgrading to Soldier Previous_Release fix the problem by the moment:
Log: https://gist.github.com/cyberconan/758340f047582f68d2c380f499a8396c

**Comment by kisak-valve** [comment] 2023-02-20 16:09
Hello @cyberconan, it looks like the windows variant of Tomb Raider (203160) is 32 bit, making this issue report a duplicate of #564. Closing in favor of the older issue report.

**Closed by kisak-valve** 2023-02-20 16:09 UTC
Labels: Pressure Vessel
