### ISSUE TITLE
Cannot load Proton for non-Steam games (libdl.so.2: wrong ELF class)

### ISSUE THREAD

**Issue by 64-Tesseract** [ValveSoftware/steam-runtime#589] opened 2023-05-16 05:00 UTC
I'm running Void Linux, and until recently when I updated a few packages, I could run games under Proton just fine. Then, ~~all of my~~ *only my non-Steam* Windows games suddenly stopped working, crashing after a second without displaying any windows. This happens with all versions of Proton I have installed, from versions 5 to 8.  
~~I figured out I can run most of them with another Wine prefix manager, but they don't link to Steam meaning I can't play multiplayer through Steam's network, so I still need to get this working...~~ *Strangely, only non-Steam games are affected. Crisis averted, but I'd still like to fix this so I don't have to rely on 5 launchers.*

[Here's my Steam system information btw](https://gist.github.com/64-Tesseract/af1be8593117e92381c770a61cf01c78)

To investigate, I tried running a game with `protontricks`, revealing these errors:
```
pressure-vessel-wrap[10414]: W: libsystemd.so.0: cannot open shared object file: No such file or directory
pressure-vessel-wrap[10414]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.
/usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb: error while loading shared libraries: libdl.so.2: wrong ELF class: ELFCLASS32
```

`readelf -h /lib/libdl.so.2` shows that it is actually a 64 bit library, and `/lib32/libdl.so.2` is appropriately 32 bit. I tried copying both of them to `~/.local/Steam/ubuntu12_*` (one at a time), but they both gave me the same error, so I have no clue where Steam's loading libraries from.

I also tried passing `LD_LIBRARY_PATH='/lib'` to `protontricks` and as a launch option in Steam, but it didn't change anything.

I noticed in Steam's system information that `libdl` was referencing `dl-linux.so.2`. That was actually a 32 bit library, so as a last-ditch attempt I moved it and symlinked it to `ld_linux-x86_64.so.2` instead. It didn't make my system unbootable like renaming `libdl.so.2` did, though I got this error from `protontricks` instead of "`wrong ELF class`":
```
/usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```
I wasn't sure if that different error counted as progress, so I put it back to how it was.

I don't even know what the root problem is, or what update broke it. `libdl` and `dl-linux` are `glibc` libraries, so I can't mess around with them _too_ much. I thought maybe the 32 bit version overwrote a library in the 64 bit version, so I reinstalled each of them in turn, but I think `xbps` is smart enough to not have different packages overwrite each other. I'm out of ideas, can anyone help? Cheers

**Comment by kisak-valve** [comment] 2023-05-16 12:33
Hello @64-Tesseract, Proton 5.13 and newer are run inside Steam Linux Runtime container environments, and Pressure Vessel is what sets up that environment. This reads like a runtime issue instead of a Proton issue, so I've transferred this issue report to the steam-runtime issue tracker.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information.

**Comment by smcv** [comment] 2023-05-18 14:52
Yes, we will probably need a detailed log from the Steam Linux Runtime to be able to debug this. For a low-level issue like this one, please use both `STEAM_LINUX_RUNTIME_VERBOSE=1` and `STEAM_LINUX_RUNTIME_LOG=1`.

Ideally, please make things as simple as possible for others to reproduce, with a minimum of complexity. A good starting point is to skip the extra complexity of Proton, and instead choose a small native Linux game that is known to work well ([Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) is one that I often use for this purpose: it's free to download, small and has minimal requirements). Set its launch options to force use of the `Steam Linux Runtime` compatibility tool, and try to launch that. If that fails in a similar way, capture a log and provide it here.

If you cannot reproduce this with a native Linux game, please say so, and then the next step is to try a small Windows game under Proton. Changing the properties of a small game like Floating Point to force it to run under Proton 5.13 or later is one easy way to get that: Steam will re-download it, this time as the Windows version.

> I'm running Void Linux

Is there anything unusual about this distribution when compared with typical Arch, Fedora, Ubuntu etc. that we should know about? (Not using glibc? Not using FHS library paths? Not using systemd? ...)

> To investigate, I tried running a game with `protontricks`

Protontricks is not a supported Valve product, and things that report an error when running `protontricks` do not necessarily reflect what will happen with an ordinary game.

> I tried copying both of them to `~/.local/Steam/ubuntu12_*`

Modifying the contents of Steam's internal files is not a supported thing to do, and the libraries in these directories are for Steam itself, not for games. Please revert this attempted workaround before debugging further.

> I also tried passing `LD_LIBRARY_PATH='/lib'`

This is not beneficial or necessary.

> I noticed in Steam's system information that libdl was referencing dl-linux.so.2

The Steam system information has separate sections for 32-bit code (it's labelled `i386-linux-gnu` following the convention used in GNU and Debian) and for 64-bit code (`x86_64-linux-gnu`). Older games are released as 32-bit, newer games usually as 64-bit, and parts of Steam itself use both word sizes, so we need to be able to run both, and therefore we show diagnostic information for both.

It is correct for the 32-bit part to refer to `/lib/ld-linux.so.2`, and it is correct for the 64-bit part to refer to `/lib64/ld-linux-x86-64.so.2`.

> `dl-linux.so.2`, `ld_linux-x86_64.so.2`

It's normally `/lib/ld-linux.so.2` and `/lib64/ld-linux-x86-64.so.2`. Please copy/paste machine-readable names instead of retyping them, especially if you are not completely sure what they are - precision matters when dealing with this sort of technical detail.

> as a last-ditch attempt I moved it and symlinked it to ld_linux-x86_64.so.2 instead

Please don't make modifications to your operating system if you don't understand their implications...

> didn't make my system unbootable like renaming libdl.so.2 did

... otherwise this sort of thing will happen :-)

**Comment by smcv** [comment] 2023-05-18 15:11
According to the system info that you provided, the container runtime framework is working OK: Steam was able to run some diagnostic programs inside the container, which were responsible for providing about 60% of the output that you saw.

I think the real problem here must be either something Proton-specific, or something different between the way Steam runs the diagnostic tools for system info and the way it runs the actual games. As I said in my previous comment, the best way to narrow this down would be to try a native Linux game in the Steam Linux Runtime container first, and then move on to a Proton game, only if the native Linux game works.

You can combine the container runtime's `STEAM_LINUX_RUNTIME_VERBOSE=1 STEAM_LINUX_RUNTIME_LOG=1`  with Proton's `PROTON_LOG=1` to get logs from both at the same time, which might be helpful in a situation like this where it's not immediately clear whether this is a container runtime issue or a Proton issue.

> /usr/lib/pressure-vessel/from-host/bin/pressure-vessel-adverb: error while loading shared libraries: libdl.so.2: wrong ELF class: ELFCLASS32

This is weird, and I would need to see a detailed log to diagnose what's happening. The same thing **did not** happen when the System Info ran diagnostic tools inside the container: if it had, then we would not have got far enough for you to see most of the diagnostic output that you attached.

The diagnostic tools' output looks normal for a system with the Arch-Linux-style multilib layout (64-bit in `/usr/lib`, 32-bit in `/usr/lib32`), and the diagnostic tools inside the container were able to see both 32-bit and 64-bit `libdl.so.2`. So that's fine.

However, for whatever reason, when you ran `protontricks`, only the 32-bit `libdl.so.2` was visible in the container, leading to this error. I would need to see a detailed log to say why.

**Comment by 64-Tesseract** [comment] 2023-05-18 17:21
Hey, thanks for the in-depth replies.

> Is there anything unusual about this distribution

Void uses `glibc` (at least the version I've installed), but `systemd` has been replaced with Void's own `runit`. Apart from that, `/bin` and the `/lib` folders are actually symlinks to their counterparts in `/usr`, but that's not all that unusual anymore.

All native Linux games run fine, so did Floating Point. I tried running it with Proton, which also mysteriously worked... Then I realized I only tested running non-Steam apps with Proton, and assumed Steam-supported games also crashed - my bad!

However, I still find it very weird that Proton would crash just because it's not running a Steam-supported game, especially because of a shared library. I added Floating Point as a non-Steam game and when I tried running it with Proton, sure enough, it crashed.  
[Here's my log from `steamapps/common/SteamLinuxRuntime_sniper/var/slr-app0-t20230518T224604.log`](https://gist.github.com/64-Tesseract/82a8ff669386fe1e79f6761f843b957d). I set both `STEAM_LINUX_RUNTIME_LOG=1 PROTON_LOG=1`, but it didn't really give much info.

Even if all the Steam reliant games launch, I'd still like to resolve this issue, just to have all my games managed from a single launcher which has worked very well so far.

**Comment by smcv** [comment] 2023-05-18 18:41
Please use `STEAM_LINUX_RUNTIME_VERBOSE=1 STEAM_LINUX_RUNTIME_LOG=1` to get a more comprehensive log. `…VERBOSE` was missing from what you tried most recently. That results in logging "info" messages (`I:`) but not "debug" messages (`D:`), which is enough for solving some simpler problems, but I think we are going to need the debug messages as well in this case.

**Comment by smcv** [comment] 2023-05-18 18:43
> I added Floating Point as a non-Steam game and when I tried running it with Proton, sure enough, it crashed

In addition to a verbose log from running `Floating Point.exe` as a non-Steam game (which fails in this way), it would be interesting to see a similar verbose log from running it as a Steam game under Proton (which you've said will succeed), so we can compare the two.

**Comment by smcv** [comment] 2023-05-18 18:46
I don't think running non-Steam games under Proton is considered to be *entirely* a supported thing, but it worked last time I tried it. I agree that it's weird that it makes a difference, and I'm unsure why it would.

**Comment by smcv** [comment] 2023-05-18 18:51
Your partial log does tell me that this is a container runtime problem and not a Proton problem, so we don't need a Proton log.

For your information, if we had got far enough to be able to run Proton, `PROTON_LOG=1` would have sent its output to a separate log file, usually `~/steam-$APPID.log` (where the app ID for non-Steam games will either be 0 or a random placeholder); but in this case we're not getting far enough to actually run any Proton code.

**Closed** 2023-05-23 03:31 UTC
Labels: Pressure Vessel
