### ISSUE TITLE
Steam Linux Runtime doesn't work on Clear Linux

### ISSUE THREAD

**Issue by sn99** [ValveSoftware/steam-runtime#345] opened 2021-01-03 11:13 UTC
# Compatibility Report
- Name of the game with compatibility issues: Brawlhalla
- Steam AppID of the game: 291550

## System Information
- GPU: AMD Radeon RX 5600M
- Driver/LLVM version: Mesa 20.3.1/LLVM 10.0.1
- Kernel version: 5.9.16
- Link to full system information report as [Gist](https://gist.github.com/): [link](https://gist.github.com/sn99/96265534b5fd15897532cf8fe7ed9cb1)
- Proton version: 5.13-4

## I confirm:
- [ ] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

```
GameAction [AppID 291550, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
_v2-entry-point[29666]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[29666]: STEAM_COMPAT_SESSION_ID=a2f3b26b11eb5a1f
_v2-entry-point[29666]: XDG_RUNTIME_DIR=/run/user/1000
_v2-entry-point[29665]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[29665]: STEAM_COMPAT_SESSION_ID=a2f3b26b11eb5a1f
_v2-entry-point[29665]: XDG_RUNTIME_DIR=/run/user/1000
bwrap: Can't mkdir /usr/lib32/gconv: Read-only file system
ln: failed to create symbolic link '/tmp/SteamPVSockets.AJj1CD/SteamLinuxRuntime.a2f3b26b11eb5a1f/socket' -> '': No such file or directory
_v2-entry-point[29908]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[29908]: STEAM_COMPAT_SESSION_ID=a2f3b26b11eb5a1f
_v2-entry-point[29908]: XDG_RUNTIME_DIR=/run/user/1000
bwrap: Can't mkdir /usr/lib32/gconv: Read-only file system
ln: failed to create symbolic link '/tmp/SteamPVSockets.AJj1CD/SteamLinuxRuntime.a2f3b26b11eb5a1f/socket' -> '': No such file or directory
_v2-entry-point[30270]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[30270]: STEAM_COMPAT_SESSION_ID=a2f3b26b11eb5a1f
_v2-entry-point[30270]: XDG_RUNTIME_DIR=/run/user/1000
bwrap: Can't mkdir /usr/lib32/gconv: Read-only file system
ln: failed to create symbolic link '/tmp/SteamPVSockets.AJj1CD/SteamLinuxRuntime.a2f3b26b11eb5a1f/socket' -> '': No such file or directory
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 291550
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 291550
Installing breakpad exception handler for appid(steam)/version(1609483741)
assert_20210103163614_28.dmp[30348]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210103163614_28.dmp
GameAction [AppID 291550, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 291550, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 291550, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 291550, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Opted-in Controller Mask for AppId 291550: 0
Game update: AppID 291550 "", ProcID 30353, IP 0.0.0.0:0
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 291550
>>> Adding process 30353 for game ID 291550
GameAction [AppID 291550, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 30368 != 30355, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 291550, ActionID 1] : LaunchApp changed task to Completed with ""
_v2-entry-point[30355]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[30355]: STEAM_COMPAT_SESSION_ID=a2f3b26b11eb5a1f
_v2-entry-point[30355]: XDG_RUNTIME_DIR=/run/user/1000
>>> Adding process 30355 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 30363 for game ID 291550
>>> Adding process 30369 for game ID 291550
>>> Adding process 30376 for game ID 291550
>>> Adding process 30381 for game ID 291550
bwrap: Can't mkdir /usr/lib32/gconv: Read-only file system
ln: failed to create symbolic link '/tmp/SteamPVSockets.AJj1CD/SteamLinuxRuntime.a2f3b26b11eb5a1f/socket' -> '': No such file or directory
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 30527 for game ID 291550
bwrap: Can't mkdir /usr/lib32/gconv: Read-only file system
ln: failed to create symbolic link '/tmp/SteamPVSockets.AJj1CD/SteamLinuxRuntime.a2f3b26b11eb5a1f/socket' -> '': No such file or directory
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pressure-vessel-launch[30741]: Can't connect to peer socket: Could not connect: No such file or directory
Game removed: AppID 291550 "", ProcID 30353 
Uploaded AppInterfaceStats to Steam
>>> Adding process 30740 for game ID 291550
>>> Adding process 30741 for game ID 291550
Exiting app 291550
No cached sticky mapping in ActivateActionSet.assert_20210103163614_28.dmp[30348]: Finished uploading minidump (out-of-process): success = yes
assert_20210103163614_28.dmp[30348]: response: CrashID=bp-abef9ee0-865c-4c71-8ec6-ff6ef2210103
assert_20210103163614_28.dmp[30348]: file ''/tmp/dumps/assert_20210103163614_28.dmp'', upload yes: ''CrashID=bp-abef9ee0-865c-4c71-8ec6-ff6ef2210103''
```

## Symptoms 

The game does not launch in latest proton version

## Reproduction

Open steam and launch game

## Additional info

- OS : Clear Linux ([latest](https://cdn.download.clearlinux.org/releases/34130/))
- There was a problem with `/etc/ld.so.cache` so I ran `sudo ldconfig -C /etc/ld.so.cache`
- My `$PATH` already include `/usr/local/bin:/usr/local/sbin:/usr/bin`
- I am using `Steam Linux Runtime - Soldier`

**Comment by kisak-valve** [comment] 2021-01-03 12:40
Hello @sn99, starting with Proton 5.13, Proton runs inside the Steam LInux Runtime - Soldier container environment, and that's setup by Pressure Vessel. Pressure Vessel has encountered some kind of issue setting up the container.

---

Please could you show us a log of what pressure-vessel is thinking, and exactly what happens? You can do this without involving Proton (which should make things a bit simpler) like this:

```
cd /path/to/SteamLinuxRuntime_soldier
PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info --verbose 2>&1 | tee container.log
```

and then send container.log as a [gist](https://gist.github.com/). You can edit/censor the log if there's anything in it that you consider private, as long as it's obvious where it has been edited, for instance replacing your username with REDACTED.

The SteamLinuxRuntime_soldier directory will be in one of your Steam libraries. The most likely place is ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier if you haven't reconfigured the installation path.
(from https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-741037038)

**Comment by sn99** [comment] 2021-01-03 12:48
conatiner.log: [gist](https://gist.github.com/sn99/e332b019efce2dfbc945b428fa420f40)

**Comment by kisak-valve** [comment] 2021-01-03 13:02
Thanks, this might be another example of #300 / #328.

**Comment by sn99** [comment] 2021-01-03 14:16
I extracted soldier manually and replaced the files and ran:
```
~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier $ ls -ld /lib /lib32 /lib64 /usr/lib /usr/lib32 /usr/lib64 /usr/lib/gconv /usr/lib32/gconv /usr/lib64/gconv
ls: cannot access '/lib32': No such file or directory
ls: cannot access '/usr/lib/gconv': No such file or directory
lrwxrwxrwx   1 root root      7 Feb  2  2019 /lib -> usr/lib
lrwxrwxrwx   1 root root      9 Feb  2  2019 /lib64 -> usr/lib64
drwxr-xr-x  54 root root   4096 Dec 26 10:15 /usr/lib
drwxr-xr-x  19 root root  36864 Jan  3 00:37 /usr/lib32
drwxr-xr-x   2 root root  12288 Dec 17 15:20 /usr/lib32/gconv
drwxr-xr-x 158 root root 258048 Jan  3 19:25 /usr/lib64
drwxr-xr-x   2 root root  12288 Dec 17 15:20 /usr/lib64/gconv

~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier $ ls -ld soldier/files/lib32/gconv soldier/files/lib64/gconv soldier/files/lib/gconv
drwxr-xr-x 2 sn99 sn99 4096 Nov 24 20:45 soldier/files/lib32/gconv
drwxr-xr-x 2 sn99 sn99 4096 Nov 24 20:45 soldier/files/lib64/gconv
drwxr-xr-x 2 sn99 sn99 4096 Nov 24 20:45 soldier/files/lib/gconv

~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier $ ls -ld soldier/files/lib32 soldier/files/lib64 soldier/files/lib
drwxr-xr-x 21 sn99 sn99 4096 Dec  3 18:41 soldier/files/lib
drwxr-xr-x  3 sn99 sn99 4096 Dec  3 18:40 soldier/files/lib32
drwxr-xr-x  3 sn99 sn99 4096 Dec  3 18:38 soldier/files/lib64
```

The new error I get:

```
GameAction [AppID 291550, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
_v2-entry-point[4400]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[4400]: STEAM_COMPAT_SESSION_ID=43a0cc8775728e8f
_v2-entry-point[4400]: XDG_RUNTIME_DIR=/run/user/1000
_v2-entry-point[4401]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[4401]: STEAM_COMPAT_SESSION_ID=43a0cc8775728e8f
_v2-entry-point[4401]: XDG_RUNTIME_DIR=/run/user/1000
esync: up and running.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
GameAction [AppID 291550, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 291550, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 291550, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 291550, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 291550 "", ProcID 4721, IP 0.0.0.0:0
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 291550
>>> Adding process 4721 for game ID 291550
GameAction [AppID 291550, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 4724 != 4722, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
_v2-entry-point[4722]: STEAM_COMPAT_APP_ID=291550
_v2-entry-point[4722]: STEAM_COMPAT_SESSION_ID=43a0cc8775728e8f
_v2-entry-point[4722]: XDG_RUNTIME_DIR=/run/user/1000
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 291550, ActionID 2] : LaunchApp changed task to Completed with ""
>>> Adding process 4722 for game ID 291550
pid 4732 != 4722, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 4723 for game ID 291550
>>> Adding process 4725 for game ID 291550
>>> Adding process 4726 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 4727 for game ID 291550
>>> Adding process 4728 for game ID 291550
>>> Adding process 4735 for game ID 291550
>>> Adding process 4736 for game ID 291550
>>> Adding process 4737 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
esync: up and running.
>>> Adding process 4739 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 4740 for game ID 291550
>>> Adding process 4743 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 4745 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 4748 for game ID 291550
>>> Adding process 4755 for game ID 291550
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 4762 for game ID 291550
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Game update: AppID 291550 "", ProcID 4739, IP 0.0.0.0:0
RecordSteamInterfaceCreation (PID 4739): SteamUtils009 / Utils
Setting breakpad minidump AppID = 291550
RecordSteamInterfaceCreation (PID 4739): SteamUser019 / User
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198967959707 [API loaded no]
RecordSteamInterfaceCreation (PID 4739): SteamUser019 / User
RecordSteamInterfaceCreation (PID 4739): SteamFriends015 / Friends
RecordSteamInterfaceCreation (PID 4739): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 4739): SteamMatchMaking009 / Matchmaking
RecordSteamInterfaceCreation (PID 4739): SteamMatchMakingServers002 / MatchmakingServers
RecordSteamInterfaceCreation (PID 4739): STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
RecordSteamInterfaceCreation (PID 4739): STEAMAPPS_INTERFACE_VERSION008 / Apps
RecordSteamInterfaceCreation (PID 4739): SteamNetworking005 / Networking
RecordSteamInterfaceCreation (PID 4739): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
RecordSteamInterfaceCreation (PID 4739): STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
RecordSteamInterfaceCreation (PID 4739): STEAMHTTP_INTERFACE_VERSION002 / HTTP
RecordSteamInterfaceCreation (PID 4739): SteamController006 / Controller
RecordSteamInterfaceCreation (PID 4739): STEAMUGC_INTERFACE_VERSION010 / UGC
RecordSteamInterfaceCreation (PID 4739): STEAMAPPLIST_INTERFACE_VERSION001 / AppList
RecordSteamInterfaceCreation (PID 4739): STEAMMUSIC_INTERFACE_VERSION001 / Music
RecordSteamInterfaceCreation (PID 4739): STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
RecordSteamInterfaceCreation (PID 4739): STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
RecordSteamInterfaceCreation (PID 4739): STEAMINVENTORY_INTERFACE_V002 / Inventory
RecordSteamInterfaceCreation (PID 4739): STEAMVIDEO_INTERFACE_V002 / Video
RecordSteamInterfaceCreation (PID 4739): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
>>> Adding process 4769 for game ID 291550
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
ERROR: ld.so: object '/home/sn99/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 4784 for game ID 291550
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
pid 4741 != 4740, skipping destruction (fork without exec?)
Game removed: AppID 291550 "", ProcID 4739 
Game 291550 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 291550 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 291550 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
Game 291550 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 291550 created interface STEAMINVENTORY_INTERFACE_V002 / Inventory
Game 291550 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 291550 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 291550 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 291550 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Game 291550 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 291550 created interface STEAMUGC_INTERFACE_VERSION010 / UGC
Game 291550 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 291550 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 291550 created interface SteamController006 / Controller
Game 291550 created interface SteamFriends015 / Friends
Game 291550 created interface SteamMatchMaking009 / Matchmaking
Game 291550 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 291550 created interface SteamNetworking005 / Networking
Game 291550 created interface SteamUser019 / User
Game 291550 created interface SteamUtils009 / Utils
Game 291550 method call count for IClientUser::GetSteamID : 1
Game 291550 method call count for IClientUtils::GetAppID : 24
Game 291550 method call count for IClientUtils::RecordSteamInterfaceCreation : 22
Game 291550 method call count for IClientUtils::GetSteamUILanguage : 1
Uploaded AppInterfaceStats to Steam
Exiting app 291550
No cached sticky mapping in ActivateActionSet.
```
conatiner.log: [gist](https://gist.github.com/sn99/739a55c418ad76adf295a9945e0e47bf)

I have freetype Installed and even tried installing one from source following [this](https://noknow.info/it/os/install_freetype_from_source?lang=en) but get the same errors

**Comment by smcv** [comment] 2021-01-04 20:22
> Wine cannot find the FreeType font library

This looks uncomfortably as though the runtime was somehow only partially unpacked, but in a different way.

What is *meant* to happen is that it's unpacked under a different directory name, and only renamed into place after unpacking has been fully successful, so that it can never have its final name but only partially be there... but it seems there's some situation in which this can fail.

> steam-runtime-system-info: error while loading shared libraries: libgio-2.0.so.0: cannot open shared object file: No such file or directory

That would certainly be consistent with the `soldier` directory being incomplete.

Please try `find soldier | LC_ALL=C sort > contents.txt`.

Then, remove the `soldier` directory (or rename it to `broken-issue345` or something), and run the commands from https://github.com/ValveSoftware/steam-runtime/issues/345#issuecomment-753611093 again. Again, record their output. You should find that pressure-vessel startup takes longer this time, because it has to unpack a new copy of soldier - and maybe it will produce error messages that let us understand this...

Then `find soldier | LC_ALL=C sort > contents2.txt`, and show us `contents.txt` and `contents2.txt`.

Also please show us what's in `VERSIONS.txt`.

It might also be helpful to check against the included `SHA256SUMS` list: `sha256sum -c SHA256SUMS`.

**Comment by sn99** [comment] 2021-01-06 13:41
[contents.txt](https://gist.github.com/sn99/feeb82b452720922d5266c9436600cbe)
[contents2.txt](https://gist.github.com/sn99/3687d9dbf130d601eac44300ee535df7)

VERSIONS.txt
```
#Name	Version		Runtime	Runtime_Version	Comment
SteamLinuxRuntime	v0.20201124.0-11-g197f448			# Entry point scripts, etc.
pressure-vessel	0.20201203.0+srt1	scout	0.20201214.0	# pressure-vessel-bin.tar.gz
soldier	0.20201210.0	soldier	0.20201210.0	# com.valvesoftware.SteamRuntime.Platform-amd64,i386-soldier-runtime.tar.gz
```
All checksum report `OK`

**Comment by smcv** [comment] 2021-01-06 20:18
```
  "runtime" : {
    "path" : "/home/sn99/.local/share/Steam/ubuntu12_32/steam-runtime",
    "version" : "0.20201203.1",
    "issues" : [
      "not-using-newer-host-libraries"
    ],
    "pinned_libs_32" : {
      "messages" : [
        "find: ‘pinned_libs_32’: No such file or directory"
      ]
    },
    "pinned_libs_64" : {
      "messages" : [
        "find: ‘pinned_libs_64’: No such file or directory"
      ]
    }
  },
```

This seems strange. It's not *directly* related to the container runtime, but would seem to indicate that there is something odd going on, and will probably result in native Linux games being broken on this system.

**Comment by smcv** [comment] 2021-01-06 20:20
> CClientJobGatherRuntimeInformation: container read output failed

Something is not right here: `steam-runtime-system-info` is unable to start in the container.

I wonder whether this is something about Clear Linux: does it perhaps have an unusual library search path or glibc configuration?

**Comment by smcv** [comment] 2021-01-06 20:23
> There was a problem with /etc/ld.so.cache so I ran sudo ldconfig -C /etc/ld.so.cache

Ah. Does Clear Linux's `ldconfig` normally produce a different file?

If it does, then its `libc` will also expect to be reading that file, which won't exist inside our container.

**Comment by sn99** [comment] 2021-01-06 22:42
Games like Dota2 or tf2 seem to work fine.

`sudo ldconfig -v 2>/dev/null | grep -v ^$'\t'` returns :
```
/usr/local/lib:
/usr/lib:
/usr/lib64:
/usr/lib32:
/usr/lib64/haswell: (hwcap: 0x0004000000000000)
/usr/lib64/haswell/avx512_1: (hwcap: 0x0004000000000004)
```
Clear Linux does have a different files structure so to say [link](https://docs.01.org/clearlinux/latest/guides/clear/stateless.html#stateless)

I will add more when I get some more info [community discussion](https://community.clearlinux.org/t/unable-to-get-latest-version-of-proton-steam-runtime-to-work-on-clearlinux/5884)

**Comment by smcv** [comment] 2021-01-06 23:13
If you have access to `strace`, then `strace -efile true` might be a quick way to provide what I'm looking for.

> Games like Dota2 or tf2 seem to work fine.

Steam doesn't run native Linux games like these in a container unless you specifically ask for it, but when it uses Proton 5.13+ to run Windows games, that happens in a container. It's the container launcher that is having trouble here.

**Comment by sn99** [comment] 2021-01-07 01:46
```
$ strace -efile true

execve("/usr/bin/true", ["true"], 0x7ffec9130268 /* 63 vars */) = 0
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/var/cache/ldconfig/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libacl.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libattr.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libcap.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/usr/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
+++ exited with 0 +++
```

**Comment by smcv** [comment] 2021-01-07 08:38
> `/var/cache/ldconfig/ld.so.cache`

Right, we need to make this file in the container be a symlink to `/etc/ld.so.cache`.

Workaround:

```
cd /path/to/SteamLinuxRuntime_soldier
mkdir -p soldier/files/var/cache/ldconfig/
ln -s /etc/ld.so.cache soldier/files/var/cache/ldconfig/ld.so.cache
```

**Comment by smcv** [comment] 2021-01-07 09:38
This won't be game-specific, but will be OS-specific. @kisak-valve, please retitle to: "Steam Linux Runtime doesn't work on Clear Linux".

**Comment by sn99** [comment] 2021-01-07 13:40
@smcv It works now, thanks for the help, appreciate it

**Comment by smcv** [comment] 2021-01-07 14:12
That workaround is not a permanent solution, and will stop working next time SteamLinuxRuntime_soldier is updated. Please reopen this until I've landed changes in the pressure-vessel code that will make the workaround unnecessary.

**Comment by smcv** [comment] 2021-01-11 18:38
This should be fixed by the combination of https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/218 and https://gitlab.collabora.com/vivek/libcapsule/-/merge_requests/43 when they get into a release.

**Comment by sn99** [comment] 2021-01-15 04:36
There was an update of soldier had to repeat the last steps again

**Comment by smcv** [comment] 2021-01-15 09:42
Yes, as I said already, the workaround was temporary.

The new beta of SteamLinuxRuntime_soldier (look for pressure-vessel version 0.20210114.0 in VERSIONS.txt) hopefully fixes this. Please could you try it on your Clear Linux system?

Switching to the beta branch of SteamLinuxRuntime_soldier is the same as switching to the beta branch of a game. Please follow the same procedure as https://support.steampowered.com/kb_article.php?ref=9847-WHXC-7326, but in the properties of "Steam Linux Runtime - soldier" rather than CS:GO.

**Comment by sn99** [comment] 2021-01-16 03:25
It fixed it, `VERSIONS.txt` :
```
#Name	Version		Runtime	Runtime_Version	Comment
SteamLinuxRuntime	v0.20210114.1-0-g5a1cbb7			# Entry point scripts, etc.
pressure-vessel	0.20210114.0+srt1	scout	0.20210114.2	# pressure-vessel-bin.tar.gz
soldier	0.20210114.2	soldier	0.20210114.2	# com.valvesoftware.SteamRuntime.Platform-amd64,i386-soldier-runtime.tar.gz
```

The game launches without needing to do anything else.

**Comment by smcv** [comment] 2021-01-28 11:35
@kisak-valve: I think we can remove `Need Retest` from this one. It's known to be still a problem in the stable branch, but is confirmed fixed in the beta. Let's close the issue after a version >= 0.20210114 goes to stable.

Would it be worthwhile to have a `Fixed in beta` label?

**Comment by smcv** [comment] 2021-02-02 15:37
> Let's close the issue after a version >= 0.20210114 goes to stable

This has now happened.

**Closed** 2021-02-02 16:02 UTC
Labels: Need Retest, Pressure Vessel

**Comment by smcv** [comment] 2024-04-16 17:57
Today's Steam Linux Runtime 2.0 (soldier) and 3.0 (sniper) betas, versioned as 0.20240415.x, have a change that slightly improves compatibility with Clear Linux (`LD_PRELOAD` modules will log fewer warnings, and VDPAU drivers will work a little bit better).

It would be useful if a Clear Linux user or developer could try these betas before they get re-released as stable, so that we can roll back the change if it causes a regression. Would you mind trying this?

As a general principle, if you are interested in having the Steam Runtime work smoothly on your OS and you are technically proficient enough to swap between beta branches and send clear bug reports, it's actually better to use the betas than the stable releases. That way, if you encounter a new regression, you can report the bug, then drop back from beta to stable while waiting for it to be fixed, and less-technically-proficient users of your OS hopefully won't have to encounter the bug at all.
