### ISSUE TITLE
Rocket League can't reach server

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/steam-runtime#199] opened 2019-11-11 14:11 UTC
With the new runtime picker, testing it out with Rocket League it fails to connect to their servers.

System info: https://gist.github.com/LiamDawe/314ccb032a0690a1c26df805ad7f3c18

Not sure what other info you want, let me know :)

**Comment by TTimo** [comment] 2019-11-11 20:32
Hey Liam, could you update your system info to include the container runtime diagnostic? The one you included was done before the depot was installed, so it reports `The Steam Linux Runtime container tool is not installed.`

**Comment by LiamDawe** [comment] 2019-11-11 20:48
Actually, it is installed but it seems the system info doesn't detect it?

**Comment by kisak-valve** [comment] 2019-11-11 20:50
Hello @LiamDawe, you may need to restart the steam client after adding the tool because it runs in the background at startup to collect the info.

**Comment by LiamDawe** [comment] 2019-11-11 20:51
Yeah, tried that. Still says it's not installed in the system info but it is.

**Comment by TTimo** [comment] 2019-11-11 21:39
It sounds like we have some problems getting `steam-runtime-system-info` to execute and report in the container context on user systems. That's probably worth a separate issue.

**Comment by TTimo** [comment] 2019-11-11 22:00
Do you see a line like this in steam stdout:
`/home/timo/.local/share/Steam/SteamApps/common/SteamLinuxRuntimesteam-runtime-system-info`

**Comment by LiamDawe** [comment] 2019-11-11 22:02
Afraid not.

**Comment by Myrddin-Wyllt** [comment] 2019-11-14 04:16
According to system information, "The Steam Linux Runtime container tool is not installed."

![image](https://user-images.githubusercontent.com/42914865/68826330-07c37380-0663-11ea-8c2a-d327c2ea6e60.png)

**Comment by smcv** [comment] 2020-09-14 11:39
Wildly guessing from the symptoms reported, this might have been the same bug as #226. If it is, please see #226 for details of how to check whether this is fixed in the latest beta.

**Comment by LiamDawe** [comment] 2020-09-14 12:41
I no longer own it to test, refunded after they removed Linux support. Someone else will need to confirm and close.

**Comment by smcv** [comment] 2020-09-23 17:30
Rocket League is no longer on Steam so nobody can test this any more, and we *think* we fixed the root cause anyway (#226), so there's probably no point in this issue staying open.

**Closed** 2020-09-23 17:31 UTC
Labels: Need Retest, Pressure Vessel
