### ISSUE TITLE
Issues with mounting an extra directory 

### ISSUE THREAD

**Issue by matheusfillipe** [ValveSoftware/steam-runtime#308] opened 2020-12-04 03:25 UTC
#### Your system information

* Steam Runtime Version: 5.13.2
* Distribution (e.g. Ubuntu 18.04): OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes

#### Please describe your issue in as much detail as possible:
I am trying to play MSFS2020 and install it on a different device on my system. I tried to mount my separate driver using `STEAM_COMPAT_MOUNTS` but coudn't get it to work at all. I tried all those ways:

`STEAM_COMPAT_MOUNTS=/media/matheus/DATA/MS20/ `
`STEAM_COMPAT_MOUNTS="/media/matheus/DATA/MS20/"`
`STEAM_COMPAT_MOUNTS=/media/matheus/DATA/MS20/:`
`STEAM_COMPAT_MOUNTS="/media/matheus/DATA/MS20/:"`
`STEAM_COMPAT_MOUNTS=:/media/matheus/DATA/MS20/:`

None worked. My launch opts line is like:

`PROTON_LOG=1 STEAM_COMPAT_MOUNTS=/media/matheus/DATA/MS20/ %command% -FastLaunch`

Where i replaced the STEAM_COMPAT part with all of those other parts above. 
![image](https://user-images.githubusercontent.com/24435787/101114703-c9c42500-35c0-11eb-8653-441504a7bd4d.png)

Should it show up as a device? All of them are empty except by C and Z:

![image](https://user-images.githubusercontent.com/24435787/101114774-e9f3e400-35c0-11eb-9455-4150c56997c3.png)

So am I doing something wrong here, could it be a problem related to the game or should I fill a new issue for this?

**Comment by smcv** [comment] 2020-12-04 12:00
Many of the environment variables that influence pressure-vessel's behaviour won't currently work in an individual Proton game's launch options, because by the time Steam gets as far as processing the launch options, it's too late - we already had to start the container to be able to run setup commands. See #304 (this is essentially the same problem).

Until this is resolved, you'll have to set those environment variables globally for the entire Steam client, for example by running it like this:

```
STEAM_COMPAT_MOUNTS=/media/matheus/DATA/MS20 steam
```

We might be able to solve this in a future release by shutting down the container after the setup commands have run, and starting a new container that takes the launch options into account. I had been concerned that this would add too much time to container startup, but it looks as though it might only add a couple of seconds in practice.

Alternatively, you can work around this by bind-mounting the `MS20` directory inside your home directory.

> Should it show up as a device?

No, the `STEAM_COMPAT_MOUNTS` are currently only used by pressure-vessel, not by Proton. If you add extra mount points they will show up under `Z:`, like the path you were trying in your screenshots.

**Comment by matheusfillipe** [comment] 2020-12-04 22:27
`STEAM_COMPAT_MOUNTS=/media/matheus/DATA/MS20 steam` made it work indeed!

**Comment by smcv** [comment] 2020-12-15 18:03
> We might be able to solve this in a future release by shutting down the container after the setup commands have run, and starting a new container that takes the launch options into account. I had been concerned that this would add too much time to container startup, but it looks as though it might only add a couple of seconds in practice.

In the latest beta version of `SteamLinuxRuntime_soldier`, you can try this out by running Steam with `PRESSURE_VESSEL_RELAUNCH_CONTAINER=1` in the environment. It will make container startup slower, but it will mean that "adverb" commands in the launch options get taken into account, and so will environment variables like `STEAM_COMPAT_MOUNTS` that affect container startup (which will get applied to the actual game, but not the setup commands). Please let me know how well it works for you!

For this feature, you want `VERSIONS.txt` to say `SteamLinuxRuntime v0.20201124.0-11-g197f448` or higher.

Depending how well it works in terms of performance and functionality, we might make this mandatory in a later version, or keep it opt-in, or drop it entirely. It might even become enabled by default with an opt-out, but probably not for very long, because if it's good enough to be on by default, making it mandatory would let us delete quite a lot of relatively complex code.

**Comment by kisak-valve** [comment] 2021-01-15 15:05
With the current Steam Linux Runtime - Soldier beta build, using `STEAM_COMPAT_MOUNTS` should work with the per-game launch options and no other workarounds. I think we're done here.

**Comment by smcv** [comment] 2021-01-15 15:20
Yes, I think so. In the latest beta, you get the `PRESSURE_VESSEL_RELAUNCH_CONTAINER=1` behaviour by default: the container is shut down after running the setup commands, and then relaunched (taking the Launch Options into account) to run the actual game.

At the moment there is still an opt-out to go back to the old way (`PRESSURE_VESSEL_RELAUNCH_CONTAINER=0`), but we'll remove that in a future release unless important regressions are reported.

**Comment by kisak-valve** [comment] 2021-01-15 15:26
Thanks @smcv, closing.

**Closed by kisak-valve** 2021-01-15 15:26 UTC
Labels: Need Retest, Pressure Vessel
