### ISSUE TITLE
steam exits without error on arch with nvidia

### ISSUE THREAD

**Issue by emlos** [ValveSoftware/steam-runtime#686] opened 2024-07-29 16:21 UTC
#### Your system information

* Steam Runtime Version: 1.0.0.79-2
* Distribution (e.g. Ubuntu 18.04): Arch Linux 6.10.2-arch1-1 x86_64
* Link to your full system information (Help -> Steam Runtime Diagnostics) in a [Gist](https://gist.github.com/): I can't start steam.
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: None, Steam does not start
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? I don't have this folder
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`? I don't have this folder
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`? I don't have this folder

#### Please describe your issue in as much detail as possible:
I have a fresh install of Arch.
When I start steam runtime OR steam-native it exits without any obvious error. I have a "NVIDIA Corporation GA104M [GeForce RTX 3070 Mobile / Max-Q]" Graphics card. I tried to follow the Steam install guide on the arch wiki, but I'm not that well versed with drivers.

This is the error:
```
steam.sh[215309]: Running Steam on arch rolling 64-bit
steam.sh[215309]: STEAM_RUNTIME is enabled automatically
setup.sh[215382]: Steam runtime environment up-to-date!
/home/milo/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[215395]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[215309]: Can't find 'steam-runtime-check-requirements', continuing anyway
tid(215426) burning pthread_key_t == 0 so we never use it
```

I also tried to check what (if any) libraries I am missing, using [this](https://wiki.archlinux.org/title/Steam/Troubleshooting#Debugging_shared_libraries) troubleshooting guide on the wiki.
```
 cd ~/.steam/root/ubuntu12_32
 file * | grep ELF | cut -d: -f1 | LD_LIBRARY_PATH=. xargs ldd | grep 'not found' | sort | uniq
```
This returns nothing. The other command `for i in $(pgrep steam); do sed '/\.local/!d;s/.*  //g' /proc/$i/maps; done | sort | uniq` returns 
```
/home/milo/.local/share/Steam/ubuntu12_32/crashhandler.so
/home/milo/.local/share/Steam/ubuntu12_32/steam
```
but are those missing libraries?

Launching it with the reset flag (`steam-runtime --reset`) also doesn't change the output, it's the same as above.

#### Steps for reproducing this issue:

1. I installed my Nvidia drivers according to [this](https://github.com/korvahannu/arch-nvidia-drivers-installation-guide) guide, and they seem to work so far. I installed those three packages: `nvidia-390xx-dkms`, `nvidia-390xx-utils`, `lib32-nvidia-390xx-utils`.
2. My locale should be all correct:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
3. I enabled multilib and ran `yay -Syu`
4. I ran `pacman -S steam`, the installation worked, but when I start steam it results in the above message and it just exits. 
5. I installed the steam-native-runtime too, and the error i get on running `steam-native` is slightly truncated:
```
steam.sh[216559]: Running Steam on arch rolling 64-bit
steam.sh[216559]: STEAM_RUNTIME is disabled by the user
steam.sh[216559]: Can't find 'steam-runtime-check-requirements', continuing anyway
tid(216642) burning pthread_key_t == 0 so we never use it
```
I googled and googled, and from my understanding I either have some sort of a wrong driver situation, or some sort of libraries are missing. Either way I don't know what to do.

**Comment by kisak-valve** [comment] 2024-07-29 17:11
Hello @emlos, the NVIDIA 390 driver is grossly outdated for your hardware generation. You should prefer to use the current up to date video driver release and there's some complications from the legacy driver which is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/10980 and #420.

Please update your video driver.

Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/10980.

**Closed by kisak-valve** 2024-07-29 17:11 UTC
