### ISSUE TITLE
Proton 5.13 fails to locate Steam's process

### ISSUE THREAD

**Issue by literal-0x4e** [ValveSoftware/steam-runtime#293] opened 2020-10-31 16:10 UTC
Any and all games or tools I attempt to run with specifically Proton version 5.13 seem to fail to reach the point where the game/tool would be executed at all, as Proton fails with this error before that happens:
```
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
```
Meanwhile, using an older Proton version works "normally".
[system information as provided by Steam](https://gist.github.com/literal-0x4e/2112b3fc482ab4817cadf0f0ab976d15) (although it looks like steam messed up and gave some incorrect information about the processor, but that shouldn't be a problem per se)
Note: this steam installation together in all the games are run from an LXD container.

**Comment by kisak-valve** [comment] 2020-10-31 16:25
Hello @literal-0x4e, let's treat this as a Pressure Vessel issue until there's a stronger indicator that the issue is elsewhere. If you completely close Steam, then run Steam from a terminal, does the terminal spew give any hints?

Possibly related to https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/35.

**Comment by literal-0x4e** [comment] 2020-10-31 17:28
> Hello @literal-0x4e, let's treat this as a Pressure Vessel issue until there's a stronger indicator that the issue is elsewhere. If you completely close Steam, then run Steam from a terminal, does the terminal spew give any hints?

This _is_ the terminal spew I see. (I always run steam from a terminal, just in case)
After the suggestion this is probably a bug in Pressure Vessel, I ran various games with `PRESSURE_VESSEL_VERBOSE=1 `, but I could not see absolutely anything at all suspicious in the output.

> Possibly related to https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/35.

I also tried running some native games with steam runtime forced as described in the aforementioned bug report and depending on the game I then either again get the very same
```
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
```
**OR** a slightly different
```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
```
which then makes those native games misbehave in a variety of ways. Nothing at all suspicious in Pressure Vessel verbose output when forcing it on native games, either.

But yes, overall appears to be a Pressure Vessel bug after all.

**Comment by literal-0x4e** [comment] 2020-10-31 17:46
Oh, it appears this is a duplicate of bug #291

I in fact did a thorough search of the error message before filing this report, but due to multitude of distractions, I took me whole three days to type out the actual report, so I missed #291, as it was filed a little bit later than I started typing mine.
Sorry about that.

**Comment by kisak-valve** [comment] 2020-10-31 17:49
Closing per the last comment.

**Closed by kisak-valve** 2020-10-31 17:49 UTC
Labels: Pressure Vessel
