### ISSUE TITLE
gnutls (libcurl_gnutls) expects /etc/ssl/certs/ca-certificates.crt

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#172] opened 2019-05-18 21:49 UTC

**Comment by sylware** [comment] 2019-05-18 21:55
yoyo gamemaker games are sending system information to their servers using a TLS connection using the steam runtime libcurl_gnutls. If /etc/ssl/certs/ca-certificates.crt does not exist, you get an early crash. The steam runtime should rely on its own ca certificate files. Some distros do not use /etc/ssl/certs/ca-certificates.crt anymore (for instance mozilla /etc/ssl/certs/cacert.pem) or their ca certificates files could be elsewhere.

**Comment by kisak-valve** [comment] 2019-05-18 22:08
Duplicate of #52.

**Closed by kisak-valve** 2019-05-18 22:08 UTC
