### ISSUE TITLE
The latest update of linux runtime 3.0 (sniper) always crash The Elder Scrolls Online

### ISSUE THREAD

**Issue by lumingzh** [ValveSoftware/steam-runtime#624] opened 2023-10-03 00:47 UTC
#### Your system information

* Steam Runtime Version: 3.0
* Distribution (e.g. Ubuntu 18.04): Fedora Silverblue 38
* Have you checked for system updates?: [Yes]
* What compatibility tool are you using?: [Steam Linux Runtime 3.0/ Proton experimental]
* What versions are listed in `steamapps/common/SteamLinuxRuntime/VERSIONS.txt`? don't have that
* What versions are listed in `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt`? 0.20230921.60881
* What versions are listed in `steamapps/common/SteamLinuxRuntime_sniper/VERSIONS.txt`? 0.20230919.60634

#### Please describe your issue in as much detail as possible:

The latest update of linux runtime 3.0(sniper) (update date is about 10/02 or 10/03) always crash ESO, switch to proton 7.0 + runtime 2.0 (soldier) can play again.
#### Steps for reproducing this issue:

1. using proton experimental + steam linux runtime 3.0 (sniper) for ESO
2. start ESO and click play button on game launcher
3. crash with black screen (sometimes can show crash report dialog)

**Comment by kisak-valve** [comment] 2023-10-03 00:55
Hello @lumingzh, please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information.

Using a completely different Steam runtime as a reference point for a regression isn't particularly useful for troubleshooting a regression. Can you go to `Steam Linux Runtime 3.0 (sniper)` in your Steam library -> per-game properties -> Betas -> switch the Beta participation dropdown to `previous_release` and test how the game behaves with the same Proton version as the regression you're seeing?

**Comment by lumingzh** [comment] 2023-10-03 04:15
@kisak-valve Yes, set as you said using `previous_release` in beta page with proton experimental and works normally now.

It has nothing to do with proton.

**Comment by lumingzh** [comment] 2023-10-03 12:54
@smcv @kisak-valve 
- system info: [share link](https://gist.github.com/lumingzh/218b1515efe301d246a2996b1929f27b)
- good version: `0.20230905.59202`
  runtime log: [slr-app306130-t20231003T201321.log](https://github.com/ValveSoftware/steam-runtime/files/12792318/slr-app306130-t20231003T201321.log)
  proton log: too big to upload (283 MB)
- bad version: `0.20230919.60634`
  runtime log: [slr-app306130-t20231003T202923.log](https://github.com/ValveSoftware/steam-runtime/files/12792442/slr-app306130-t20231003T202923.log)
  proton log: too big to upload
- client_beta version: `0.20231002.61997` (crash as well)
  runtime log: [slr-app306130-t20231003T203828.log](https://github.com/ValveSoftware/steam-runtime/files/12792507/slr-app306130-t20231003T203828.log)
  proton log: too big to upload

**Comment by smcv** [comment] 2023-10-03 13:15
> proton log: too big to upload

Please could you get another log for the bad case (0.20230919.60634 or 0.20231002.61997), this time *without* `PROTON_LOG=1`? This should leave some information about the crash near the end of `slr-latest.log`.

**Comment by smcv** [comment] 2023-10-03 14:33
OK, this is probably an unintended consequence of the Flatpak-related bug fixes in pressure-vessel 0.20230919.0. I'll see whether I can reproduce this with some other 64-bit game (I don't currently have access to ESO).

**Comment by smcv** [comment] 2023-10-04 20:08
@lumingzh, if you're comfortable with using prerelease software, you could try setting `PRESSURE_VESSEL_PREFIX` to point to the result of unpacking this: https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/jobs/334317/artifacts/raw/_build/production/pressure-vessel-bin.tar.gz

(from https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/merge_requests/595)

I'm hoping that will fix the crash you're seeing with ESO by avoiding the duplication.

After more testing/review this change should be available in a future beta release.

**Comment by smcv** [comment] 2023-10-06 09:29
This should now be fixed in the soldier and sniper `client_beta` branches, versioned 0.20231005.x (VERSIONS.txt should say that they have `pressure-vessel 0.20230928.1`).

**Comment by lumingzh** [comment] 2023-10-10 11:13
@smcv Sorry for my late reply. The `client_beta` branch works normally now, thank you. 
Should I close this issue now or after the `client_beta` branch released as stable branch?

**Comment by smcv** [comment] 2023-10-10 11:32
Please leave this open, @kisak-valve will close it after the beta is released as stable. Thanks for re-testing!

**Comment by kisak-valve** [comment] 2023-11-10 20:33
Closing as fixed in the [2023-10-25](https://store.steampowered.com/news/app/593110/view/3723973446147960643) Steam client update. It looks like the relevant change actually went to the stable release on 2023-10-18.

**Closed by kisak-valve** 2023-11-10 20:33 UTC
Labels: Need Retest, Pressure Vessel

**Comment by smcv** [comment] 2023-11-11 16:53
> It looks like the relevant change actually went to the stable release on 2023-10-18

Yes, I think that is correct: the 0.20231005.x versions of sniper and soldier were promoted to stable on 2023-10-18, the same day that the 0.20231016.x versions were released as new betas.

> Closing as fixed in the [2023-10-25](https://store.steampowered.com/news/app/593110/view/3723973446147960643) Steam client update

For the sake of fully correct information: that's not strictly true. This was a bug in the `Steam Linux Runtime 3.0 (sniper)` and `Steam Linux Runtime 2.0 (soldier)` compatibility tools, not a bug in the Steam client, so there was not (and will not be) any particular change made in the Steam client to address it.
