### ISSUE TITLE
Nov 5th 2024 update Linux not working w/Valheim

### ISSUE THREAD

**Issue by altacus** [ValveSoftware/steam-runtime#706] opened 2024-11-08 22:36 UTC
# Compatibility Report
- Name of the game with compatibility issues: Valheim
- Steam AppID of the game: 892970

## System Information
- GPU: Nvidia Quadro M2000 & GeForce 1080
- Video driver version: Nvidia 535
- Kernel version: 5.15.0-124
- Link to full system information report as [Gist](https://gist.github.com/altacus/e2d80792dac11c5c9de7d94dac1128d1):
- Proton version: experimental

## I confirm:
- [x] that I haven't found an existing compatibility report for this game.
- [x] that I have checked whether there are updates for my system available.

Directions are not producing logs

## Symptoms 

I have been playing valheim via steam on linux for the past several months without issue. On the Nov 5th update, I started receiving an error regarding playfab and cross play. The error message is:

`PlayFab could not load - It is necessary for using crossplay. Make sure you have installed the dependencies necessary for PlayFab Party on Linux, listed here: https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/netowrking/linux-specific-requirements`

note I was able to work around the issue by passing in the following flag `-compat-force-slr`

## Reproduction
start valheim with Nov 5th update without  `-compat-force-slr` flag on linux steam client

**Comment by kisak-valve** [comment] 2024-11-08 23:08
Hello @altacus, you're mixing up the Linux native variant of Valheim with the Windows variant. This is the former and Proton isn't involved so I've transferred this issue report to the steam-runtime issue tracker for a runtime dev to ponder.

**Comment by AngelQC** [comment] 2024-11-09 19:57
I can't wait for a new patch :-\  I also have this issue

**Comment by TTimo** [comment] 2024-11-09 22:18
You can get the fix for this early by switching the 'Steam Linux Runtime 2.0 (soldier)' to it's 'client_beta' branch.

**Comment by altacus** [comment] 2024-11-09 22:28
I just tested this out following directions here and the issue still occurs.

**Comment by altacus** [comment] 2024-11-09 22:33
> I can't wait for a new patch :-\ I also have this issue Note that the mentioned "-compat-force-slr" did not work for me, with or without mods, using steam or r2modman to launch.

Sorry the flag is
 -compat-force-slr off

**Comment by kisak-valve** [comment] 2024-11-09 22:34
Hello @altacus, opting into the Steam client beta and re-configuring Steam Linux Runtime 2.0 (Soldier) to use a beta branch are not the same thing. Search for `Steam Linux Runtime` in your Steam library and look at its per-game properties.

**Comment by altacus** [comment] 2024-11-09 23:55
@kisak-valve Thanks for the clarification. I was able to get valheim running (natively?) with the following:

Library -> Search `Steam Linux Runtime` -> Select `Steam Linux Runtime 2.0 (soldier)` -> Gear Icon -> Properties -> Betas -> `client_beta - use with Steam beta client`

**Comment by AngelQC** [comment] 2024-11-10 01:07
It did work, vanilla.  But when I go back to the server profile on r2modman, it still breaks with fatal mono error without detail because gdb cannot run 

`ERROR: ld.so: object '/home/jay/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/gdb: /home/jay/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libdebuginfod.so.1)`

Seems line

**Comment by enfermero-dev** [comment] 2024-11-11 00:00
Also **worked for me** with the steam beta client, didnt worked using  -compat-force-slr

**Comment by AngelQC** [comment] 2024-11-12 01:40
@smcv 

> What is r2modman? Is this a third-party addition to the game? Does it rely on gdb in some way?

R2modman is a Unity engine mod manager which Linux players use to launch Valheim, and other games, with mods.

Valheim seems to use gdb when unrecoverable errors occurs.  The quoted text of my previous post comes from Valheim Player.log file, which ends the log file lately when it can't initialize Mono libraries, which happens every time it's launched with mods since the game's Nov. 5th patch.

It's not clear to me which process is failing and is responsible for this Mono failure, neither why gdb is invoked, although it would be nice if it worked, it would add information for debugging.

**Comment by smcv** [comment] 2024-11-12 12:12
@AngelQC, if you can still reproduce the crash that you describe, after selecting the SLR 2.0 beta as described in https://github.com/ValveSoftware/steam-runtime/issues/706#issuecomment-2466514438, please open a *separate* issue report for the situation that you are seeing.

The reasons I ask you to do this are:

1. We don't need to keep spamming altacus with information about a crash that they do not experience
2. The separate issue report gives you an opportunity to provide information about *your* system, which is presumably not the same as theirs
3. The longer we spend mixing up two separate issues on one issue report, the harder it becomes to extract the necessary information from it, which makes bugs take longer to fix, and none of us want that

> Valheim seems to use gdb when unrecoverable errors occurs

If an unrecoverable error is happening, we should concentrate on identifying and fixing the unrecoverable error (whatever that might be), and treat any gdb invocation errors as secondary to that. Providing a fully-featured interactive debugger is out-of-scope for the Steam Runtime.

**Comment by smcv** [comment] 2024-11-19 12:41
>I was able to get valheim running (natively?) with the following:
> 
> Library -> Search `Steam Linux Runtime` -> Select `Steam Linux Runtime 2.0 (soldier)` -> Gear Icon -> Properties -> Betas -> `client_beta - use with Steam beta client`

The change that fixed this issue was included in the default branch of SLR 2.0 yesterday, so switching to a beta is no longer necessary.

If you stay on the beta, you'll get the latest improvements and bugfixes sooner. If a new beta causes some other regression for you, please report it to <https://github.com/ValveSoftware/steam-runtime/issues>, and then you should be able to work around it by switching back to the default, non-beta branch.

`SteamLinuxRuntime_soldier/VERSIONS.txt` for a version that fixes this issue will say `depot 0.20241105.107207` or newer.

**Closed** 2024-11-19 13:41 UTC
Labels: Need Retest, Pressure Vessel
