### ISSUE TITLE
Some devices not detected in versions prior to and after 0.20230111.85

### ISSUE THREAD

**Issue by kevenwyld** [ValveSoftware/steam-runtime#561] opened 2023-02-16 23:19 UTC
#### Your system information

* Steam Runtime Version: 0.20230111.85 (that's for the working SteamLinuxRuntime_soldier, not sure if I should have put some other version here, the broken one is 0.20230123.89 and also all versions prior to 0.20230111.85 are broken too)
* Distribution (e.g. Ubuntu 18.04): Archlinux
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
  https://gist.github.com/kevenwyld/eb0cd968f8e55c276d42af2da5c59878
* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime / Proton 5.13+
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
  * Older working version
    * #Name	Version		Runtime	Runtime_Version	Comment
      depot	0.20230111.85			# Overall version number
      pressure-vessel	0.20221215.0	scout		# from local file
      scripts	0.20221215.0			# Entry point scripts, etc.
      soldier	0.20230109.1	soldier	0.20230109.1	# soldier_platform_0.20230109.1/
  * Newer not-working version
    * #Name	Version		Runtime	Runtime_Version	Comment
      depot	0.20230123.89			# Overall version number
      pressure-vessel	0.20230216.0	scout		# from local file
      scripts	0.20230112.0			# Entry point scripts, etc.
      soldier	0.20230117.0	soldier	0.20230117.0	# soldier_platform_0.20230117.0/

#### Please describe your issue in as much detail as possible:

Pedals and other input devices were unreliable and only worked in some games up until 0.20230111.85.  Specifically my `Heusinkveld Sim Pedals Ultimate+` suddenly worked great in (previous versions did not work, I was ecstatic when this update came out and everything suddenly worked):

```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230111.85			# Overall version number
pressure-vessel	0.20221215.0	scout		# from local file
scripts	0.20221215.0			# Entry point scripts, etc.
soldier	0.20230109.1	soldier	0.20230109.1	# soldier_platform_0.20230109.1/
```

But no longer work in today's version:

```
#Name	Version		Runtime	Runtime_Version	Comment
depot	0.20230123.89			# Overall version number
pressure-vessel	0.20230216.0	scout		# from local file
scripts	0.20230112.0			# Entry point scripts, etc.
soldier	0.20230117.0	soldier	0.20230117.0	# soldier_platform_0.20230117.0/
```

#### Steps for reproducing this issue:
As of today (2023-02-16)
1. Use the current version of SteamLinuxRuntime_soldier
2. Launch any game with Heusinkveld Sim Pedals Ultimate+ connected
3. pedals do not work
4. go to properties on SteamLinuxRuntime_soldier in steam library -> Betas -> Previous version
5. launch game again
6. pedals work fine

I suspect this will be reproducible with any device that only has axis and not buttons.  The pedals only report 3 axis which was a previous proton bug that the last version of SteamLinuxRuntime_soldier seemed to work around.

Please let me know if there's anything I can do.  I am willing to spend as much time as necessary on this because for the last 2 weeks I was able to play every sim racing game I own on Linux for the first time ever and I'd really like that to be the case again!

Thanks!

**Comment by kisak-valve** [comment] 2023-02-16 23:46
Hello @kevenwyld, there's a good chance that https://github.com/ValveSoftware/Proton/issues/5126 is the issue report you're looking for.

There was a bug in Steam Linux Runtime - Soldier 0.20230111.85 which caused SDL to not detect that it was being run in a container environment, and that led to other unwanted behavior. This is most likely directly connected to the working case you've described as a side effect instead of by design.

While your findings could (and should) be mentioned in the linked issue report or possibly to upstream SDL's issue tracker, the bug that was fixed in today's hot fix takes priority over this use case.

**Closed by kisak-valve** 2023-02-16 23:46 UTC

**Comment by kevenwyld** [comment] 2023-02-17 00:11
@kisak-valve thanks for the explanation.  I'm sure you're right about that proton issue and my observed behavior, it's too bad this working behavior was only a side effect of a bug.  I'll be sure to post over there and see if what I found helps at all.

Is the hot fix visible as a release on github or a tag in a repo somewhere (maybe not open I guess)?  The source of `Steam Linux Runtime - Soldier` doesn't appear to be in this repo and it has no releases that I saw here.  I could just be blind though.

Thanks!

**Comment by smcv** [comment] 2023-02-17 10:50
> Is the hot fix visible as a release on github or a tag in a repo somewhere (maybe not open I guess)? The source of `Steam Linux Runtime - Soldier` doesn't appear to be in this repo and it has no releases that I saw here.

Soldier does have public release notes, but they're not straightforward to find at the moment. Here: https://gitlab.steamos.cloud/steamrt/steamrt/-/wikis/Soldier-release-notes

Projects like the Steam Runtime that are put together from many individual packages don't fit the Github/Gitlab release model particularly well, because each release can involve changes to several different components, but none of those components are guaranteed to change in every release, so there's no completely obvious place for "the release" to be represented.

The source code for soldier is a bit more complicated than just pointing to one git repository: each release is made up of [a version of steam-runtime-tools](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/) (which includes the pressure-vessel tool that launches the container), together with a container image built by [flatdeb-steam](https://gitlab.steamos.cloud/steamrt/flatdeb-steam) from the packages listed in [steamrt](https://gitlab.steamos.cloud/steamrt/steamrt/-/tree/steamrt/soldier). Source code for the actual packages is included in [releases](https://repo.steampowered.com/steamrt-images-soldier/snapshots/) but doesn't currently have public version-control; some are taken from Debian unmodified, and some have modifications for the Steam Runtime.

Yesterday's hotfix consisted of upgrading the pressure-vessel tool to version [0.20230216.0](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/releases/v0.20230216.0), with a workaround for a regression in SDL 2.26 that prevented it from detecting hotplugged game controllers as intended.

I think that regression accidentally had the side-effect of Proton identifying your pedals as pedals, rather than thinking they were probably an accelerometer that needed to be ignored.

**Comment by kevenwyld** [comment] 2023-02-17 14:51
@smcv Thank you so much for taking the time to explain all that!  And for your contributions in the linked thread as well!

**Comment by schlegp** [comment] 2023-02-24 08:21
Since I am not able to provide much else that might be helping, here is the output of steam-runtime-input-monitor when hotplugging my VRS DirectForcePro Pedals:

`{
  "added" : {
    "interface_flags" : [
      "event",
      "readable",
      "read-write"
    ],
    "type_flags" : [
      "accelerometer"
    ],
    "dev_node" : "/dev/input/event4",
    "subsystem" : "input",
    "sys_path" : "/sys/devices/pci0000:00/0000:00:08.1/0000:0d:00.3/usb5/5-3/5-3:1.0/0003:0483:A3BE.0039/input/input68/event4",
    "bus_type" : "0x0003",
    "vendor_id" : "0x0483",
    "product_id" : "0xa3be",
    "version" : "0x0111",
    "evdev" : {
      "types" : [
        "SYN",
        "ABS"
      ],
      "absolute_axes" : [
        "X",
        "Y",
        "Z"
      ],
      "relative_axes" : [
      ],
      "keys" : [
      ],
      "input_properties" : [
      ]
    },
    "hid_ancestor" : {
      "sys_path" : "/sys/devices/pci0000:00/0000:00:08.1/0000:0d:00.3/usb5/5-3/5-3:1.0/0003:0483:A3BE.0039",
      "name" : "Smarty Co. VRS DirectForce Pro Pedals",
      "bus_type" : "0x0003",
      "vendor_id" : "0x0483",
      "product_id" : "0xa3be",
      "uniq" : "PCC92BBA6B"
    },
    "input_ancestor" : {
      "sys_path" : "/sys/devices/pci0000:00/0000:00:08.1/0000:0d:00.3/usb5/5-3/5-3:1.0/0003:0483:A3BE.0039/input/input68",
      "name" : "Smarty Co. VRS DirectForce Pro Pedals",
      "bus_type" : "0x0003",
      "vendor_id" : "0x0483",
      "product_id" : "0xa3be",
      "version" : "0x0111"
    },
    "usb_device_ancestor" : {
      "sys_path" : "/sys/devices/pci0000:00/0000:00:08.1/0000:0d:00.3/usb5/5-3",
      "vendor_id" : "0x0483",
      "product_id" : "0xa3be",
      "version" : "0x0100",
      "manufacturer" : "Smarty Co.",
      "product" : "VRS DirectForce Pro Pedals",
      "serial" : null
    }
  }
}
`

Has anyone else had the issue of Protopedal now not working anymore aswell? Something changed and now even the workaround doesn't work anymore.
