### ISSUE TITLE
The Swords of Ditto: Mormo's Curse (619780) doesn't launch

### ISSUE THREAD

**Issue by DanMan** [ValveSoftware/steam-runtime#410] opened 2021-05-12 16:54 UTC
#### Your system information

* Steam Runtime Version: steam-runtime_0.20210422.0
* Distribution (e.g. Ubuntu 18.04): Fedora 33
* [Link to your full system information](https://gist.github.com/DanMan/df94fe2dc319aad76fc097c2f90e6329/a75201dff250134bf8df58f01aae106ebca44565)
* Have you checked for system updates?: [Yes]
* Are you using the Steam Linux Runtime compatibility tool?: [Yes]

#### Please describe your issue in as much detail as possible:
Game doesn't launch at all.

Tried to set `STEAM_LINUX_RUNTIME_LOG=1` but then steam wouldn't even launch.

#### Steps for reproducing this issue:

1. Launch Steam
2. Enable "Steam Linux Runtime" for the game
3. Launch game

Among the usual errors there's this line in the terminal:

```
./The_Swords_of_Ditto: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
It's a pretty shoddy port to begin with though. Crashes a lot in general.

**Comment by smcv** [comment] 2021-05-13 14:16
Looks like this game has been compiled in the wrong environment: it is assuming it will be able to load OpenSSL 1.1, but Steam Runtime 1 'scout' only guarantees to provide OpenSSL 1.0.

The "Steam Linux Runtime" compatibility tool currently provides a very, very strict scout environment with as few updated libraries from your host system as possible, so games like this won't work there.

**Comment by DanMan** [comment] 2021-05-13 16:34
These are the dependencies for the executable:

```
$ ldd The_Swords_of_Ditto
./The_Swords_of_Ditto: /lib64/libcurl.so.4: no version information available (required by ./The_Swords_of_Ditto)
	linux-vdso.so.1 (0x00007ffd6bdce000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f1d71bc6000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1d719de000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f1d719c4000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f1d719bd000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f1d71936000)
	libopenal.so.1 => /lib64/libopenal.so.1 (0x00007f1d71853000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1d7170d000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f1d71702000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1d716e1000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f1d716da000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f1d713ed000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f1d713d8000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f1d7128f000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f1d71282000)
	libGLU.so.1 => /lib64/libGLU.so.1 (0x00007f1d7122b000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f1d7118e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1d71173000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1d70fa4000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f1d70f78000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f1d70f57000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f1d70eea000)
	libpsl.so.5 => /lib64/libpsl.so.5 (0x00007f1d70ed7000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f1d70e83000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f1d70dad000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f1d70d93000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f1d70d8d000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f1d70d3d000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f1d70d2c000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f1d70d1e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1d71c75000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f1d70cec000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f1d70c32000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f1d70c08000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f1d70bfb000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f1d70a78000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f1d70a67000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f1d70a5e000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f1d70a44000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f1d70a25000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f1d70a02000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f1d709fd000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1d709ce000)
	libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f1d70994000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f1d708fd000)
```

So I guess you're spot on.

**Comment by kisak-valve** [comment] 2021-05-13 16:37
`lddtree` might reveal if it's a direct dependency, or if it's being pulled in by a library.

**Comment by DanMan** [comment] 2021-05-13 16:40
```
$ lddtree The_Swords_of_Ditto
The_Swords_of_Ditto => ./The_Swords_of_Ditto (interpreter => /lib64/ld-linux-x86-64.so.2)
    libcurl.so.4 => /lib64/libcurl.so.4
        libnghttp2.so.14 => /lib64/libnghttp2.so.14
        libidn2.so.0 => /lib64/libidn2.so.0
            libunistring.so.2 => /lib64/libunistring.so.2
        libssh.so.4 => /lib64/libssh.so.4
            ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
        libpsl.so.5 => /lib64/libpsl.so.5
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2
            libkrb5support.so.0 => /lib64/libkrb5support.so.0
                libselinux.so.1 => /lib64/libselinux.so.1
                    libpcre2-8.so.0 => /lib64/libpcre2-8.so.0
            libkeyutils.so.1 => /lib64/libkeyutils.so.1
            libresolv.so.2 => /lib64/libresolv.so.2
        libkrb5.so.3 => /lib64/libkrb5.so.3
        libk5crypto.so.3 => /lib64/libk5crypto.so.3
        libcom_err.so.2 => /lib64/libcom_err.so.2
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2
            libsasl2.so.3 => /lib64/libsasl2.so.3
                libcrypt.so.2 => /lib64/libcrypt.so.2
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1
            libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1
    libstdc++.so.6 => /lib64/libstdc++.so.6
    libz.so.1 => /lib64/libz.so.1
    libXxf86vm.so.1 => /lib64/libXxf86vm.so.1
    libGL.so.1 => /lib64/libGL.so.1
        libGLX.so.0 => /lib64/libGLX.so.0
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0
    libopenal.so.1 => /lib64/libopenal.so.1
    libm.so.6 => /lib64/libm.so.6
    librt.so.1 => /lib64/librt.so.1
    libpthread.so.0 => /lib64/libpthread.so.0
    libdl.so.2 => /lib64/libdl.so.2
    libcrypto.so.1.1 => /lib64/libcrypto.so.1.1
    libXext.so.6 => /lib64/libXext.so.6
    libX11.so.6 => /lib64/libX11.so.6
        libxcb.so.1 => /lib64/libxcb.so.1
            libXau.so.6 => /lib64/libXau.so.6
    libXrandr.so.2 => /lib64/libXrandr.so.2
        libXrender.so.1 => /lib64/libXrender.so.1
    libGLU.so.1 => /lib64/libGLU.so.1
    libssl.so.1.1 => /lib64/libssl.so.1.1
    libgcc_s.so.1 => /lib64/libgcc_s.so.1
    libc.so.6 => /lib64/libc.so.6
```

**Comment by smcv** [comment] 2021-05-13 17:05
It's a direct dependency. Instead of being compiled in the Steam Runtime 1 'scout' environment, this game was probably compiled on some later OS (maybe Ubuntu 18.04?) and never tested on anything older.

**Comment by DanMan** [comment] 2021-05-13 17:18
Yup. Copying both `libcrypto.so.1.1 ` and  `libssl.so.1.1` into the game's folder allowed it to launch within PV.

**Comment by smcv** [comment] 2021-05-26 19:26
We now have a prototype of a different approach to running native Linux games on SLR, which might resolve this. If you [go into the list of SLR betas](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#using-a-beta-or-an-older-version) and choose the `scout_layered_slim` branch, you'll get the Steam Runtime v1 'scout' `LD_LIBRARY_PATH` runtime, running inside the same Steam Runtime v2 'soldier' container that Proton uses. This is an implementation of https://github.com/ValveSoftware/steam-runtime/blob/master/doc/possible-designs.md#steam-runtime-2-container-with-ld_library_path-runtime-inside from the design document I wrote a while ago.

Please remove your workaround (delete the copies of `libcrypto.so.1.1` and `libssl.so.1.1` from the game's directory), then try that branch and see whether it works?

If the `scout_layered_slim` branch breaks any of your *other* games, please report that as a separate issue, and make it as obvious as possible that you're using the `scout_layered_slim` branch.

If this approach is successful, then it will eventually replace the current approach to running native scout games in SLR.

> It's a pretty shoddy port to begin with though. Crashes a lot in general.

We're not going to be able to fix that! But if this game works acceptably without SLR on a distro of about the same age as Debian 10, then it should work similarly in the "layered" container, because Steam Runtime 2 'soldier' is mostly the same as Debian 10.

**Comment by smcv** [comment] 2021-05-26 19:29
Sorry, I should have mentioned: if launching games in `scout_layered_slim` doesn't work immediately, try exiting from Steam completely, and starting Steam again. Similarly, if you go back from `scout_layered_slim` to the default or `client_beta` branch, you might need to exit from Steam and restart it.

**Comment by DanMan** [comment] 2021-05-26 20:59
Game does launch when using `scout_layered_slim`. I deleted the 2 SO files, had to restart Steam.

P.S.: Had to fix an issue with updating the runtime first. Update failed with "disk write error" and got a popup about a problem with `awk`. Could neither uninstall the runtime nor verify its files. Had to delete all the folders in the `SteamLinuxRuntime` folder in the library first, then verification worked and it would update itself.

**Comment by smcv** [comment] 2021-05-27 11:27
> Had to fix an issue with updating the runtime first. Update failed with "disk write error" and got a popup about a problem with awk

We're aware of this and it's being looked at. It seems to be a problem with distributing symlinks via Steam's download manager, which affects the SteamLinuxRuntime `client_beta` branch (but not the default branch or `scout_layered_slim`).

It seems that retrying the update two more times will usually work. If not, deleting everything from the `SteamLinuxRuntime` directory and re-verifying it is the brute-force approach.

**Comment by smcv** [comment] 2021-06-09 10:49
> ["Disk write error"] seems to be a problem with distributing symlinks via Steam's download manager, which affects the SteamLinuxRuntime `client_beta` branch (but not the default branch or `scout_layered_slim`).

This is only tangentially related to this issue report, but anyway: the `client_beta` and default branches now contain a workaround for this, which seems to be reliable.

**Comment by DanMan** [comment] 2021-06-10 16:19
Just for the record: I already got it running, as mentioned in my last post. So… re-test succeeded? Or shall I test `client_beta` again?

**Comment by smcv** [comment] 2021-06-10 16:43
Let's leave this open until we are ready for the new approach used in `scout_layered_slim` to become the default.

**Comment by smcv** [comment] 2021-07-20 19:02
We have now shipped the equivalent of `scout_layered_slim` as the default.

I don't have this particular game, but since @DanMan confirmed that it worked in `scout_layered_slim` and I was able to launch several other GameMaker titles (#216, #235 and the demo of Demetrios), I think we can be reasonably confident that this is solved now.

**Comment by kisak-valve** [comment] 2021-08-20 13:42
Closing per the last comment.

**Closed by kisak-valve** 2021-08-20 13:42 UTC
Labels: Need Retest, Pressure Vessel
