### ISSUE TITLE
Any steam game will not run on Manjaro if you are using the snap version instead of the Multilib (solved). 

### ISSUE THREAD

**Issue by aboimpinto** [ValveSoftware/steam-runtime#532] opened 2022-09-19 22:06 UTC
#### Your system information

* Steam Runtime Version: 
![image](https://user-images.githubusercontent.com/1231687/191127062-00d80b96-e6fb-4bc4-a26b-39cf2a478cfc.png)

* Distribution: Manjaro (full update 19.09.2022) 
* Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/): 
 https://gist.github.com/aboimpinto/64d59738ae5d8745735d207472a1e5c6
  
* Have you checked for system updates?: [Yes]
* What compatibility tool are you using?: [Proton 5.13+]
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?

<details>
<summary>VERSIONS.txt</summary>
#Name   Version         Runtime Runtime_Version Comment
depot   0.20220804.66                   # Overall version number
pressure-vessel 0.20220803.0
scripts v0.20220803.0-0-gbca628e                        # Entry point scripts, etc.
soldier 0.20220803.0    soldier 0.20220803.0    # soldier_platform_0.20220803.0/
</details>

#### Please describe your issue in as much detail as possible:

I used Proton experimental and 7.0-4 with the same result.
the game just doesn't start.
Bellow, I provide the output information from the console

[Cyberpunk console log](https://gist.github.com/aboimpinto/7f079194911cbf758d2bcf03dc84711b)

#### Steps for reproducing this issue:

1. Open Steam
2. Choose CyberPunk game and run it 
3. The game never starts

*UPDATE*
The same behavior is happening with other games like AmongUs

thanks
Paulo Aboim Pinto

**Comment by smcv** [comment] 2022-09-20 14:43
This looks like a possible root cause:

```
x86_64-linux-gnu-capsule-capture-libs: code 13: open "/var/cache/ldconfig/ld.so.cache": Permission denied
```

What are the permissions on `/var`, `/var/cache`, `/var/cache/ldconfig` if it exists, and `/var/cache/ldconfig/ld.so.cache` if it exists?

(And please provide the rest of the information that the issue template asks for.)

**Comment by aboimpinto** [comment] 2022-09-20 20:31
Thanks for the answer
This is a fresh installed Manjaro and  the folders are under root permissions.

I add the VERSIONS.txt file and the system information to the issue ... 
Is there anything missing? 

Hope that now I can get some help
thanks
Paulo Aboim Pinto

**Comment by smcv** [comment] 2022-09-22 12:38
> This is a fresh installed Manjaro and the folders are under root permissions

That doesn't answer my question: root is an owner, not a permission. Please provide the output of:

```
ls -ld /var /var/cache /var/cache/ldconfig /var/cache/ldconfig/ld.so.cache
```

**Comment by aboimpinto** [comment] 2022-09-22 13:05
![image](https://user-images.githubusercontent.com/1231687/191754579-f8476699-1f45-490a-a6e4-0a038aac961e.png)

still dunno why the ld.so.cache is not accessible ... 

![image](https://user-images.githubusercontent.com/1231687/191754752-01fd5f2d-50a4-41d3-95ef-a592c13a84c1.png)

**Comment by RyuzakiKK** [comment] 2022-09-22 13:14
> Link to your full system information (Help -> System Information) in a [Gist](https://gist.github.com/):

This is accessible from the Steam client. The file that you posted is probably from your OS settings or something similar?

You should open Steam, and then go to Help and click on "System Information". Wait for it to complete and then copy the output.

> still dunno why the ld.so.cache is not accessible ...

This means that `/var/cache/ldconfig/ld.so.cache` is not available, which is probably expected in Arch Linux/Manjaro.

**Comment by smcv** [comment] 2022-09-22 13:34
The fact that `/var/cache/ldconfig/ld.so.cache` doesn't exist is not necessarily a problem: it will usually only exist on ClearLinux.

The fact that `/var/cache/ldconfig` is unreadable is also not necessarily a problem: it's also unreadable on my Debian system.

However, the fact that you're seeing that error message means that the container runtime was unable to open `/etc/ld.so.cache`, which should normally exist and be readable by everyone. Does that file exist? What are its permissions?

**Comment by smcv** [comment] 2022-09-22 13:36
From the log:

> `/home/esqueleto/snap/steam/common/.local/share/Steam/ubuntu12_32/`

Does this mean you are running Steam from the unofficial Snap app?

**Comment by aboimpinto** [comment] 2022-09-22 14:43
that's strange ... the snap is using the Ubuntu version ... possible, that's the solution for not working ...  
let me see if I can find another way to install the steam on Manjaro!

NOTE: I changed from Ubuntu to Manjaro. In Ubuntu was working very well ... never got problems

**Comment by aboimpinto** [comment] 2022-09-22 14:59
looks like that was the issue ... I installed AmongUs (fast game installation) and worked ... 
the snap version is tailored for Ubuntu and not for any distribution...
I'm installing and will run CyberPunk, and this may work...

**Comment by aboimpinto** [comment] 2022-09-22 15:25
yes .. that was the problem ... 
the snap version is not compatible with Manjaro ... 

thanks for spotting that in the log ...
who we can contact to fix the snap version?

thanks a lot
Paulo Aboim Pinto

**Comment by aboimpinto** [comment] 2022-09-22 15:29
maybe we cannot contact anyone ..

![image](https://user-images.githubusercontent.com/1231687/191788996-b7c0f120-2ce1-4561-9ce9-f880490fea87.png)

looks like this is maintained by canonical it self ...

at least now it's working and I thanks that to you @smcv 
thank you!
Paulo Aboim Pinto

**Comment by smcv** [comment] 2022-09-22 15:42
Yes, please contact Canonical via https://github.com/canonical/steam-snap if there are issues with the unofficial Snap Steam package that are not reproducible in the non-sandboxed version. Valve does not support the Snap package, and Canonical describes it as a beta.

> the snap version is not compatible with Manjaro

Snap is heavily dependent on AppArmor, and Canonical's Snap Steam package requires features of very recent snapd versions, so it wouldn't surprise me if it only works on Ubuntu. I suspect there might be incompatibilities with Manjaro's AppArmor rules or Manjaro's packaged version of snapd.

**Comment by smcv** [comment] 2022-09-22 15:43
@kisak-valve, please could you retitle this issue to something about the container runtime not working in the Snap package on Manjaro (this is not a Cyberpunk specific issue, it would affect any Proton game equally), and perhaps close it as not our bug?

**Closed** 2022-09-22 16:15 UTC
