### ISSUE TITLE
Linux Runtime Soldier: bash: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by Cynosure-null** [ValveSoftware/steam-runtime#545] opened 2022-11-11 22:21 UTC
#### Your system information

* Steam client version (build number or date): Built Oct 19 2022, zypper's latest version
* Distribution (e.g. Ubuntu): OpenSUSE tumbleweed
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

Expected behavior:
Games process vulkan shaders for a minute than launch with no issues. This happened previously on my machine around last week.

Actual behavior:
All proton games (even those that can run using only wine or native games forced to use proton) process vulkan shaders for a second and then crash. Game logs here: https://gist.github.com/Cynosure-null/282376f514bd55a780d8408424150a84

#### Steps for reproducing this issue:
(Note: I did not have the drive space to create a testing VM. This assumes you have the same system config as me. If needed I can find some space and spin up an environment)
1. Open Steam 
2. Run a Windows only game that is confirmed to work on proton (Planetside 2 with --no-gpu in my case, but any game works)
3. View logs. 

Also my steam system information says that "Linux Runtime Soldier: bash: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE"

**Comment by kisak-valve** [comment] 2022-11-11 22:34
Hello @Cynosure-null, Proton 5.13 and newer runs inside of the Steam Linux Runtime - Soldier container environment, and your bash related message sounds like there's an issue with that before Proton itself gets a chance to run.

Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and share the requested information for a runtime dev to ponder.

**Comment by smcv** [comment] 2022-11-14 22:46
Please get a new log like that one, but add `STEAM_LINUX_RUNTIME_VERBOSE=1` in the environment?

**Comment by smcv** [comment] 2022-11-15 13:05
Something is going badly wrong here, but it's not immediately clear what. The error message you originally reported and the one you're now getting in `slr-latest.log` are entirely different, which suggests they might both be symptoms of some hidden problem.

Is there anything unusual about your soldier installation directory `/home/laptop-main/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier`, or any of its parent directories? Some examples of the sort of thing that counts as unusual and can interfere with the container runtime:

* non-Linux filesystems like NTFS, FAT or ExFAT
* networked filesystems like SMB/CIFS or NFS
* Linux filesystems other than ext3/ext4/btrfs (for instance overlay mounts or ZFS are unusual)
* symbolic links anywhere in the path
* directories inside your `$HOME` owned by a user other than you
* parent directories of your `$HOME` owned by a user other than `root`
* running Steam in a container like Flatpak, Snap, Docker or Firejail
* running Steam with seccomp or AppArmor confinement

There's a bug in the container runtime's error handling, which is the reason for the `glnx_close_fd` assertion failure; you should be getting a different error message that indicates the real error, but that error isn't being detected correctly. Coincidentally, I think I already fixed the error-handling bug while doing some other maintenance, so I'll put together a test version you can try that will show us the real error message.

To isolate the various possible root causes for this, it would be useful if you could install a small native Linux game, ideally a free-to-play one so that everyone looking into this can be trying the same thing (we often use [Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) for this purpose), then go into its Properties -> Compatibility and set it to use the "Steam Linux Runtime" compatibility tool. Then use that game, instead of the one you originally wanted to play, as the game you try launching. By doing that, you'll be testing the container runtime, but avoiding anything that might be specific to Proton or your unofficial Proton-GE build, which will narrow down the components that we have to look at.

It would also be interesting if you could cd into the `SteamLinuxRuntime_soldier/var/tmp-*` directory (there should only be one directory like that at a time), and do a `find . -ls`, so that I can see what has and hasn't been created in that directory.

**Comment by smcv** [comment] 2022-11-15 22:02
> There's a bug in the container runtime's error handling, which is the reason for the glnx_close_fd assertion failure; you should be getting a different error message that indicates the real error, but that error isn't being detected correctly. Coincidentally, I think I already fixed the error-handling bug while doing some other maintenance, so I'll put together a test version you can try that will show us the real error message.

If you replace `SteamLinuxRuntime_soldier/pressure-vessel/` with the result of unpacking <https://repo.steampowered.com/pressure-vessel/snapshots/0.20221115.1/pressure-vessel-bin.tar.gz>, that should give you a better log with a bit more indication of what is going on here: instead of the assertion failure, it should report the actual failure reason. Use the ["Verify integrity" button](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) on "Steam Linux Runtime - soldier" when you want to go back to the released version.

**Comment by smcv** [comment] 2022-11-16 13:20
> Also, why does steam want to write to `/boot/`? It seems like it shouldn't need to do that

That's the Steam client, not the Steam Runtime, so this is out of scope for this issue tracker.

(The answer is that it's checking whether each of your mounted filesystems would be a suitable place to put a Steam library. On OS drives, you don't have permission to write there, so the check has no practical effect. I don't know why it does this "eagerly" instead of waiting until you actually create a Steam library there. https://github.com/ValveSoftware/steam-for-linux/ would be the place if you want to ask for it to not do that.)

**Comment by smcv** [comment] 2022-11-16 13:22
> ~/.steam is a symlink to ~/.local/share/Steam

Are you sure? The normal arrangement is that `~/.steam/steam` and `~/.steam/root` are symlinks to `~/.local/share/Steam`, but `~/.steam` is a real directory. If that's not what you have, then this *might* be something that is worth following up on.

**Comment by smcv** [comment] 2022-11-16 18:56
> I did switch from bash to fish recently

What exactly do you mean by this? Do you mean you used `chsh` or similar to change the shell that is listed in the 7th field of `/etc/passwd`, or do you mean you changed the target of the `/bin/sh` symlink, or what?

**Comment by smcv** [comment] 2022-11-17 12:00
> Here is the new gist https://gist.github.com/Cynosure-null/6d1a61394a3af4f1d5062c4ef9a568cb

That's a log from the old version of pressure-vessel: `I: pressure-vessel version 0.20220927.0` (and it's also Proton rather than Floating Point, so what's happening there is a bit more complicated).

We should try to get a native Linux game like Floating Point working first, because those are simpler, and then we can look again at Proton after you have a native Linux game working.

You seem to be having two different failure modes at different times:

1. `symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE`
2. `glnx_close_fd: assertion failed: (errno != EBADF)`

and at the moment I don't know whether they are related or unrelated.

It might be easier to keep track if you can collect Steam's output, *without* sending pressure-vessel logging to a separate log - that way, you'll know that you're definitely seeing the current status, and not something old. To do that, do something like this:

* completely exit from Steam
* delete `SteamLinuxRuntime_soldier/var/slr-*.log` so old logs are not confusing you
* run Steam from a terminal, as: `STEAM_RUNTIME_VERBOSE=1 steam 2>&1 | tee steam.log`
* *don't* set `STEAM_LINUX_RUNTIME_LOG`
* launch your game (Floating Point is an excellent example, letting its GTK launcher run is enough)
* exit from your game
* completely exit from Steam again

If all goes well, those steps should make all the pressure-vessel debug logging come out of Steam's standard error stream and into `steam.log`. So you should see something like this:

```
/bin/sh\0-c\0/home/laptop-main/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=302380 -- /home/laptop-main/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- ...
Game process added : AppID 302380 ...                                                                 
chdir /home/laptop-main/.local/share/Steam/steamapps/common/Floating Point
_v2-entry-point[12345]: argv: ...
pressure-vessel-wrap[12350]: I: pressure-vessel version 0.20221115.1
...
bash: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
```

> I used chsh, but have since used chsh to change back.

Thanks for checking that. I assume the symptoms didn't change?

Changing your interactive shell with chsh *shouldn't* break anything, but your interactive shell is sometimes involved in graphical session startup, so it can have surprising side-effects.

> Here is find . -ls

That's very incomplete, so I'm not surprised it isn't working. There are two possible reasons for this. One is that pressure-vessel-wrap is crashing or otherwise going wrong while it is halfway through setting up the container, and the other is that the `SteamLinuxRuntime_soldier/soldier_platform_0.20220927.0` directory is incomplete or has got corrupted.

After you have collected the detailed log with the system in its current state, it might be worth trying to use the ["Verify integrity" button](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) on "Steam Linux Runtime - soldier", to make sure Steam has downloaded it correctly. Using "Verify integrity" will reset `SteamLinuxRuntime_soldier/pressure-vessel/` to the production version, so if that doesn't solve it, you will need to upgrade pressure-vessel to v0.20221115.1 again in order to continue to get detailed logs.

**Comment by smcv** [comment] 2022-11-17 20:06
> Floating Point works perfectly fine until I go to Settings / Manage / Compatibility / Force the use of a specific Steam Play compatibility tool / Steam Linux Runtime

Yes, that's as expected. This issue is a problem with the container runtime, which most native Linux games don't use unless you force them to. (It's good to know that this game works correctly without the container runtime, though!)

**Comment by smcv** [comment] 2022-11-17 20:19
> Floating point logs: https://gist.github.com/Cynosure-null/172b8a31a36aa0776e61b456cc9e5429

I'm still not seeing any log output from pressure-vessel in there.

If you're sure you had `STEAM_RUNTIME_VERBOSE=1` set in Steam's environment, then another possibility is that there might be something that is more generally broken involving `bash`. `SteamLinuxRuntime_soldier/_v2-entry-point` is a `#!/usr/bin/env bash` script, and it's required when starting the container runtime, so if the bash in the `PATH` is broken, then the container runtime will fail, before pressure-vessel has had a chance to run.

Do you have any shared libraries in `/usr/local` or in the `$LD_LIBRARY_PATH` that could be interfering with this? Or any `LD_PRELOAD` or `LD_AUDIT` modules that are getting loaded into game processes?

Or do you perhaps have a broken or wrong version of `bash` in the `PATH`? What do you get if you run `which bash`, for instance?

The reason I find this weird is that `~/.steam/root/steam.sh` is also a `#!/usr/bin/env bash` script, so if the `bash` in your `PATH` is broken, I would expect Steam to fail to start...

You could try setting the launch options for Floating Point to `LD_DEBUG=libs %command%` to make the dynamic linker tell us exactly which libraries it's loading? This will be very, very verbose, but perhaps it will give us a clue...

**Comment by smcv** [comment] 2022-11-18 20:10
> I think I found my issue... `/home/laptop-main/.nix-profile/bin/bash`

I think what has happened here goes something like this:

* Your host system (openSUSE) has some version of glibc (I don't know what version).
* Your Nix installation contains a version of `bash` built against some different version of glibc.
* Normally, the Nix `bash` finds its glibc in `/nix/...` via the `DT_RUNPATH` ELF header in the binary.
* However, the `LD_LIBRARY_PATH` scout runtime sets up a long `LD_LIBRARY_PATH` which can be simplified to something like this (there are really more entries, but this is enough to illustrate the problem):
    * `$HOME/.steam/root/ubuntu12_32/steam-runtime/pinned_libs64` (highest priority)
    * `/usr/lib64`
    * `$HOME/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu` (lowest priority)
* `LD_LIBRARY_PATH` is higher priority than `DT_RUNPATH`. This means that when we try to run Nix `bash` in the Steam Runtime environment, we get Nix's dynamic linker `/nix/.../ld-linux-x86-64.so` trying to load openSUSE's glibc `/usr/lib64/libc.so.6`.
* The dynamic linker calls private functions in glibc, which means it crashes when it tries to load a non-matching glibc version.

Workaround: run Steam as `PATH=/usr/bin:/bin steam` so that your Nix bash is not on the `PATH` that it sees.

> This issue is a problem with the container runtime

If I'm right, then this is actually not really a problem with the container runtime, but rather a problem with the `LD_LIBRARY_PATH` runtime which makes Nix's bash crash on startup, breaking any `#!/usr/bin/env bash` script - and the container runtime happens to use a `#!/usr/bin/env bash` script. This is not going to be straightforward to solve.

**Comment by smcv** [comment] 2022-11-18 20:18
> The reason I find this weird is that `~/.steam/root/steam.sh` is also a `#!/usr/bin/env bash` script, so if the bash in your PATH is broken, I would expect Steam to fail to start...

If my current theory is correct, the reason this didn't fail is that it is `~/.steam/root/steam.sh` that sets up the `LD_LIBRARY_PATH` runtime that is used to run the rest of Steam, so it is only bash scripts that are run as descendants of that script that are broken on your system, and not that script itself.

**Comment by smcv** [comment] 2022-11-21 14:06
> Would running rm -frv ~/.local/share/Steam/ && rm -frv ~/.steam/ and reinstalling everything help or just waste time?

Please don't: it'll waste a bunch of your time re-downloading large games that didn't need to be re-downloaded, and if you do, we'll never know what was wrong or how to fix it.

> Running `/usr/bin/bash` and then `PATH=/usr/bin:/bin steam` and launching floating point does not work.

It doesn't work, but it does at least manage to *start* the container runtime, so this is progress! The log says:

```
pressure-vessel-wrap[12195]: E: Could not create copy "./lib/steamrt/expectations/x86_64-linux-gnu/libstdc++6.symbols" from "/home/laptop-main/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220927.0/files/./lib/steamrt/expectations/x86_64-linux-gnu/libstdc++6.symbols" into "/home/laptop-main/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-WUXYV1/usr": fstatat(./lib/steamrt/expectations/x86_64-linux-gnu/libstdc++6.symbols): No such file or directory
```

This means we have got through the shell-script wrapper and we are running the C code to start the container, but your copy of the container runtime is missing some of its files, so it doesn't work.

I think this might be related to the `glnx_close_fd: assertion failed: (errno != EBADF)` error from some of the logs you previously captured. Back in [an earlier comment](https://github.com/ValveSoftware/steam-runtime/issues/545#issuecomment-1315283981), I said that there was a bug in the container runtime's error handling which was giving you this assertion failure instead of the real error. Now that you're using pressure-vessel 0.20221115.1, that bug in the error handling has been fixed, so we can see the real error you're encountering, and I think this could be it.

Please try this:

1. `cd ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220927.0; find -ls > ../var/platform-before-verify.log`
2. Delete `SteamLinuxRuntime_soldier/var/slr-*.log` so old logs can't be mixed up with new ones.
3. Run Floating Point via Steam Linux Runtime, with `STEAM_LINUX_RUNTIME_VERBOSE=1` and `STEAM_LINUX_RUNTIME_LOG=1` in the environment (and keep using the same `PATH` workaround as well). This should produce a new `slr-latest.log` which ends with a similar `Could not create copy` error. Save that log as `slr-before-verify.log`.
4. Attach `platform-before-verify.log` and `slr-before-verify.log` here or send them as a Gist.
5. Delete `SteamLinuxRuntime_soldier/var/` so old logs can't be mixed up with new ones.
6. [Verify integrity](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) on the "Steam Linux Runtime - soldier" tool. It will re-download pressure-vessel, and hopefully other files too.
7. The "Verify integrity" step will overwrite the new pressure-vessel I provided with the public stable version, so [replace it with version 0.20221115.1 again](https://github.com/ValveSoftware/steam-runtime/issues/545#issuecomment-1315917172)
8. `cd ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220927.0; find -ls > ../var/platform-after-verify.log`
9. Run Floating Point via Steam Linux Runtime, again with `STEAM_LINUX_RUNTIME_VERBOSE=1` and `STEAM_LINUX_RUNTIME_LOG=1` in the environment (and also the `PATH` workaround). Whether it works or not, it should produce a new `slr-latest.log`. Save that log as `slr-after-verify.log`.
10. Attach `platform-after-verify.log` and `slr-after-verify.log` here or send them as a Gist.

**Comment by smcv** [comment] 2022-11-23 11:00
> No logs produced in ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var or ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel

If you were going to get a log, it would always have appeared in `SteamLinuxRuntime_soldier/var`, never in `SteamLinuxRuntime_soldier/pressure-vessel`.

What is meant to happen is that if the SLR framework inherits environment variable `STEAM_LINUX_RUNTIME_LOG=1` from a higher layer (the Steam client or your shell or a game's Launch Options), then it records a log in `var/`. Otherwise, all output (warnings and error messages) goes to the same place as Steam's own output, whatever that is: for example if you ran Steam from a terminal, it will appear on that terminal. So if you had set `STEAM_LINUX_RUNTIME_LOG=1` somehow, you should have got a log generated. Did you set that environment variable? If yes, how did you set it?

The other thing that varies is the amount of information logged. By default we only show warnings and error messages. If you set `STEAM_LINUX_RUNTIME_LOG=1` then "info" messages also get enabled, to provide a bit more detail in the log. If you set `STEAM_LINUX_RUNTIME_VERBOSE=1`, then both "info" and "debug" messages are enabled, to provide a lot more detail.

**Comment by smcv** [comment] 2022-11-23 11:13
As a summary of where we have got to now, we have seen at least three separate failure modes while looking at this issue.

* `bash: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE` is caused by running a compatibility tool or game that uses a `#!/usr/bin/env bash` script, while [having the Nix version of bash in the PATH](https://github.com/ValveSoftware/steam-runtime/issues/545#issuecomment-1320476494). The `LD_LIBRARY_PATH` set up by the old scout runtime is not compatible with the way Nix looks up libraries. Workaround: ensure `~/.nix-profile/bin` is not in the `PATH` when running Steam. As a long-term solution, we can avoid this by moving towards replacing our `#!/usr/bin/env bash` scripts with `#!/bin/sh` scripts or C code. The scripts in `SteamLinuxRuntime_soldier` rely on bash features, so we can't just swap them to `#!/bin/sh`; we will have to modify them to avoid using those features, which might require changes in lower-level components.

* `E: Could not create copy "./blahblah" from "$HOME/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_*/files/blahblah" into "$HOME/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-WUXYV1/usr": fstatat(./blahblah): No such file or directory` we do not yet understand. @Cynosure-null was able to avoid this by deleting `var`, but I don't know why that worked.

* `glnx_close_fd: assertion failed: (errno != EBADF)` is a bug in pressure-vessel's error handling. I *think* this was being triggered by the `Could not create copy` bug. The bug in the error-handling is fixed in pressure-vessel 0.20221115.1, so with that version you see the real error, `Could not create copy`, instead.

**Comment by smcv** [comment] 2022-11-23 19:26
> After verifying the files on Steam for SteamLinuxRuntime_Soldier. I should have made that clearer.

OK, that is what I thought might happen. That would indicate that there was some problem with the Steampipe distribution stuff, resulting in you having an incomplete installation of `SteamLinuxRuntime_soldier`.

**Comment by smcv** [comment] 2023-01-12 13:52
>     * `bash: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE` is caused by running a compatibility tool or game that uses a `#!/usr/bin/env bash` script, while [having the Nix version of bash in the PATH](https://github.com/ValveSoftware/steam-runtime/issues/545#issuecomment-1320476494).

The next beta of `SteamLinuxRuntime_soldier` will hopefully avoid this (I'll comment here when a suitable beta is available). We've simplified the relevant scripts so they can run under plain `/bin/sh`, to prevent this issue.

>     * `glnx_close_fd: assertion failed: (errno != EBADF)` is a bug in pressure-vessel's error handling.

As stated before, this was already fixed.

>     * `E: Could not create copy "./blahblah" from "$HOME/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_*/files/blahblah" into "$HOME/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-WUXYV1/usr": fstatat(./blahblah): No such file or directory`

This appears to have been caused by Steam not downloading the `SteamLinuxRuntime_soldier` content correctly. There is unlikely to be a whole lot we can do about this from the Steam Runtime side: the Steam client uses the same download management and CDN to download soldier that it would use to download a game or Proton, so if that download is incomplete, that's a Steam client problem.

Now that you've worked around this with "Verify Integrity", it probably won't happen again. But, if it does, please check Steam's own logs for any relevant information: I think `~/.steam/root/logs/content_log.txt` is the most relevant one?

We could potentially add a verification step to the container runtime that is triggered whenever it can't find a file that should have been there, and tell Steam to open `steam://validate/1391110` (which is "Verify Integrity") if that verification fails? But this is something that shouldn't be happening in the first place, and it could equally hit a game or Proton, which wouldn't have that extra check; so investing time into guarding against this in SLR might not be all that useful.

**Comment by smcv** [comment] 2023-01-23 20:11
> > * `bash: symbol lookup error: /lib64/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE` is caused by running a compatibility tool or game that uses a `#!/usr/bin/env bash` script, while [having the Nix version of bash in the PATH](https://github.com/ValveSoftware/steam-runtime/issues/545#issuecomment-1320476494).
> 
> The next beta of `SteamLinuxRuntime_soldier` will hopefully avoid this (I'll comment here when a suitable beta is available). We've simplified the relevant scripts so they can run under plain `/bin/sh`, to prevent this issue.

This part is fixed in today's beta version (`VERSIONS.txt` should say `scripts 0.20230112.0` or later).

**Comment by smcv** [comment] 2023-02-17 17:14
> This part is fixed in today's `client_beta` versions of soldier and sniper (in both cases, `VERSIONS.txt` should say `scripts 0.20230112.0` or later).

And now fixed in the default branch too.

**Closed** 2023-03-18 01:13 UTC
Labels: Need Retest, Pressure Vessel
