### ISSUE TITLE
Launching non-Steam Windows game with Proton 5.13 fails

### ISSUE THREAD

**Issue by popsUlfr** [ValveSoftware/steam-runtime#287] opened 2020-10-24 13:14 UTC
#### Your system information

* Steam client version (build number or date): **Oct 23 2020, at 20:26:58**
* Distribution (e.g. Ubuntu): **Arch**
* Opted into Steam client beta?: **Yes**
* Have you checked for system updates?: **Yes**
* I'm opted into the **client_beta** branch for **Steam Linux Runtime - Soldier**
* [Steam System Info](https://gist.github.com/popsUlfr/96adac7690c83232b65b1d4a2ed83aa4)

#### Please describe your issue in as much detail as possible:

When adding a non-steam windows game and forcing the use of a specific Steam Play compatibility tool to **Proton 5.13-1**, it silently fails. There's no user feedback to inform that it failed to launch.
Choosing **Proton 5.0-9** or a custom Proton version like **Proton-5.9-GE-8-ST** instead works.

Game is _Paranormal Entities_ downloaded via itch.io if that is of any help.

#### Steps for reproducing this issue:

1. ADD A GAME > Add a Non-Steam Game... > Browse to .exe
2. Go to game's **Properties**
3. Check **Force the use of a specific Steam Play compatibility tool**
4. Select **Proton 5.13-1**
5. Play

#### Log

```
GameAction [AppID 4255205971, ActionID 4] : LaunchApp changed task to UpdatingAppTicket with ""
GameAction [AppID 4255205971, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 4255205971, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 4255205971, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 4255205971, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 0 "ParanormalEntities.exe", ProcID 295917, IP 0.0.0.0:0
GameAction [AppID 4255205971, ActionID 4] : LaunchApp changed task to Completed with ""
>>> Adding process 295917 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 295920 != 295918, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
_v2-entry-point[295918]: STEAM_COMPAT_APP_ID=-39761325
_v2-entry-point[295918]: STEAM_COMPAT_SESSION_ID=c2aad2a1f794a393
_v2-entry-point[295918]: XDG_RUNTIME_DIR=/run/user/1000
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 295918 for game ID 33554432
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
>>> Adding process 295919 for game ID 33554432
>>> Adding process 295921 for game ID 33554432
>>> Adding process 295922 for game ID 33554432
>>> Adding process 295923 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
>>> Adding process 295924 for game ID 33554432
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_type_ensure
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_type_ensure
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
_v2-entry-point[295918]: Mismatch: SteamAppId=0, STEAM_COMPAT_APP_ID=-39761325
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
>>> Adding process 296039 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
>>> Adding process 296040 for game ID 33554432
Game removed: AppID 0 "ParanormalEntities.exe", ProcID 295917 
Uploaded AppInterfaceStats to Steam
```

**Comment by kisak-valve** [comment] 2020-10-24 13:20
Hello @popsUlfr, let's treat this as a Pressure Vessel issue until there's a stronger indication the issue is elsewhere.

`_v2-entry-point[295918]: Mismatch: SteamAppId=0, STEAM_COMPAT_APP_ID=-39761325` looks like a possible line of interest from the log.

**Comment by TTimo** [comment] 2020-10-26 21:22
@popsUlfr can you edit `~/.steam/steam/SteamApps/common/SteamLinuxRuntime_soldier/_v2-entry-point` and set `STEAM_COMPAT_APP_ID` to 0 near the beginning of the script? See if that fixes your problem (it'll only work for running non Steam games, you'll need to remove that otherwise - just want to see if it's a good fix).

**Comment by popsUlfr** [comment] 2020-10-26 22:11
> @popsUlfr can you edit `~/.steam/steam/SteamApps/common/SteamLinuxRuntime_soldier/_v2-entry-point` and set `STEAM_COMPAT_APP_ID` to 0 near the beginning of the script? See if that fixes your problem (it'll only work for running non Steam games, you'll need to remove that otherwise - just want to see if it's a good fix).

@TTimo Yes, I can confirm that this worked! :) 

Here's the successfull launch log : 

```
GameAction [AppID 4255205971, ActionID 1] : LaunchApp changed task to UpdatingAppTicket with ""
Opted-in Controller Mask for AppId 4255205971: b
GameAction [AppID 4255205971, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 4255205971, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 4255205971, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 4255205971, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 0 "ParanormalEntities.exe", ProcID 104893, IP 0.0.0.0:0
GameAction [AppID 4255205971, ActionID 1] : LaunchApp changed task to Completed with ""
>>> Adding process 104893 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 104896 != 104894, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
_v2-entry-point[104894]: STEAM_COMPAT_APP_ID=0
_v2-entry-point[104894]: STEAM_COMPAT_SESSION_ID=849090ec4ef5da12
_v2-entry-point[104894]: XDG_RUNTIME_DIR=/run/user/1000
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
>>> Adding process 104894 for game ID 33554432
>>> Adding process 104895 for game ID 33554432
>>> Adding process 104897 for game ID 33554432
>>> Adding process 104898 for game ID 33554432
>>> Adding process 104899 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
>>> Adding process 104900 for game ID 33554432
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_type_ensure
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_type_ensure
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
pid 105009 != 104894, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/gio/modules/libgvfsdbus.so
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_type_ensure
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
>>> Adding process 105013 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105015 for game ID 33554432
Proton: Upgrading prefix from 5.0-1 to 5.13-1 (/home/popsulfr/.local/share/Steam/steamapps/compatdata/4255205971/)
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105016 for game ID 33554432
>>> Adding process 105017 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fsync: up and running.
>>> Adding process 105018 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105021 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105029 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105032 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105039 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105053 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105060 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105072 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105074 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105076 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 105078 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105082 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105102 for game ID 33554432
wine: configuration in L"/home/popsulfr/.local/share/Steam/steamapps/compatdata/4255205971/pfx" has been updated.
RecordSteamInterfaceCreation (PID 105017): SteamUtils009 / Utils
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105110 for game ID 33554432
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105112 for game ID 33554432
Fossilize INFO: Overriding serialization path: "/home/popsulfr/.local/share/Steam/steamapps/shadercache/4255205971/fozpipelinesv4/steamapprun_pipeline_cache".
Installing breakpad exception handler for appid(gameoverlayui)/version(20201023202654)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
[1026/230439.806471:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
ERROR: ld.so: object '/home/popsulfr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
>>> Adding process 105209 for game ID 33554432
pid 105019 != 105018, skipping destruction (fork without exec?)
Game removed: AppID 0 "ParanormalEntities.exe", ProcID 105110 
Uploaded AppInterfaceStats to Steam
```

**Comment by TTimo** [comment] 2020-11-04 16:49
Next beta (> Oct 28) will have a fix for this so the workaround will no longer be needed.

**Comment by Mubsshir** [comment] 2021-05-01 20:22
Hey ! my directory doesn't have this path-->~/.steam/steam/SteamApps/common/SteamLinuxRuntime_soldier/_v2-entry-point
i have this instead-->~/.steam/steam/SteamApps/common/Untrusted/ ...
so what is the fix for that...please help

**Comment by smcv** [comment] 2021-05-04 09:10
@Mubsshir: The issue described here was fixed several months ago, so you are probably seeing the same symptom as a result of something different. Please report a separate issue with more information: https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md

**Closed** 2021-05-04 10:45 UTC
Labels: Pressure Vessel

**Comment by smcv** [comment] 2021-05-04 11:42
I've confirmed that the original bug here is fixed:

* Download a free Windows game: I used minetest 5.4.1 (64-bit Windows version) from https://www.minetest.net/downloads/
* Unpack into a directory: I used ~/tmp/minetest-5.4.1-win64
* Games -> Add a Non-Steam Game to My Library, browse to `~/tmp/minetest-5.4.1-win64/bin/minetest.exe`
* Right-click -> Properties -> Compatibility -> Force the use of -> Proton 6.3-3
* Play
