### ISSUE TITLE
Factorio - can't access mod portal or log in from client when using runtime

### ISSUE THREAD

**Issue by dmarcuse** [ValveSoftware/steam-runtime#262] opened 2020-06-06 16:49 UTC
#### Your system information

* Steam Runtime Version: 0.20200505.0
* Distribution (e.g. Ubuntu 18.04): Arch Linux (kernel 5.6.15-zen)
* [System information](https://gist.github.com/dmarcuse/a02835aab351febc0ef9be885b611210)
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: Yes
* Game version: Factorio 0.18.30 [latest experimental version at time of writing]

#### Please describe your issue in as much detail as possible:

When the Steam Linux Runtime tool is used, Factorio doesn't seem to be able to connect to factorio.com for functionality like logging into an account, downloading/updating mods, or hosting a server that requires verified logins - an error will be shown about being unable to resolve the domain, with corresponding messages in the game log. When the Steam Linux Runtime isn't used, these features work as expected.

[Here's the game log from a session attempting to install/update mods, host a server with verified logins, and then login to a factorio.com account from the game settings, all of which failed.](https://gist.github.com/dmarcuse/b27ade98dafd09bbd6c49e8d43abbcdb)

#### Steps for reproducing this issue:

1. Force use of Steam Linux Runtime
2. Launch game from Steam
3. Note that all factorio.com functionality doesn't work any more

**Comment by smcv** [comment] 2020-07-27 13:20
Similar to #226 and #264, something is wrong with either name resolution or networking. I think this might have the same root cause as those other issues.

Please try the steps from https://github.com/ValveSoftware/steam-runtime/issues/226#issuecomment-587125941 and report back? That would provide useful information. The contents of your `/etc/nsswitch.conf` would also be interesting.

**Comment by dmarcuse** [comment] 2020-07-27 15:09
`getent ahosts example.com` exits with no output, and `curl http://93.184.216.34` does indeed succeed and produce a 404 page. My DNS configuration is a bit unorthodox: I'm running dnsmasq on 127.0.0.1:53 (for caching), which then resolves names through dnscrypt-proxy, running on 127.0.0.1:5354. My `resolv.conf` is a regular file, containing only `nameserver 127.0.0.1`.
<details>
<summary>/etc/nsswitch.conf</summary>

```
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

publickey: files

hosts: files mdns4_minimal [NOTFOUND=return] dns myhostname
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files

# End /etc/nsswitch.conf
```

</details>

**Comment by smcv** [comment] 2020-07-27 20:09
Like #264, that looks surprisingly normal. The steps in https://github.com/ValveSoftware/steam-runtime/issues/264#issuecomment-664404777 might also be useful to try here.

**Comment by dmarcuse** [comment] 2020-07-27 21:11
All the listed `nslookup` invocations fail. However, unlike Newbytee's results, mine do attempt to use the servers listed in the arguments rather than using `resolv.conf`:
```
[dana@DANA-DESKTOP Factorio]$ busybox nslookup example.com 8.8.8.8  
ERROR: ld.so: object '/home/dana/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Server:    8.8.8.8
Address 1: 8.8.8.8

nslookup: can't resolve 'example.com'
[dana@DANA-DESKTOP Factorio]$
```

**Comment by smcv** [comment] 2020-09-08 13:36
I have a new idea for why this might be failing. Please try this in the interactive shell inside the container:

```
LD_DEBUG=files getent ahosts example.com 2>&1 | tee getent-ahosts.log
```

and then send `getent-ahosts.log` as a gist.

I think you might see an error in that log, something like this:

```
/lib/x86_64-linux-gnu/libnss_dns.so.2: error: symbol lookup error: undefined symbol: (something) (fatal)
```

If you do, then I think I know how we can solve this in a future pressure-vessel release.

**Comment by dmarcuse** [comment] 2020-09-08 15:10
It looks like you might be right! [Here's the relevant line in the log](https://gist.github.com/dmarcuse/be48fe60a41eacae1dd71dee0a42faf7#file-getent-ahosts-log-L173).

**Comment by smcv** [comment] 2020-09-08 15:33
OK! In that case, a future SteamLinuxRuntime update will probably fix this.

**Comment by smcv** [comment] 2020-09-14 11:27
Please try with the "Steam Linux Runtime" set to the public beta branch `client_beta`, and the latest Steam client beta (Sep 10 2020 or newer). `SteamLinuxRuntime/VERSIONS.txt` should identify it as pressure-vessel 0.20200909.0+srt1 and scout 0.20200910.0.

If that version works, then we can consider this issue to be a duplicate of #226.

Note that the beta Steam Linux Runtime is not expected to work with Steam client versions older than the current beta. This is not considered to be a bug.

**Comment by dmarcuse** [comment] 2020-09-14 12:37
With the beta client and runtime, things seem to be working! I can properly use network functionality like logging in and accessing the mod portal in-game.

**Comment by kisak-valve** [comment] 2020-10-16 14:58
Thanks for retesting, closing.

**Closed by kisak-valve** 2020-10-16 14:58 UTC
Labels: Need Retest, Pressure Vessel

**Comment by dmarcuse** [comment] 2020-10-16 17:02
Awesome, thank you!
