### ISSUE TITLE
Proton 5.13-1 doesn't run with Flatpak Steam

### ISSUE THREAD

**Issue by andreldmonteiro** [ValveSoftware/steam-runtime#294] opened 2020-10-17 11:23 UTC
Proton 5.13-1 literally doesn't run any game, when clicked to play it will run and exit immediately.

Log:
[proton5.13.txt](https://github.com/ValveSoftware/Proton/files/5395533/proton5.13.txt)

System info:
https://gist.github.com/monterrr/ed24a7ff787aa3e9e938fea607c5d2b8

Flatpak steam issue:
https://github.com/flathub/com.valvesoftware.Steam/issues/642

**Comment by kisak-valve** [comment] 2020-11-01 14:05
Hello @ahvth, friendly note that I'm a moderator for Valve's issue trackers on Github and not a Valve dev myself. We'll need to hear from a Pressure Vessel dev if there's progress on this issue. As a tracking note, I left this on the Proton issue tracker for a while for visibility, but this issue is something to be resolved in Pressure Vessel or related projects.

**Comment by smcv** [comment] 2020-11-02 13:16
See also <https://github.com/flathub/com.valvesoftware.Steam/issues/642>.

> See bubblewrap and its implementation of FS rebinding without a user namespace.

This is exactly how pressure-vessel works - we use bubblewrap (we even use code recycled from Flatpak to run it). However, Flatpak doesn't allow that, because it would undermine some of the namespace properties that Flatpak relies on for security.

Solving this properly is not straightforward. We aim to solve it, but it will require code in both Flatpak and pressure-vessel (https://github.com/flatpak/flatpak/issues/3797 is the Flatpak side).

There are community builds of Proton 5.13 against the freedesktop.org SDK that can be used in the meantime (see https://github.com/flathub/com.valvesoftware.Steam/issues/642).

> the idea would be to not enforce enforce the process isolation by conditionally skipping the spawning of a new namespace if already inside a namespace

We are not using the new namespace for process isolation, so this wouldn't help. pressure-vessel is not a security boundary.

We are using the new namespace to get the ability to replace `/usr` with a known library stack, eventually on a per-game basis, so that old native Linux games can use Steam Runtime 1 'scout' (like Proton 5.0 does), new native Linux games can use Steam Runtime 2 'soldier' (like Proton 5.13 does), and even newer native Linux games can use a future Steam Runtime 3, without new games causing old games to regress.

The first thing to be using Steam Runtime 2 happens to have been Proton 5.13 rather than a game, because the Proton developers were finding it increasingly difficult and limiting to keep compiling Proton against what is effectively a version of Ubuntu from 2012. It's the same principle: the official Proton 5.13 binaries want the library stack from Steam Runtime 2, not older, not newer.

There's more background information in the `doc/` directory of this repository or in [my talk at FOSDEM 2020](https://archive.fosdem.org/2020/schedule/event/containers_steam/).

**Comment by ahvth** [comment] 2020-11-03 09:46
I just wanted to say thanks for taking the time to reply, and it all sounds very exciting!

**Comment by nickavem** [comment] 2020-11-15 17:00
I love the Steam flatpak (and maybe even hope valve upstreams it at some point wink) and I really hope this issue gets fixed soon. Community Proton Builds built on the actual flatpak runtime seem to bypass a lot of these issues. This can easily be installed with flatpak install com.valvesoftware.Steam.CompatibilityTool.Proton and should show up with all the other proton versions in Force the use of a specific compatibility tool. I'm honestly not completely sure how or why it works, but hey, it works!

**Comment by gasinvein** [comment] 2020-11-15 18:20
@nickavem 
>I'm honestly not completely sure how or why it works

No magic here. Since it's built on the flatpak runtime, it doesn't depend on Steam Runtime, and, thus, doesn't need pressure-vessel to run.

**Comment by Pixeliz3d** [comment] 2020-12-10 19:59
Cyberpunk 2077 with Freedesktop build Proton fails with error
```wine: Unhandled exception 0x80000003 in thread 1d0 at address 024BC828 (thread 01d0), starting debugger...```

Proton-GE Freedesktop build launches game, but crashes after character editor

OS: Arch Linux with latest updates
Kernel: 5.9.13-tkg-pds
Video driver: nvidia-tkg 455.45.01
CPU: Ryzen 1600AF
GPU: Nvidia Geforce GTX 980
Flatpak 1.9.2
Latest Steam version

**Comment by nickavem** [comment] 2020-12-10 20:01
Cyberpunk isn’t supported on Proton GE or Nvidia yet. You could try your
luck with 1.13-4 however...

**Comment by gasinvein** [comment] 2020-12-10 20:08
Mesa in flatpak's `org.freedesktop.Platform.GL.default` is not recent enough. You'll need `org.freedesktop.Platform.GL.mesa-git` for it. But this is kinda off-topic here, ask in the flatpak IRC channel if you need help with running Cyberpunk, or file a bug to the community build.

**Comment by nickavem** [comment] 2020-12-10 20:12
Forgot about this one lol. I think there is a way to get Mesa-git to work,
but I don’t remember...

**Comment by cold-distance** [comment] 2020-12-20 13:46
Hi, I just want to say that Proton provided through Steam doesn't work with the Flatpak version of the client, but Proton Community Edition provided through Flatpak seems working.

I'm using Fedora 33 Workstation now, but I'm thinking to switch back to Debian Bullseye with the Flatpak version of Steam because my intention is to keep Bullseye when it becomes into the Stable branch of Debian, so the parallel version of Mesa provided in Flatpak format can be very helpful for me.

**Comment by MavropaliasG** [comment] 2020-12-31 01:59
Hi, I wanted to share my output, as I just purchased Bloons TD 6, and I am trying to run it with Proton experimental and nothing happens. See attached info about my system, and the terminal output when I tried to run the game (twice) unsuccessfully.

Output
https://gist.github.com/MavropaliasG/363bb9fa4b6725c459aa98c6f2973754

My system
https://gist.github.com/MavropaliasG/0e680530e57495658aaf90d0f1677f92

@kisak-valve mentioned that this belongs here

**Comment by smcv** [comment] 2020-12-31 13:13
> Hi, I just want to say that Proton provided through Steam doesn't work with the Flatpak version of the client, but Proton Community Edition provided through Flatpak seems working.

This is the current state. There is no need to post comments or logs that confirm this: we are aware that this issue exists.

As several people have already said, the community builds of Proton can be used as a workaround. They are not supported by Valve, but neither is the Steam Flatpak app.

This issue will be updated when there is something available to test. Until then, there is no need to reply or comment. The eventual solution is likely to require updated versions of both Flatpak (I'm hoping to get the necessary code included in Flatpak 1.10) and the SteamLinuxRuntime_soldier depot.

**Comment by smcv** [comment] 2021-06-01 15:12
With the latest development versions of everything, it is possible to run games in the container runtime from within Flatpak (including official Valve releases of Proton 5.13 and 6.3, and the "Steam Linux Runtime" for native Linux games). At the moment this is still an "early adopters"-only feature.

You need:

* An operating system where unprivileged users can create user namespaces (non-setuid bubblewrap)
    * Debian >= 11 can work, Debian <= 10 won't
    * RHEL/CentOS >= 8 can work, RHEL/CentOS <= 7 won't
    * Arch Linux with the default `linux` kernel can work, Arch Linux with `linux-hardened` and `bubblewrap-suid` won't
    * Most other distributions can work (e.g. Ubuntu)
* Flatpak 1.11.1 or later. This is a development version, so use it at your own risk.
    * Ubuntu users can get this from [the PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak)
    * Debian users can get this from [experimental](https://packages.debian.org/source/experimental/flatpak)
    * Arch Linux users can find this in the default repositories
* A fully-up-to-date version of the Steam Flatpak app
    * It should list the `per-app-dev-shm` feature in its permissions
* For Proton games: [Steam Linux Runtime - soldier](https://steamdb.info/app/1391110/depots/) version 0.20210415.0 or later
    * All supported versions should meet this requirement by now
    * Check `steamapps/common/SteamLinuxRuntime_soldier/VERSIONS.txt` to see which version you have
* For native Linux games with "Steam Linux Runtime": [Steam Linux Runtime](https://steamdb.info/app/1070560/depots/) version 0.20210415.0 or later
    * All supported versions should meet this requirement by now
    * Check `steamapps/common/SteamLinuxRuntime/VERSIONS.txt` to see which version you have

Known issue: flatpak/flatpak#4286 can result in games failing to launch (it's intermittent). Re-launching the same game will usually succeed. This has been fixed in Flatpak git master, and the fix should be in 1.11.2 (not yet released).

If you are sure that you have all the requirements, and it still isn't working, please report [a new issue](https://github.com/ValveSoftware/steam-runtime/issues). Please be as specific as possible and make sure to include [all the required information](https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information).

If you do not have *all* of the requirements above, then this will not work. Please don't report that as a bug.

**Comment by hpfr** [comment] 2021-12-15 19:29
I believe this can be closed due to smcv's much-appreciated work on Flatpak 1.12.

**Comment by kaimast** [comment] 2021-12-15 19:38
Yes, this has been fixed for a while now as far as I can tell.

**Comment by cold-distance** [comment] 2021-12-15 19:44
Now I'm focused on native games for Linux, but I'm using Fedora Silverblue and I did two gameplays with Proton took from the Steam client. Both worked fantastic but they are old games (Dead Space and Doom 2016).

**Comment by smcv** [comment] 2021-12-15 20:09
> I believe this can be closed due to smcv's much-appreciated work on Flatpak 1.12.

To confirm, yes, Flatpak 1.12.x is the first stable branch that fixes this. You want at least 1.12.1 for some regression fixes (but the latest 1.12.x, currently 1.12.2, is better). Debian 11 users can get this from `bullseye-backports`, and Ubuntu users can get this from [the Flatpak PPA](https://launchpad.net/~flatpak/+archive/ubuntu/stable/) (if all goes well, Ubuntu 22.04 should come with a suitable version in the base distro).

As mentioned in my previous comment, you need an OS with [unprivileged bubblewrap](https://github.com/flatpak/flatpak/wiki/User-namespace-requirements#unprivileged-bubblewrap). I believe the latest versions of all major distros meet this requirement, with one notable exception: Arch Linux's non-default `linux-hardened` kernel.

All the other requirements mentioned in my previous comment should be easy to get now.

**Comment by kisak-valve** [comment] 2022-01-21 20:25
Closing per the last comment.

**Closed by kisak-valve** 2022-01-21 20:25 UTC
Labels: Need Retest, Pressure Vessel
