### ISSUE TITLE
Steam Linux Runtime in Flatpak 1.11.1 subsandbox not finding Xwayland DISPLAY on Gentoo

### ISSUE THREAD

**Issue by exeqtion** [ValveSoftware/steam-runtime#447] opened 2021-08-14 17:06 UTC
#### Your system information

* Steam Runtime Version: `steam-runtime_0.20210630.0`
* Distribution : `Gentoo`
* [Link to your full system information in a gist](https://gist.github.com/exeqtion/4d381e4a6ead968bad22e02f02208296)
* Have you checked for system updates?: `Yes`
* What compatibility tool are you using?: `Proton 5.13+`
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in SteamLinuxRuntime_soldier/VERSIONS.txt?
```
#Name   Version         Runtime Runtime_Version Comment
depot   0.20210723.18                   # Overall version number
pressure-vessel 0.20210722.0
scripts v0.20210722.0-0-gb142f90                        # Entry point scripts, etc.
soldier 0.20210719.0    soldier 0.20210719.0    # soldier_platform_0.20210719.0/ 
```

#### Please describe your issue in as much detail as possible:
I am using distribution kernel `5.13.10-gentoo-dist` with namespace config turned on (default options, nothing changed). I also compiled bubblewrap using `-suid` USE flag (installing as non-setuid), and I am on flatpak 1.11.1 with stable steam client. I tried multiple games with proton, proton experimental and proton-ge and nothing works. Native games works and of course games using proton 5.0 also.

#### If you are using Proton or the Steam Linux Runtime compatibility tool, please provide the information requested here:
[steam-524220-proton.log](https://github.com/ValveSoftware/steam-runtime/files/6986834/steam-524220-proton.log)
[slr-app524220-proton.log](https://github.com/ValveSoftware/steam-runtime/files/6986835/slr-app524220-proton.log)

#### Steps for reproducing this issue:

1. Open steam.
2. Enable steam play/proton.
3. Launch the game via steam play/proton.

**Comment by kisak-valve** [comment] 2021-08-14 17:13
Looks like this is an Xwayland issue of some kind. Since there's no X server available for wine to connect to, the graphic stack is falling over with `err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.`
`err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.` in the Proton log.

**Comment by exeqtion** [comment] 2021-08-14 18:26
Yeah, I just ran the game via awesomewm, and it ran without any issues.

**Comment by smcv** [comment] 2021-08-17 12:31
> I am on flatpak 1.11.1

I would recommend Flatpak 1.11.2. That version has some improvements that are relevant to pressure-vessel, and only the newest version from any particular branch of Flatpak has any expectation of support.

**Comment by smcv** [comment] 2021-08-17 13:01
> Looks like this is an Xwayland issue of some kind (inside of Steam Linux Runtime - Soldier)

It would be useful to trace further into this. When I did the development of the necessary Flatpak 1.11+ features, I was using GNOME in Wayland mode on Debian 11 as my main test environment, so it is definitely possible to run Steam and Proton 5.13+ under Flatpak in a Wayland/Xwayland environment. However, there is presumably at least one important difference between your environment and mine.

What desktop environment are you using? From the Steam system info, it looks like some wlroots-based Wayland compositor (sway or similar). `DISPLAY` is correctly set in the plain Flatpak environment, so presumably your desktop environment is also providing an Xwayland instance so that X11-only programs like Steam can work as intended.

However, when we go from the ordinary Flatpak runtime to the soldier subsandbox, you've lost your `DISPLAY` environment variable (we can see this in `driver_environment` in the system info dump), so X11 is not working.

I'm surprised by this, because Flatpak should be using the same setup code for `DISPLAY` and the X11 socket when it sets up the main Steam app, and when it sets up the soldier subsandbox: so if it works for Steam, it should work for soldier.

There are a couple of things you could try to get more information. For best results, do the two at the same time, so that `flatpak-portal` output and the pressure-vessel log come from the same attempt to launch a game.

1. Run Steam with `STEAM_LINUX_RUNTIME_VERBOSE=1` and `STEAM_LINUX_RUNTIME_LOG=1` in the environment, then try launching a game in the container environment (Proton 5.13+ or Steam Linux Runtime). You will get a larger `slr-app*.log` with more detail about what is happening.

2. Re-run `flatpak-portal` with a command like `G_MESSAGES_DEBUG=all /usr/libexec/flatpak-portal --replace --verbose` (if Gentoo installs it somewhere other than `/usr/libexec`, adjust the path accordingly), then try launching a game in the container environment. `flatpak-portal` will produce a lot of output, some of which will hopefully help us to see what is happening.

To limit the number of variables involved, it is probably best if you do this test by configuring a small, free-to-play native Linux game under the **Steam Linux Runtime** compatibility tool - that means we don't have to think about Proton and can concentrate on what is happening to the container runtime, and it means everyone interested in this issue report can easily be testing the same game. We often use [Floating Point](https://store.steampowered.com/app/302380/Floating_Point/) as our example of a small game that anyone can install.

> Yeah, I just ran the game via awesomewm, and it ran without any issues.

I'm not familiar with awesomewm. Is that an X11-only window manager, running under Xorg? Did you do everything else the same for this test, for example using Flatpak to run Steam, and running your game under Proton 5.13+?

**Comment by exeqtion** [comment] 2021-08-18 07:40
@smcv Hi, thanks for helping! 
>I would recommend Flatpak 1.11.2. That version has some improvements that are relevant to pressure-vessel, and only the newest version from any particular branch of Flatpak has any expectation of support.

Unfortunately, 1.11.2 is not yet available in gentoo's repos or in any overlay. Also, it does not have -9999 live ebuild.

>What desktop environment are you using? From the Steam system info, it looks like some wlroots-based Wayland compositor (sway or similar).

Yes, you are right, I am using sway. My bad, I forgot to add that in my post.

>I'm not familiar with awesomewm. Is that an X11-only window manager, running under Xorg? Did you do everything else the same for this test, for example using Flatpak to run Steam, and running your game under Proton 5.13+?

Yes, it is X11-only wm. And I kept everything the same. After kisak-valve replied, I did a quick install and check to see if it works under pure X11 environment or not.

Finally, I did the tests as you suggested, I downloaded the game you mentioned and ran it under Steam Linux Runtime compatibility tool. When I ran it as expected, it did not run. But when I re-ran it with flatpak-portal command `G_MESSAGES_DEBUG=all /usr/libexec/flatpak-portal --replace --verbose`, the game launched, and I was able to play it without any issue. So I did the same with proton games, and they started running without any issues. Just to be clear, first I launched the steam and then ran that command in a terminal after then ran the game. So yeah, everything started working after I reran the flatpak-portal.

Floating Point Logs:
[slr.log](https://github.com/ValveSoftware/steam-runtime/files/7005330/slr-app-floating.log)
[slr.log re-ran with flatpak-portal command](https://github.com/ValveSoftware/steam-runtime/files/7005329/slr-app-floating-flatpak-portal.log)
[output of flatpak-portal command](https://github.com/ValveSoftware/steam-runtime/files/7005331/floating-flatpak-portal.log)

Nier Automata Logs:
[slr.log](https://github.com/ValveSoftware/steam-runtime/files/7005321/slr-app-nier.log)
[slr.log re-ran with flatpak-portal command](https://github.com/ValveSoftware/steam-runtime/files/7005320/slr-app-nier-flatpak-portal.log)
[output of flatpak-portal command](https://github.com/ValveSoftware/steam-runtime/files/7005322/nier-flatpak-portal.log)

**Comment by smcv** [comment] 2021-08-18 10:14
> Unfortunately, 1.11.2 is not yet available in gentoo's repos or in any overlay.

Please report that to Gentoo as a bug. If distributions are going to package the 1.11.x development branch of Flatpak, then they should make sure to ship the newest release from that branch.

**Comment by smcv** [comment] 2021-08-18 10:20
> But when I re-ran it with flatpak-portal command G_MESSAGES_DEBUG=all /usr/libexec/flatpak-portal --replace --verbose, the game launched, and I was able to play it without any issue.

OK, this is a bit weird. Maybe you had an outdated version of `flatpak-portal` still running, left over from before you upgraded it?

Please restart your Wayland session completely (the easiest way to make sure everything has restarted is to reboot), and then try to launch one of these games in Proton 5.13+ from within Flatpak, without any special workarounds. I hope it will work successfully.

**Comment by smcv** [comment] 2021-08-18 10:21
Another way you can make sure `flatpak-portal` has restarted is: if you are using `systemd --user`, run `systemctl --user restart flatpak-portal.service`; or if not, kill the `flatpak-portal` process so that D-Bus activation will restart it the next time it's used.

**Comment by exeqtion** [comment] 2021-08-21 13:14
Hi, sorry for the late reply.
>Please report that to Gentoo as a bug. If distributions are going to package the 1.11.x development branch of Flatpak, then they should make sure to ship the newest release from that branch.

I created the version bump request. 

I do restart my pc daily, Just to be sure I uninstalled flatpak, made sure it removes /usr/libexec/flatpak-portal also. Then I also removed the installation files that used to install flatpak. After that, I restarted my system and installed the flatpak again. I checked in htop that flatpak-portal is not running before I launch any flatpak app. And then I launched steam, but the problem remained the same. Unless I run `/usr/libexec/flatpak-portal` in terminal before I launch the steam or replace it (kill and launch again or launch with `--replace` argument) then game runs.

**Comment by smcv** [comment] 2021-08-21 16:14
Oh, I think I might see what's happened here. Is the `dbus-daemon` being launched before Xwayland is up, or otherwise not getting the `DISPLAY` environment variable sent to it? And then `flatpak-portal` inherits the environment of the `dbus-daemon`, including the absence of a `DISPLAY` environment variable?

(You can check this with something like: `perl -pe 's/\0/\n/g' < /proc/$(pgrep flatpak-portal | head -n1)/environ`)

If so, this is a system integration issue, which is really outside the scope of either Flatpak or Steam. In a less DIY Linux distribution or desktop environment, I would have expected the desktop environment or the distribution's dbus and/or desktop environment packaging to solve it for you, but if you're putting together your own GUI session based on sway then it might be up to you to solve this.

The key thing is to send the `DISPLAY` environment variable to the `dbus-daemon` when it becomes available, for example with `dbus-update-activation-environment DISPLAY=...` (or as a shortcut, you can use `dbus-update-activation-environment DISPLAY` which is almost equivalent to `dbus-update-activation-environment DISPLAY="$DISPLAY"`), or by calling the underlying `UpdateActivationEnvironment` method [like GNOME does](https://gitlab.gnome.org/GNOME/gnome-session/-/blob/40.0/gnome-session/gsm-util.c#L590).

**Comment by exeqtion** [comment] 2021-08-31 14:28
Sorry, for the late reply again. Yeah, adding `exec hash dbus-update-activation-environment 1>/dev/null && dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK` in sway config fixed the issue, I also discovered this is also mentioned in [sway wiki](https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start). So I don't think it is related to gentoo but sway, actually. I think we can close this issue now. Thanks for helping me!

**Comment by kisak-valve** [comment] 2021-08-31 14:57
Closing per the last comment.

**Closed by kisak-valve** 2021-08-31 14:57 UTC
Labels: Pressure Vessel
