### ISSUE TITLE
latest lib pinning ignores system LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/steam-runtime#177] opened 2019-09-18 15:23 UTC

**Comment by sylware** [comment] 2019-09-18 15:25
It seems the new setup.bash/sh which does lib pinning does only consider the output of /sbin/ldconfig which seems to ignore the user/system LD_LIBRARY_PATH

**Comment by kisak-valve** [comment] 2019-09-18 15:41
Hello @sylware, this is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5455. If you want that issue tracked over here, let me know and I'll transfer it over. There's no value in fragmenting the discussion.

Closing as a duplicate.

**Closed by kisak-valve** 2019-09-18 15:41 UTC
