### ISSUE TITLE
Stack smashing detected with ANV in Steam Linux Runtime - Soldier

### ISSUE THREAD

**Issue by JaydeepGo** [ValveSoftware/steam-runtime#341] opened 2020-12-23 15:34 UTC
System information
  
* Steam Runtime Version:  steam-runtime_0.20201203.1
* Distribution : Manjaro 
* Link to your full system information : [System info](https://gist.github.com/JaydeepGo/3e1f922dba3f1e5235a553cfbef5b068) 
* Have you checked for system updates?: Yes
* Are you using the Steam Linux Runtime compatibility tool?: [Yes/No] Yes
* [pressure-vessel log](https://gist.github.com/JaydeepGo/eb1f19e9622ce4c33de487e83117f96b)

I have tested all proton version with game Temtem. It was working properly with proton 5.13 but it stops working yesterday. I  even tried with the latest version of Steam Linux Runtime Soldier (client_beta).

**Comment by kisak-valve** [comment] 2020-12-23 15:45
Hello @JaydeepGo, I took a look at your system information and pressure vessel log and I don't see a fatal issue with the runtime container. This should be investigated on Proton's side.

Please add a comment to https://github.com/ValveSoftware/Proton/issues/3441 with the issue you're seeing. Make sure to note the last known working Proton version, and the current version. Also, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options and attach the generated $HOME/steam-$APPID.log to that issue report as a file. (Proton logs compress well if needed.)

**Comment by kisak-valve** [comment] 2020-12-23 15:50
And just after I wrote that I just noticed:
```
messages" : "*** stack smashing detected ***: terminated
timeout: the monitored command dumped core",
```
With 64 bit vulkan in the container. Not sure what to make of this, but it's worth holding this issue open to focus on that.

**Comment by smcv** [comment] 2021-01-04 19:39
I think we'd need a backtrace from the crashing `vulkaninfo` command to get anywhere with this.

**Comment by smcv** [comment] 2021-01-05 12:30
It looks like Vulkan is working fine in the scout container runtime, but 64-bit vulkaninfo is crashing in the soldier container runtime, which is interesting. I wonder whether we're misdetecting some library as newer in the soldier runtime when it's actually older?

**Comment by JaydeepGo** [comment] 2021-01-08 13:58
Hi @smcv @kisak-valve, Is there anything where I can help?

**Comment by smcv** [comment] 2021-01-08 14:15
Is this a multi-GPU system, or is your only GPU the Intel integrated GPU?

If you're able to get a stack trace from the crashing `vulkaninfo` command, perhaps by using `systemd-coredump`, that might help to figure out what is going on. For example see https://wiki.archlinux.org/index.php/Core_dump#Examining_a_core_dump

**Comment by JaydeepGo** [comment] 2021-01-08 19:21
Hi @smcv, This is a multi-GPU system (AMD+Intel hybrid). 
The `vulkaninfo` works fine outside of the container. For crashing `vulkaninfo` logs are available in repo.
Please find all logs in [debug-dump repo](https://github.com/JaydeepGo/debug-dump).

**Comment by smcv** [comment] 2021-01-09 00:02
> This is a multi-GPU system (AMD+Intel hybrid)

There's a known bug causing the Mesa device selection layer not to be loaded correctly inside the container. Presumably you were intending to be using the AMD GPU for games? The next beta of the Steam Linux Runtime will fix loading of the Mesa device selection layer, which should make it more likely that things like DKVK will get run on your AMD GPU as intended.

Workaround: try running Steam with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json` in the environment, so the Intel Vulkan driver doesn't get loaded. At the moment, you need to have this set during Steam startup: setting it in Launch Options is too late.

**Comment by JaydeepGo** [comment] 2021-01-10 09:55
Thanks @smcv, This prefix works. So after this prefix, all native steam game will also use AMD GPU?

**Comment by smcv** [comment] 2021-01-10 18:00
`VK_ICD_FILENAMES` will affect native Linux Steam games that use Vulkan, and Proton games that use DXVK. It won't affect games that use OpenGL.

**Comment by smcv** [comment] 2021-01-19 19:51
> The next beta of the Steam Linux Runtime will fix loading of the Mesa device selection layer, which should make it more likely that things like DKVK will get run on your AMD GPU as intended

This has now been released as a beta. Switching to the beta branch is the same as switching to the beta branch of a game, so please follow the same procedure as https://support.steampowered.com/kb_article.php?ref=9847-WHXC-7326, but in the properties of *Steam Linux Runtime - soldier* rather than CS:GO. You can see which specific versions you're using in `SteamLinuxRuntime_soldier/VERSIONS.txt`.

For the issue I'm thinking of, the fix is in the `pressure-vessel` component, and you want version 0.20210114.0 or later.

If you do that, and stop using the `VK_ICD_FILENAMES` workaround, does it convince DXVK to use your AMD GPU?

If this doesn't help, please capture a new pressure-vessel log and new steam-runtime-system-info details. We've added an easier way to get a pressure-vessel log since you opened this bug: see <https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information>.

**Comment by JaydeepGo** [comment] 2021-01-21 20:33
Hi @smcv, I have updated the

**Comment by JaydeepGo** [comment] 2021-04-11 16:59
Hi @smcv, The Workaround: try running Steam with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json` in the environment, so the Intel Vulkan driver doesn't get loaded, is not working anymore. 

<details>
<summary> Steam terminal log</summary>

```
[leader@manjaro ~]$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json steam 
Running Steam on manjarolinux 21.0.1 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/leader/.local/share/Steam/ubuntu12_32/steam
[2021-04-11 22:15:19] Startup - updater built Mar 23 2021 20:11:00
Installing breakpad exception handler for appid(steam)/version(1616532526)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2021-04-11 22:15:19] Loading cached metrics from disk (/home/leader/.local/share/Steam/package/steam_client_metrics.bin)
[2021-04-11 22:15:19] Using the following download hosts for Public, Realm steamglobal
[2021-04-11 22:15:19] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-04-11 22:15:19] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-04-11 22:15:19] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1616532526)
[2021-04-11 22:15:19] Checking for update on startup
[2021-04-11 22:15:19] Checking for available updates...
[2021-04-11 22:15:19] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
Installing breakpad exception handler for appid(steam)/version(1616532526)
[2021-04-11 22:15:20] Download skipped: /client/steam_client_ubuntu12 version 1616532526, installed version 1616532526, existing pending version 0
[2021-04-11 22:15:20] Nothing to do
[2021-04-11 22:15:20] Verifying installation...
[2021-04-11 22:15:20] Performing checksum verification of executable files
[2021-04-11 22:15:24] Verification complete
Loaded SDL version 2.0.15-6379350
/usr/share/themes/Breath/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:19506): Gtk-WARNING **: 22:15:25.009: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breath/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
Installing breakpad exception handler for appid(steam)/version(1616532526)
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
[0411/221526.070780:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: browser
[0411/221526.105523:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0411/221526.105601:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1616530283
[0411/221526.105612:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0411/221526.105623:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0411/221526.167985:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0411/221526.168064:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1616530283
[0411/221526.168077:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0411/221526.168086:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0411/221526.168797:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
[0411/221526.331233:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
[0411/221526.385003:WARNING:crash_reporting.cc(286)] Failed to set crash key: UserID with value: 0
[0411/221526.385089:WARNING:crash_reporting.cc(286)] Failed to set crash key: BuildID with value: 1616530283
[0411/221526.385107:WARNING:crash_reporting.cc(286)] Failed to set crash key: SteamUniverse with value: Public
[0411/221526.385119:WARNING:crash_reporting.cc(286)] Failed to set crash key: Vendor with value: Valve
[0411/221526.385931:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: utility
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
CAppInfoCacheReadFromDiskThread took 220 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
CApplicationManagerPopulateThread took 4537 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Proceed to auto login
Opted-in Controller Mask for AppId 0: 2
Installing breakpad exception handler for appid(steam)/version(1616532526)

(steam:19506): Gtk-WARNING **: 22:15:31.744: gtk_disable_setlocale() must be called before gtk_init()

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.752: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.753: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.753: Trying to remove a child that doesn't believe we're it's parent.

(steam:19506): LIBDBUSMENU-GLIB-WARNING **: 22:15:31.753: Trying to remove a child that doesn't believe we're it's parent.
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
vkEnumeratePhysicalDevices failed, unable to init and enumerate GPUs with Vulkan.
BInit - Unable to initialize Vulkan!
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
roaming config store loaded successfully - 33198 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 24ms
[0411/221536.721876:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1616532526)
[0411/221536.876818:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0411/221536.987741:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1616532526)
Failed to init SteamVR because it isn't installed
ExecCommandLine: "'/home/leader/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 13.41 seconds
[0411/221538.366331:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0411/221538.371788:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
[0411/221538.410345:INFO:crash_reporting.cc(270)] Crash reporting enabled for process: renderer
Installing breakpad exception handler for appid(steam)/version(1616532526)
BuildCompleteAppOverviewChange: 419
RegisterForAppOverview 1: 138ms
RegisterForAppOverview 2: 139ms
Installing breakpad exception handler for appid(steam)/version(1616532526)
Installing breakpad exception handler for appid(steam)/version(1616532526)
[730]Non-Steam Controller Configs Enabled: 0
Installing breakpad exception handler for appid(steam)/version(1616532526)
[570]Non-Steam Controller Configs Enabled: 1
[745920]Non-Steam Controller Configs Enabled: 1
[652720]Non-Steam Controller Configs Enabled: 1
CAPIJobRequestUserStats - Server response failed 2
CAPIJobRequestUserStats - Server response failed 2
Opted-in Controller Mask for AppId 745920: 7
GameAction [AppID 745920, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
[0411/221722.789219:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
^CTraceback (most recent call last):
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 977, in <module>
    path = subprocess.check_output([g_proton.wine_bin, "winepath", "-w", sys.argv[2]], env=g_session.env, stderr=g_session.log_file)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
Traceback (most recent call last):
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 969, in <module>
    g_session.run()
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 942, in run
    self.run_proc([g_proton.wine_bin, "steam"] + sys.argv[2:] + self.cmdlineappend)
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 934, in run_proc
    subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/usr/lib/python3.7/subprocess.py", line 325, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 474, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 926, in communicate
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
    stdout = self.stdout.read()
KeyboardInterrupt
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
^CTraceback (most recent call last):
Traceback (most recent call last):
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 969, in <module>
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 969, in <module>
    g_session.run()
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 942, in run
    g_session.run()
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 942, in run
    self.run_proc([g_proton.wine_bin, "steam"] + sys.argv[2:] + self.cmdlineappend)
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 934, in run_proc
    self.run_proc([g_proton.wine_bin, "steam"] + sys.argv[2:] + self.cmdlineappend)
  File "/home/leader/.local/share/Steam/steamapps/common/Proton 6.3/proton", line 934, in run_proc
    subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/usr/lib/python3.7/subprocess.py", line 325, in call
    subprocess.call(args, env=local_env, stderr=self.log_file, stdout=self.log_file)
  File "/usr/lib/python3.7/subprocess.py", line 325, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 745920
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 745920
Installing breakpad exception handler for appid(steam)/version(1616532526)
assert_20210411222012_30.dmp[20633]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210411222012_30.dmp
Installing breakpad exception handler for appid(steam)/version(1616532526)
assert_20210411222012_30.dmp[20633]: Finished uploading minidump (out-of-process): success = yes
assert_20210411222012_30.dmp[20633]: response: CrashID=bp-f146c594-7094-4746-80e5-48e2b2210411
assert_20210411222012_30.dmp[20633]: file ''/tmp/dumps/assert_20210411222012_30.dmp'', upload yes: ''CrashID=bp-f146c594-7094-4746-80e5-48e2b2210411''
```

</details>
If you require more info please do tell.

**Comment by smcv** [comment] 2021-04-11 21:46
Please get new debug info according to https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information, and attach it or upload it as a gist. Quite a lot has changed since you originally reported this, so we'll need new information to work out what is still not working.

**Comment by JaydeepGo** [comment] 2021-04-20 14:55
Hi @smcv 
Apologies for the late response. Please find the logs:
[System Info](https://github.com/JaydeepGo/debug-dump/blob/master/logs/system%20info)
[steam terminal](https://github.com/JaydeepGo/debug-dump/blob/master/logs/steam%20terminal)
[Coredump x86_64-linux-gnu-inspect-library & x86_64-linux-gnu-check-vulkan](https://github.com/JaydeepGo/debug-dump/blob/master/logs/Coredump%20log)
I can't find proton log in `/var`.

**Comment by kisak-valve** [comment] 2021-04-20 15:12
Looking at your updated system information, it looks like 64 bit Vulkan is outright broken now. Is there a particular reason why `amdvlk` was added, `vulkan-intel` was removed, and `nvidia-390xx` is on what appears to be an Intel-only system? I'm not asking for them to be changed, but tinkering with the installed drivers might give some insight.

**Comment by JaydeepGo** [comment] 2021-04-20 18:59
Hi @kisak-valve, Thanks to point out about `amdvlk` & `nvidia-390xx` I have removed these packages and installed `vulkan-intel`. 
> `64 bit Vulkan is outright broken now

I never notice these because I normal play Dota2 and CSGO. 
Here is the [Updated System Info ](https://github.com/JaydeepGo/debug-dump/blob/master/logs/system%20info%20updated).
Now the game is running without any tweaks, So good to close this bug.
I have small doubt have can I check which GPU game is using when running via proton. I like to run the game via AMD driver.

Thanks for fixing the bug.

**Closed** 2021-04-30 21:04 UTC
Labels: Pressure Vessel

**Comment by JaydeepGo** [comment] 2021-04-30 21:05
Hi @kisak-valve, 
Closing the issue as the bug is fixed.
