### ISSUE TITLE
Dota 2 not launching on Steam Runtime [Ubuntu 20.04 LTS]

### ISSUE THREAD

**Issue by hankhaichong** [ValveSoftware/steam-runtime#500] opened 2022-03-11 14:21 UTC
#### Your system information

* Steam Runtime Version: soldier_platform_0.20220131.0
* Distribution (e.g. Ubuntu 18.04): Ubuntu 20.04 LTS
* Link to your full system information (Help -> System Information): 
  <details>
  <summary>System Information</summary>

  **Computer Information:**
    Manufacturer:  Micro-Star International Co., Ltd
    Model:  B450 TOMAHAWK (MS-7C02)
    Form Factor: Desktop
    No Touch Input Detected
 **Processor Information:**
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 1700 Eight-Core Processor          
    CPU Family:  0x17
    CPU Model:  0x1
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3200 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported
**Operating System Version:**
    Ubuntu 20.04.3 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.13.0-35-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12013000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20220119.0
**Video Card:**
    Driver:  NVIDIA Corporation GeForce GTX 1080 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 390.144
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1b06
    Revision Not Detected
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 3926 x 1440
    Primary Display Size: 20.71" x 11.65" (23.74" diag)
                                            52.6cm x 29.6cm (60.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 11264 MB
    Supported MSAA Modes:  2x 4x 8x 16x 
**Sound card:**
    Audio device: Nvidia GPU 82 HDMI/DP
**Memory:**
    RAM:  32055 MB
**VR Hardware:**
    VR Headset: None detected
**Miscellaneous:**
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  467922 MB
    Largest Free Hard Disk Block:  351695 MB
**Storage:**
    Number of SSDs: 0
    Number of HDDs: 0

</details>

* Have you checked for system updates?: Yes
* What compatibility tool are you using?: Steam Linux Runtime
* If you are using Steam Linux Runtime for native Linux games: What versions are listed in `SteamLinuxRuntime/VERSIONS.txt`?
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`?
```
depot   0.20220131.43                   # Overall version number
pressure-vessel 0.20220131.0
scripts v0.20211029.0-0-g2d89be4                        # Entry point scripts, etc.
soldier 0.20220131.0    soldier 0.20220131.0    # soldier_platform_0.20220131.0/
```

#### Please describe your issue in as much detail as possible:
I have not been able to launch my Dota 2 game for a few weeks now. I initially thought it might be a patch issue and waited for new patches and hoped that it will be fixed. But it has been many patches now, so I believed it might not be a Valve issue. When I launch Dota 2 on steam, the Play Button turned into Cancel, which means it is trying to launch and soon it just goes back to the green Play button.

#### Steps for reproducing this issue:
1. Launch Steam.
2. Launch Dota 2.
3. Game does not launch at all.

Attached is the Steam Runtime log file generated when trying to launch Dota 2.
[slr-app570-t20220311T221738.log](https://github.com/ValveSoftware/steam-runtime/files/8232621/slr-app570-t20220311T221738.log)

**Comment by kisak-valve** [comment] 2022-03-11 14:34
Hello @hankhaichong, `*** stack smashing detected ***: terminated` in your log and the NVIDIA 390 series driver install makes this issue report a duplicate of #420. Please update your video driver.

**Closed by kisak-valve** 2022-03-11 14:34 UTC
