### ISSUE TITLE
Proton 5.13 crashes instantly regardless of game. 

### ISSUE THREAD

**Issue by bonkmaykrQ** [ValveSoftware/steam-runtime#298] opened 2020-11-05 00:33 UTC
Eversince Proton 5.13 came out, when I set it as my default Proton version it caused litterally all of my games to just quit working.

I tried everything I could, reinstalling Proton, reinstalling Steam, reinstalling my graphics driver, blah blah. And I made sure Python was up to date

It took me a very very long time to figure this out, but switching back to Proton 5.9 GE and rebooting solved all of my problems. 

This really disappoints me because I upgraded to 5.13 hearing that it added support for RDR2 and instead it just broke everything.

Here's my neofetch output for those who are interested:  https://bonkmaykrq.github.io/neofetch-inspiron-3670

Screen recording: https://cdn.discordapp.com/attachments/772897556300169256/773703661334560768/Peek_2020-11-04_15-13.gif

**Comment by kisak-valve** [comment] 2020-11-10 22:32
Thanks for retesting @bonkmaykrQ, I still think this is a duplicate of #286, but it's not clear why that is the case. Let's treat this as a Pressure Vessel issue until there's a stronger indication that the issue is elsewhere.

**Comment by lbibass** [comment] 2020-11-15 18:38
I'd just like to say that I am having the same problem here. libgtk3-noscd is not installed. Getting a ton of errors with 5.13, both 5.13.1 and 5.13.2. I installed steam through flatpak. 

`ln: failed to create symbolic link '/tmp/SteamPVSockets.BHxL9o/SteamLinuxRuntime.28015d6fcf15ff25/socket' -> '': No such file or directory
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_get_source_tag
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_task_data
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_get_source_tag
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_task_data
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
pressure-vessel-wrap[19193]: Cannot run flatpak-spawn: wait status 256
pressure-vessel-wrap[19193]: Diagnostic output:
Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown

ln: failed to create symbolic link '/tmp/SteamPVSockets.BHxL9o/SteamLinuxRuntime.28015d6fcf15ff25/socket' -> '': No such file or directory
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 945360
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 945360
GameAction [AppID 945360, ActionID 6] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 945360, ActionID 6] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 945360, ActionID 6] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 945360, ActionID 6] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 945360 "", ProcID 19206, IP 0.0.0.0:0
Starting app 945360
>>> Adding process 19206 for game ID 945360
GameAction [AppID 945360, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 945360, ActionID 6] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 19211 != 19207, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
_v2-entry-point[19207]: STEAM_COMPAT_APP_ID=945360
_v2-entry-point[19207]: STEAM_COMPAT_SESSION_ID=28015d6fcf15ff25
_v2-entry-point[19207]: XDG_RUNTIME_DIR=/run/user/1000
>>> Adding process 19207 for game ID 945360
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_get_source_tag
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_task_data
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 19208 for game ID 945360
>>> Adding process 19212 for game ID 945360
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_get_source_tag
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_task_data
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
pressure-vessel-wrap[19221]: Cannot run flatpak-spawn: wait status 256
pressure-vessel-wrap[19221]: Diagnostic output:
Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown

ln: failed to create symbolic link '/tmp/SteamPVSockets.BHxL9o/SteamLinuxRuntime.28015d6fcf15ff25/socket' -> '': No such file or directory
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_get_source_tag
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_task_data
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
>>> Adding process 19213 for game ID 945360
>>> Adding process 19214 for game ID 945360
ERROR: ld.so: object '/home/lbibass/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_new
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_get_source_tag
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_task_data
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
pressure-vessel-launch[19235]: Can't connect to peer socket: Could not connect: No such file or directory
>>> Adding process 19215 for game ID 945360
>>> Adding process 19234 for game ID 945360
>>> Adding process 19235 for game ID 945360
Game removed: AppID 945360 "", ProcID 19206 
Uploaded AppInterfaceStats to Steam
Exiting app 945360
No cached sticky mapping in ActivateActionSet.

`

**Comment by kisak-valve** [comment] 2020-11-15 18:40
Hello @lbibass, you've encountered #294 instead of this issue report.

**Comment by lbibass** [comment] 2020-11-15 23:12
> Hello @lbibass, you've encountered #294 instead of this issue report.

Yup, thank you! Sorry about that. Installing from apt instead of flatpak fixed the problems.

**Comment by bonkmaykrQ** [comment] 2020-11-19 05:00
Hello @kisak-valve.

While I was updating my sysinfo on ProtonDB, I noticed something:

```
"scout runtime container" is not installed.

"soldier runtime container" is not installed.
```

Could this have something to do with it? I have heard a lot about Proton 5.13 relying on the Runtime containers.

Interestingly, switching to version 5.21-GE (an unofficial fork of Proton), a version based off of 5.13, seems to run just fine.

**Comment by Antarctic-Ice-Shelf** [comment] 2020-11-20 00:10
Hi, I just wanted to remark that I think I had this same issue when I posted https://github.com/ValveSoftware/Proton/issues/4371 .

Your fix of installing Proton 5.9 GE and setting it as default and then rebooting my PC worked for me, and I have now gotten my games running again on that version of Proton. Thanks for that!

**Comment by bonkmaykrQ** [comment] 2020-11-20 00:17
> Hi, I just wanted to remark that I think I had this same issue when I posted [ValveSoftware/Proton#4371](https://github.com/ValveSoftware/Proton/issues/4371) .
> 
> Your fix of installing Proton 5.9 GE and setting it as default and then rebooting my PC worked for me, and I have now gotten my games running again on that version of Proton. Thanks for that!

Could you try using 5.21 GE now and see if it works? 5.9 GE is about a month old I think. 

While 5.13 vanilla is still not working for me, 5.21 GE seems to be working just fine and actually fixed a few performance issues I had with 5.9 GE.

What's strange about this is that, I'm sure 5.21 GE is based off of 5.13, so how it manages to work while 5.13 doesn't, is beyond me.

**Comment by Antarctic-Ice-Shelf** [comment] 2020-11-20 01:19
> > Hi, I just wanted to remark that I think I had this same issue when I posted [ValveSoftware/Proton#4371](https://github.com/ValveSoftware/Proton/issues/4371) .
> > Your fix of installing Proton 5.9 GE and setting it as default and then rebooting my PC worked for me, and I have now gotten my games running again on that version of Proton. Thanks for that!
> 
> Could you try using 5.21 GE now and see if it works? 5.9 GE is about a month old I think.
> 
> While 5.13 vanilla is still not working for me, 5.21 GE seems to be working just fine and actually fixed a few performance issues I had with 5.9 GE.
> 
> What's strange about this is that, I'm sure 5.21 GE is based off of 5.13, so how it manages to work while 5.13 doesn't, is beyond me.

Sorry, I would like to help with this, but I use Manjaro, and when I tried installing the AUR package "proton-ge-custom" (1:5.21.GE.1-2) it broke my Steam in a way unrelated to the issue in this thread. The installation went on for about an hour, after which I cancelled it, and now the Steam settings menu is broken in a weird way where I can't select Proton GE as the default. I will see if I can fix it by deleting my steam folders. In future I think I will stick to the stable branch of Proton GE.

**Comment by bonkmaykrQ** [comment] 2020-11-20 04:34
You're not supposed to install GE from the package manager, as far as I'm aware.

**Comment by bonkmaykrQ** [comment] 2020-11-20 20:41
Hello, @kisak-valve, what are your thoughts?

**Comment by bonkmaykrQ** [comment] 2020-12-02 00:34
@kisak-valve, I'd like to report that my issues with Proton 5.13 starting up have been fixed after the -2 revision, however Origin games do not start as promised in 5.0.

**Comment by kisak-valve** [comment] 2020-12-02 00:48
Glad to hear that it started working for you. It would have been nice to find out what made the difference, but it's not strictly necessary.

Proton 5.13 is the first release to run on top of Steam Linux Runtime - Soldier. Issues with older Proton releases are unrelated to the issue reported here. Please give feedback on those games on their compatibility report in the Proton issue tracker. It wouldn't be surprising if Origin has changed over time and now uses something that Proton 5.0 does not provide.

Since it's now working for you, there's no longer a test case to ponder here, closing.

**Closed by kisak-valve** 2020-12-02 00:48 UTC
Labels: Pressure Vessel
