### ISSUE TITLE
Ubuntu vulkan-validationlayers package causes Proton games to fail to start. Uninstalling fixes it.

### ISSUE THREAD

**Issue by GavinNL** [ValveSoftware/steam-runtime#325] opened 2020-12-12 17:37 UTC
#### Your system information

* Steam client version (build number or date):  Dec 7 2020, at 18:04:33. Steam API: v020
* Distribution (e.g. Ubuntu): Linux Mint 20 (Ubuntu 20.04)
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes
* nvidia-driver-455

#### Please describe your issue in as much detail as possible:

After much trial and error, and a few system-restores and full OS re-installations. I found that the `vulkan-validationlayers` package from the Linux Mint 20 repo (Probably Ubuntu 20.04 as well) is causing Proton games to fail to start.

This is the current version in the ubuntu repo.
```
vulkan-validationlayers:
  Installed: (none)
  Candidate: 1.2.131.2-1
  Version table:
     1.2.131.2-1 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages

```

I tested this with Proton 5.13-4 as well as Proton Experimental, and both of them do the same thing. **Removing the package fixes the issue**.

#### Steps for reproducing this issue:

I tested this with Gunfire Reborn and Among Us. Both do the same thing.

0. sudo apt update && sudo apt upgrade
1. Install Steam and a Proton game 
2. Run Gunfire Reborn (starts successfully).
3. install `sudo apt install vulkan-validationlayers`
3. Run Gunfire Reborn (fails to start)
4. `sudo apt purge vulkan-validationlayers`
4. Run Gunfire Reborn (starts successfully)

I ran the following with and without the `vulkan-validationlayers` package
```
cd ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier 
PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info --verbose 2>&1 | tee container.log
```

The output along with my system information is below:
https://gist.github.com/GavinNL/6c6df022bd7ce0f561a5d46eb8995864

**Comment by kisak-valve** [comment] 2020-12-12 17:44
Hello @GavinNL, let's treat this as a Pressure Vessel issue until there's a stronger indicator the issue is elsewhere.

---
Please could you show us a log of what pressure-vessel is thinking, and exactly what happens? You can do this without involving Proton (which should make things a bit simpler) like this:

`
cd /path/to/SteamLinuxRuntime_soldier
PRESSURE_VESSEL_VERBOSE=1 ./run -- steam-runtime-system-info --verbose 2>&1 | tee container.log
`

and then send container.log as a gist. You can edit/censor the log if there's anything in it that you consider private, as long as it's obvious where it has been edited, for instance replacing your username with REDACTED.

The SteamLinuxRuntime_soldier directory will be in one of your Steam libraries. The most likely place is ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier if you haven't reconfigured the installation path.

Also please show us the full system information (Help -> System Information in Steam), after waiting for the diagnostic tools to finish thinking about what drivers you have. Again, you can edit/censor it if you need to, and please send it as a gist.

(from https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-741037038)

**Comment by GavinNL** [comment] 2020-12-12 18:02
Hi @kisak-valve , I edited the issue and included the information you requested.

**Comment by kisak-valve** [comment] 2020-12-12 18:11
Pressure Vessel fails with `pressure-vessel:ERROR:../pressure-vessel/runtime.c:2441:collect_vulkan_layers: assertion failed: (details->resolved_library != NULL)` which points towards #306.

**Comment by GavinNL** [comment] 2020-12-12 18:28
I opted into the beta update in the steam settings. I am getting the same behaviour. Games start successfully if i do not have `vulkan-validationlayers` installed, and and fail to start if it is installed.

**Comment by GavinNL** [comment] 2020-12-12 18:35
Oh wait, I think i opted into the wrong beta. I opted into the beta for Steam Linux Runtime - Soldier. And the games **do start** with and without the `vulkan-validationlayer`

**Comment by kisak-valve** [comment] 2020-12-12 18:38
Thanks for retesting, closing as a duplicate of #306.

**Closed by kisak-valve** 2020-12-12 18:38 UTC
Labels: Pressure Vessel
