### ISSUE TITLE
Proton 5.13 has borked NVIDIA prime offloading

### ISSUE THREAD

**Issue by Alex-Bujorianu** [ValveSoftware/steam-runtime#377] opened 2021-03-08 19:40 UTC
Dear Valve developers,

The latest version of Proton (5.13-6) does not work with NVIDIA prime offloading using driver version 460.39 and kernel 5.8.0-44-generic on an up-to-date install of Ubuntu 20.04 LTS. I tested Swords & Souls and had to revert to Proton 5.0 to get it to run smoothly. Is this possibly related to Soldier?

Additionally, you might want to test the game itself as it seems to have trouble running on Intel graphics under Proton. It’s not a very demanding game, so there might be some problems with the Intel graphics driver or Proton itself. (I will ask the developer about this.)

**Comment by kisak-valve** [comment] 2021-03-08 19:46
Hello @Alex-Bujorianu, let's treat this as a Steam Linux Runtime - Soldier issue until there's a stronger indication the issue is elsewhere. Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and attach a Steam Linux Runtime log along with your system information from Steam as a file or in a [gist](https://gist.github.com).

**Comment by Alex-Bujorianu** [comment] 2021-03-08 20:03
> Hello @Alex-Bujorianu, let's treat this as a Steam Linux Runtime - Soldier issue until there's a stronger indication the issue is elsewhere. Please give https://github.com/ValveSoftware/steam-runtime/blob/master/doc/reporting-steamlinuxruntime-bugs.md#essential-information a read and attach a Steam Linux Runtime log along with your system information from Steam as a file or in a [gist](https://gist.github.com).
> 
> Also, it may be worthwhile to take a look at #312 and see if you have the same behavior as discussed in that issue report.

Here is a copy of the log file:
[slr-app679900-saaec894d29f782d6.log](https://github.com/ValveSoftware/steam-runtime/files/6103830/slr-app679900-saaec894d29f782d6.log)

Gist of system info: https://gist.github.com/Alex-Bujorianu/d02392a5378dbe057b2a4df8dbce9630

**Comment by kisak-valve** [comment] 2021-03-08 20:14
I suspect that your system would be affected by #303. Can you opt into Steam's client beta and the beta branch of Steam Linux Runtime - Soldier (Steam library -> search for `Steam Linux Runtime - Soldier` -> right click on it in the sidebar (or click the gear icon on the right side) -> Properties -> Betas -> pick `client_beta` from the dropdown.

If that doesn't help, then please check if the system information from Steam gathered more information to ponder instead of ending in `CClientJobGatherRuntimeInformation: container read output failed` and share an updated gist.

**Comment by Alex-Bujorianu** [comment] 2021-03-08 20:31
> I suspect that your system would be affected by #303. Can you opt into Steam's client beta and the beta branch of Steam Linux Runtime - Soldier (Steam library -> search for `Steam Linux Runtime - Soldier` -> right click on it in the sidebar (or click the gear icon on the right side) -> Properties -> Betas -> pick `client_beta` from the dropdown).
> 

I will opt in to the beta and see if that fixes the issue. 

You referenced #303 but that seems to be a MangoHud specific issue (I am not using MangoHud). Issue #312 seems more related to my problem—my game does work, but with Proton 5.13 I can’t get it to run on the NVIDIA card even with __NV_PRIME_RENDER_OFFLOAD=1 %command% (it offloads fine with Proton 5.0)

**Comment by kisak-valve** [comment] 2021-03-08 20:43
You can give `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only %command%` a try in the game's launch options, or failing that the workaround at https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559 might be worth a try.

**Comment by Alex-Bujorianu** [comment] 2021-03-08 20:58
> You can give `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only %command%` a try in the game's launch options, or failing that the workaround at [#312 (comment)](https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559) might be worth a try.

Bingo! `__VK_LAYER_NV_optimus=NVIDIA_only` does the trick. The game now offloads to the NVIDIA card using Proton 5.13

**Comment by kisak-valve** [comment] 2021-03-08 21:01
Thanks, I think that #312 covers this topic fairly thoroughly. Closing as a duplicate.

**Closed by kisak-valve** 2021-03-08 21:01 UTC
Labels: Pressure Vessel
