### ISSUE TITLE
Witcher 3 fail to launch proton 6.3-6

### ISSUE THREAD

**Issue by witcherenjoyer** [ValveSoftware/steam-runtime#464] opened 2021-09-17 20:54 UTC
Hello. Please bear with me as I try to report this correctly. I am brand new to gaming on linux. 

#### Your system information

* Steam Runtime Version: 0.20210818.24
* Distribution: opensuse leap 15.3
* full system information: https://gist.github.com/witcherenjoyer/c7cf45252a8e8b367c0c800a1e3fde1f
* Have you checked for system updates?: [**Yes**/No]
* What compatibility tool are you using?: [None / Steam Linux Runtime / **Proton 5.13+** / older Proton]
* If you are using Steam Linux Runtime, or Proton 5.13 or newer: What versions are listed in `SteamLinuxRuntime_soldier/VERSIONS.txt`? : https://gist.github.com/witcherenjoyer/fb65f4f4d3d4f4074c83b2309b106a66

#### Please describe your issue in as much detail as possible:
Proton worked very well with DOOM and Witcher 1, Witcher 2, and other games. But now with Witcher 3 the game fails to launch. Ive tried the fix at https://github.com/ValveSoftware/steam-runtime/issues/312#issuecomment-739441559 and it did not work. I have tried a bunch of different things now and i haven't seen any change in behavior at all. I'm not sure where to even begin troubleshooting, as I looked at some of the logs and couldn't make out much of what I was reading. I am including the two logs below (as I believe I am supposed to) and hope you can make out a solution better than I can. Any other output or logs that would be helpful let me know. 

https://gist.github.com/witcherenjoyer/8f5e7c64b76bc2e3597d7a8edfbace91
https://gist.github.com/witcherenjoyer/d4802e2a6c08495275b13e786df88988

#### Steps for reproducing this issue:

1. Launch witcher 3 (maybe with top running) and watch it spin for a bit then die.

**Comment by kisak-valve** [comment] 2021-09-17 21:04
Hello @witcherenjoyer, `"SDL_AUDIODRIVER=pulse"` in your system information and `INFO: SDL_INIT_AUDIO failed: Audio target 'pulse' not available` in the Proton log makes your issue looks like it's #452. Per https://github.com/ValveSoftware/steam-runtime/issues/452#issuecomment-914468898, please opt into the `client_beta` branch of `Steam Linux Runtime - Soldier` in Steam's library and retest.

**Comment by witcherenjoyer** [comment] 2021-09-17 21:40
@kisak-valve Thank you. That worked perfectly. I probably couldve looked harder for a solution but never wouldve thought about sound. Thank you again

**Comment by kisak-valve** [comment] 2021-09-17 21:42
Closing as a duplicate of #452.

**Closed by kisak-valve** 2021-09-17 21:42 UTC
Labels: Need Retest, Pressure Vessel
